### ISSUE TITLE
Cannot use 'in' operator to search for '$ref' in-error when using external schemas

### ISSUE THREAD

**Issue by petetnt** [drwpow/openapi-typescript#1009]
**Description**

Generation fails when trying to reference external (local) files via `$ref`.

```
file:///foo/node_modules/openapi-typescript/dist/transform/components-object.js:44
            if ("$ref" in responseObject) {
                       ^
TypeError: Cannot use 'in' operator to search for '$ref' in external["responses/_index.yaml"]
```

openapi: 3.0.3

https://swagger.io/docs/specification/using-ref/

**OpenAPI**

schema.yaml

```yaml
openapi: 3.0.3
components:
  responses:
    $ref: './responses/_index.yaml'
```

./responses/_index.yaml

```
Foo:
  description: Foo
  content:
    application/text:
      schema:
        type: string
```

**Checklist**

- [x] My OpenAPI schema passes a validator
- [ ] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Remote $refs have been greatly improved in recent versions and this should be fixed now! But please let me know if you still experience the issue
