### ISSUE TITLE
Incorrect tuples generation with v6.x

### ISSUE THREAD

**Issue by Jmenache** [drwpow/openapi-typescript#1011]
**Description**

Hello. Thank you very much for your great work on this library 👍 !!

From v6.0 tuples stopped being properly generated.
I get the following :

```ts
export interface paths {
  "/tupleTest": {
    post: {
      requestBody: {
        content: {
          "application/json; charset=UTF-8": {
            tupleTest: [[[object Object], [object Object]], [[object Object], [object Object]]];
          };
        };
      };
    };
  };
}
```

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `6.1.0`                      |
| Node.js              | `16.13.0`                      |
| OS + version         | `Windows 10` |

**Reproduction**

```json
{
  "openapi": "3.1.0",
  "paths": {
    "/tupleTest": {
      "post": {
        "requestBody": {
          "required": true,
          "content": {
            "application/json; charset=UTF-8": {
              "schema": {
                "type": "object",
                "properties": {
                  "tupleTest": {
                    "type": "array",
                    "minItems": 2,
                    "maxItems": 2,
                    "items": [
                      {"type": "string"},
                      {"type": "number"}
                    ]
                  }
                },
                "required": ["tupleTest"],
                "additionalProperties": false
              }
            }
          }
        }
      }
    }
  }
}

```

**Expected result**

With v5.4.0 I get :
```ts
export interface paths {
  '/tupleTest': {
    post: {
      requestBody: {
        content: {
          'application/json; charset=UTF-8': {
            tupleTest: [string, number];
          };
        };
      };
    };
  };
}
```

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by mitchell-merry** [comment]
This appears to be working in my tests (6.1.1). Could you confirm if this is still happening? i.e. using your example the output is:

```ts
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/tupleTest": {
    post: {
      requestBody: {
        content: {
          "application/json; charset=UTF-8": {
            tupleTest: [string, number];
          };
        };
      };
    };
  };
}

export interface components {}

export interface operations {}

export interface external {}
```

**Comment by liangskyli** [comment]
@mitchell-merry : I also have the same problem here
version: openapi-typescript@6.2.1
```ts
/**
 * This file was auto-generated by @liangskyli/openapi-gen-ts.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/tupleTest": {
    post: {
      requestBody: {
        content: {
          "application/json; charset=UTF-8": {
            tupleTest: ([[object Object], [object Object]])[];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;

```

**Comment by drwpow** [comment]
Agree this needs to be supported. Though I believe the spec requires `prefixItems` to be an array rather than `items`. I think `items` needs to stay as an object (or be set to `false`).

**Comment by liangskyli** [comment]
I think items also need support！
see: https://json-schema.org/draft/2020-12/release-notes.html
<img width="800" alt="image" src="https://user-images.githubusercontent.com/31531283/234135086-ec6017a7-0599-430b-bea8-b08a7d1c094f.png">
because: Draft 2019-09 use items, so we alse need support items!

https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation
<img width="863" alt="image" src="https://user-images.githubusercontent.com/31531283/234135366-f76742d3-cbac-49ea-99d9-d36eac0f96fa.png">
In Draft 4 - 2019-09, tuple validation was handled by an alternate form of the items keyword. When items was an array of schemas instead of a single schema, it behaved the way prefixItems behaves.

**Comment by drwpow** [comment]
With #1082 and #1085 merged this is mostly handled, but I’d like to add support for `prefixItems` when I have time to (I’m working with a spec now that uses that, and I can test it on there)
