### ISSUE TITLE
TypeError when running remote schema example

### ISSUE THREAD

**Issue by vitorcodesalittle** [drwpow/openapi-typescript#1021]
**Description**

Example is found in [README remote schema section](https://github.com/drwpow/openapi-typescript/blob/main/README.md#%EF%B8%8F-reading-remote-schemas)

```bash
npx openapi-typescript https://petstore3.swagger.io/api/v3/openapi.yaml --output petstore.d.ts
```
Output:
```
(node:93903) UnhandledPromiseRejectionWarning: TypeError: options.fetch is not a function
    at load (file:///****/node_modules/openapi-typescript/dist/load.js:80:39)
    at openapiTS (file:///****/node_modules/openapi-typescript/dist/index.js:37:11)
    at generateSchema (file:///****/node_modules/openapi-typescript/bin/cli.js:90:24)
    at main (file:///****/node_modules/openapi-typescript/bin/cli.js:157:11)
    at file:///****/node_modules/openapi-typescript/bin/cli.js:193:1
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:93903) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).
 (rejection id: 2)
(node:93903) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I'm still able to download the schema and run the generator on it as expected, so this issue is not a blocker. Just letting you guys know. 

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `6.1.0`                      |
| Node.js              | `14.20.0`                      |
| OS + version         | `Linux 6.0.11` |

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by larkonesvk** [comment]
Same here

**Comment by JGJP** [comment]
It requires Node 16.8+ to work

**Comment by drwpow** [comment]
v6.0 dropped support for Node 14 ([changelog](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CHANGELOG.md#600)). Node 16+ is required (but newer is always preferred). Node 14 is near EOL anyway.
