### ISSUE TITLE
ReadOnly property is not processed for an individual field

### ISSUE THREAD

**Issue by DanielTrommel** [drwpow/openapi-typescript#1030]
A definition with an individual readonly property does not produce a type/interface definition with a readonly property.

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `6.1.0`                      |
| Node.js              | `v18.12.1`                      |
| OS + version         | `Windows 10` |

**Reproduction**

a YAML definition like this:
![image](https://user-images.githubusercontent.com/20012984/217649786-228c398a-131b-4554-8c2e-9421b67908f6.png)

**Expected result**

...should produce a readonly property like this:
![image](https://user-images.githubusercontent.com/20012984/217650031-79f491e8-d585-4c48-a702-38f8ab197c4e.png)
but it does not...

**Solution proposal**

`Line 174`  in  `\transform\schema-object.ts`  is currently:

`if (ctx.immutableTypes || schemaObject.readOnly) key = tsReadonly(key);`

and should(?) be:

`if (ctx.immutableTypes || schemaObject.readOnly || ("readOnly" in v && v.readOnly)) key = tsReadonly(key);`

Also notice that no test exists for the "readonly" case in  `schema-object-test.ts`.

**Question**
I tried to push this fix to this repo on a new branch (to open a PR), but got a HTTP 403. 
Hopefully someone else can submit this fix instead?

**Comment by olivierbeaulieu** [comment]
I think you're misunderstanding OpenAPI's readOnly annotation. It has nothing to do with TypeScript's readonly modifier.

From the [spec](https://swagger.io/docs/specification/data-models/data-types/):

> Read-Only and Write-Only Properties
> You can use the readOnly and writeOnly keywords to mark specific properties as read-only or write-only. This is useful, for example, when GET returns more properties than used in POST – you can use the same schema in both GET and POST and mark the extra properties as readOnly. readOnly properties are included in responses but not in requests, and writeOnly properties may be sent in requests but not in responses.

openapi-typescript does not handle readOnly and writeOnly properly even by that definition though, see issue https://github.com/drwpow/openapi-typescript/issues/604

**Comment by DanielTrommel** [comment]
Thanks for taking the time; I indeed misunderstood and will close this issue.
