### ISSUE TITLE
type: "object" being parsed as empty object

### ISSUE THREAD

**Issue by jackstar12** [drwpow/openapi-typescript#1031]
**Description**

A brief description of the issue.
A schema of type: "object" with no other information specified is being parsed as an empty (Record<string, never>) object, but I would expect it to be an Record<string, any>

I think it would have to be changed in here, correct me if I'm wrong:
https://github.com/drwpow/openapi-typescript/blob/3ffb475d15352ebc1dd2f823b01d3ae8b18ef68b/src/transform/schema-object.ts#L244

<html><body>

Name | Version
-- | --
openapi-typescript | 6.1.0
Node.js | v16.13.2
OS + version | Windows 10

</body>
</html>

**OpenAPI**
![image](https://user-images.githubusercontent.com/62219658/218279717-67fac4bc-112e-4aa7-bc4e-ae1de9f2c653.png)

**Generated TS**

```ts
    DocumentModel: {
      /** Type */
      type?: string;
      /** Content */
      content?: (components["schemas"]["DocumentModel"])[];
      /** Text */
      text?: string;
      /** Attrs */
      attrs?: Record<string, never>;
      /** Marks */
      marks?: (components["schemas"]["Mark"])[];
    };
```

**Expected TS*

```ts
    DocumentModel: {
      /** Type */
      type?: string;
      /** Content */
      content?: (components["schemas"]["DocumentModel"])[];
      /** Text */
      text?: string;
      /** Attrs */
      attrs?: Record<string, any>;
      /** Marks */
      marks?: (components["schemas"]["Mark"])[];
    };
```

**Checklist**

- [x ] My OpenAPI schema passes a validator
- [x ] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by mitchell-merry** [comment]
Disagree. In my opinion it should just generate to the `object` type. That way, if you try to access a property on the object, you need to validate that it both exists first and that the type is what you expect.

Alternatively, I could see `Record<string, unknown>` so you at least have to prove the type. I really dislike the idea of introducing `any`s.

**Comment by jackstar12** [comment]
That makes sense, yeah.
A `Record<string, unknown>` would fix my issue aswell and describes the situation better without introducing an any.

Would the fix be as simple as changing the fallback type in the line mentioned above?

**Comment by duncanbeevers** [comment]
I needed this for work, so I went ahead and opened a PR with the `Record<string, unknown>` behavior.
