### ISSUE TITLE
Cannot use 'in' operator to search for '$ref' in …

### ISSUE THREAD

**Issue by nevir** [drwpow/openapi-typescript#1038]
**Description**

When parsing [Zoom's Webhook API spec](https://marketplace.zoom.us/docs/api-reference/zoom-api/events/#overview) (click download) – which is valid according to [swagger-cli](https://apitools.dev/swagger-cli/) – we run into various errors where code is expecting an object, but receiving a string (in `"anyOf"` statements)

```
$ openapi-typescript ./zoom-spec.json
<project>/openapi-typescript/dist/load.js:150
                    if (!("$ref" in o) || typeof o.$ref !== "string")
                                 ^

TypeError: Cannot use 'in' operator to search for '$ref' in schedule_meeting
    at <project>/openapi-typescript/dist/load.js:150:34
    at Array.filter (<anonymous>)
    at <project>/openapi-typescript/dist/load.js:149:41
    at walk (<project>/openapi-typescript/dist/utils.js:26:5)
    at walk (<project>/openapi-typescript/dist/utils.js:28:9)
    at walk (<project>/openapi-typescript/dist/utils.js:28:9)
    at walk (<project>/openapi-typescript/dist/utils.js:28:9)
    at walk (<project>/openapi-typescript/dist/utils.js:28:9)
    at walk (<project>/openapi-typescript/dist/utils.js:28:9)
    at walk (<project>/openapi-typescript/dist/utils.js:28:9)
```

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `6.1.1`                      |
| Node.js              | `18.14.2`                      |
| OS + version         | `macOS 12.6.2` |

**Reproduction**

Download the spec from [Zoom's Webhook API docs](https://marketplace.zoom.us/docs/api-reference/zoom-api/events/#overview), and run `openapi-typescript` against it

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Yes as @mitchell-merry pointed out, this spec actually is invalid. It’s a shame that the swagger-cli isn’t better at validation :( (also worth noting that the swagger-cli doesn’t support 3.1 either). `@redocly/cli lint [zoomapi.json]` is a much better validator, and that surfaces myriad issues with the Zoom spec.

I’m going to close this, but if there’s another issue with `oneOf` that does pass validation, happy to reasses.

**Comment by smein** [comment]
Getting the same thing with the cloudflare api schema:

`npx openapi-typescript  https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.json -o cloudflare.d.ts`


TypeError: Cannot use 'in' operator to search for '$ref' in null

**Comment by drwpow** [comment]
@smein That schema is invalid; in places it uses string `enum`s for `type: object` schema objects. Be sure to run `@redocly/cli lint` on schemas first if you see unexpected errors like that.
