### ISSUE TITLE
Parameters missing in the generated output

### ISSUE THREAD

**Issue by tonyxiao** [drwpow/openapi-typescript#1040]
Given this input spec

https://gist.github.com/tonyxiao/9d37b8e908ad51319b9225e7a19bc632#file-venice-openapi3-json

Note parameters are specified for `/account` endpoint
![CleanShot 2023-03-01 at 10 44 02@2x](https://user-images.githubusercontent.com/696842/222031760-af18cd9a-bf3f-4fb2-97b5-e40cd506ab3d.png)

The generated output https://gist.github.com/tonyxiao/9d37b8e908ad51319b9225e7a19bc632#file-venice-gen-ts does not contain any params for the `/acocunt` endpoint

![CleanShot 2023-03-01 at 10 45 58@2x](https://user-images.githubusercontent.com/696842/222031991-9f72f52c-9d81-4c9a-9f2b-7676462cb4a3.png)

**Comment by wolfy1339** [comment]
Duplicate of #984

**Comment by tonyxiao** [comment]
Ah, thanks, closing then. Will track over there.
