### ISSUE TITLE
External Refs don't work in v6

### ISSUE THREAD

**Issue by asdaandrewhaigh** [drwpow/openapi-typescript#1041]
**Description**

If you have an Open API Specification in YAML which references another Open API Specification, say in order to support common types, the code is not correctly generated in v6 compared to the code generated in v5.

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `5.4.1` and `6.1.1`                      |
| Node.js              | `18.14.2`                      |
| OS + version         | `macOS 13.2.1` |

**Reproduction**

Given a Common.yaml containing:

```yaml
openapi: 3.1.0
info:
  title: Common API Components
  version: 1.0.0
  summary: The common API Components
components:
  schemas:
    User:
      title: User
      type: object
      description: Example User
      examples:
        - id: 142
          firstName: Alice
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
      required:
        - id
        - firstName
```

Given an api.yaml which references common.yaml:

```yaml
openapi: 3.1.0
x-stoplight:
  id: 42f45qvowo3cx
info:
  title: Sample API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: common.yaml#/components/schemas/User
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
components:
  schemas: {}
```

When the command (v5) is run: `npx --yes openapi-typescript@5 ./api.yaml --output out.v5.ts` the following is output to screen:

```bash
✨ openapi-typescript 5.4.1
🚀 ./api.yaml -> /Users/xxxx/Documents/StoplightStudio/codegen-sample/reference/out.v5.ts [102ms]
```

The generated `out.v5.ts` contains, the following external block:

```typescript
export interface external {
  "common.yaml": {
    paths: {};
    components: {
      schemas: {
        /**
         * User
         * @description Example User
         */
        User: {
          /** @description Unique identifier for the given user. */
          id: number;
          firstName: string;
        };
      };
    };
    operations: {};
  };
}
```

When the command (v6) is run: `npx --yes openapi-typescript@6 ./api.yaml --output out.v6.ts` the following is output to screen:

```bash
✨ openapi-typescript 6.1.1
🚀 ./api.yaml → file:///Users/xxxx/Documents/StoplightStudio/codegen-sample/reference/out.v6.ts [28ms]
```

The generated `out.v6.ts` contains, the following external block:

```typescript
export interface external {

  "common.yaml": Record<string, never>
}
```

**Expected result**

Version 6 external code should be generated as per version 5 external code.

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by sebmos** [comment]
For what it's worth, some additional precision: External refs that contain individual schemas still works - it's referencing complete OpenAPI specification files that's broken.
