### ISSUE TITLE
Type error in utils.ts due to missing tsconfig in production build

### ISSUE THREAD

**Issue by jonluca** [drwpow/openapi-typescript#1058]
**Description**

The file "utils.ts" imports from "types.ts", but the production build doesn't include the tsconfig, so typescript does not know that it is a local file.

<img width="1044" alt="capture 2023-03-28 at 12 15 31 PM" src="https://user-images.githubusercontent.com/13029040/228343826-23063f36-5327-43a0-8190-08bb33855a04.png">

This causes errors in external libraries using these types.

<img width="1022" alt="capture 2023-03-28 at 12 16 42 PM" src="https://user-images.githubusercontent.com/13029040/228344020-fb7387db-f327-4c83-839e-493711e52542.png">

```
yarn typecheck
yarn run v1.22.19
$ tsc --noEmit
node_modules/openapi-typescript/src/utils.ts:5:23 - error TS2307: Cannot find module 'types' or its corresponding type declarations.

5 import { Fetch } from "types";
                        ~~~~~~~


Found 1 error in node_modules/openapi-typescript/src/utils.ts:5
```

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 405.84 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.2 - ~/Documents/Other/openapi-schema-to-json-schema/node_modules/.bin/npm
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.146
    Firefox: 111.0
    Safari: 16.3

**Reproduction**

Bump the version to 6.2.0 and add it to a project. My tsconfig looks like so:

```json
{
  "compilerOptions": {
    "module": "esnext",
    "outDir": "dist/mjs",
    "target": "es2020",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "src",
    "declaration": true,
    "esModuleInterop": true,
    "inlineSourceMap": false,
    "lib": ["esnext"],
    "listEmittedFiles": false,
    "listFiles": false,
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "pretty": true,
    "resolveJsonModule": true,
    "rootDir": "src",
    "skipLibCheck": true,
    "noImplicitAny": false,
    "strict": true,
    "noUnusedParameters": true,
    "sourceMap": true
  },
  "compileOnSave": false,
  "exclude": ["node_modules", "dist", "coverage", "bin"],
  "include": ["src"]
}
```

**Expected result**

_(in case it’s not obvious)_

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by jonluca** [comment]
This occurs in this library https://github.com/openapi-contrib/openapi-schema-to-json-schema

Looks like it first started happening in 6.0

**Comment by drwpow** [comment]
I don’t think `tsconfig.json` is what’s causing this, but `utils.js` is missing a required extension for ESM. Will fix! Thank you.
