### ISSUE TITLE
Tiny mistakes in MediaTypeObject encoding property type

### ISSUE THREAD

**Issue by marcomuser** [drwpow/openapi-typescript#1062]
**Description**

I'm currently building on the side and for fun a fetch codegen tool that uses openapi-typescript internally to generate the types and reference them from the generated fetch functions (no idea if this is the best approach but it's been a lot of fun building it so far). I'm thereby also reusing the internal OpenAPI types that openapi-typescript uses for sake of simplicity. I noticed two small issues:

1. the `encoding` property in the `MediaTypeObject` expects a `contentType` key of type string that holds the EncodingObject as value. This is a bit misleading. The shape is correct but the key will not be a `contentType` but the `name` of the property that should be encoded in the specified way. See in the [OpenApi Spec](https://spec.openapis.org/oas/latest.html#fixed-fields-11).
2. `explode` in the `EncodingObject` is typed as string but it should be boolean: https://github.com/drwpow/openapi-typescript/blob/main/src/types.ts#L300

```

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `6.2.0`                      |
| Node.js              | `18.14.0`                      |
| OS + version         | `Fedora 37` |

**Reproduction**

https://github.com/drwpow/openapi-typescript/blob/main/src/types.ts#L285
https://github.com/drwpow/openapi-typescript/blob/main/src/types.ts#L300

**Expected result**

encoding?: { [name: string]: EncodingObject };
AND
explode?: boolean;

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by mitchell-merry** [comment]
Seems reasonable, feel free to open a PR
