### ISSUE TITLE
Augment operation parameters for type-safety and ergonomics?

### ISSUE THREAD

**Issue by shoffmeister** [drwpow/openapi-typescript#1074]
**Description**

The code generator faithfully produces code which matches an OpenAPI contract - but OpenAPI (sometimes) is not powerful enough to express the constraints / requirements of (string) parameters.

Typescript, on the other hand, is very richly typed and therefore allows for much more expressive API contracts on the consumer side.

I would love to be able to augment the generated code for an existing OpenAPI contract (which is outside of my sphere of influence) so that the Typescript client interface is more ergonomic and safer to use, much in the spirit of Typescript SQL abstraction tooling such as listed at https://phiresky.github.io/blog/2020/sql-libs-for-typescript/

**Proposal - or perhaps it's just a question?**

The API in question is documented at https://www.dynatrace.com/support/help/dynatrace-api. Alas, I am not aware of the contract being available for download, so I am going to refer to representative Typescript consumer usage below to show my challenge. The generated Dynatrace Typescript contract has roughly 17'000 lines of code, BTW.

Part of the Dynatrace API is https://www.dynatrace.com/support/help/dynatrace-api/environment-api/events-v2/get-events which - through `string` parameters `from`, `to`, `eventSelector`, `entitySelector` - effectively exposes a custom query language. There are other parts of the API (metrics queries) where this gets even more exciting.

Now, instead of writing the "code" for the custom query language as a plain string, to be passed as a string, the Typescript type system allows me to create an abstraction over the query language, enforcing that the string provided via the API does match the API's requirement. The sample code below demonstrates this with class `ComplexParam` being the query language producer.

Now, the easiest way to invoke the API is to simply pass ComplexParam.toString(). While this _works_, I'd rather enforce the underlying type being used, ultimately to reduce room for human error, to improve ergonomics.

I have tried to use Typescript [Module Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) to augment "complexParam" with a definition of my own (intersect, replace), but ultimately was not successful.

So, I am looking for a feature (or suggestions) on how to get this augmentation done with `openapi-typescript` :)

FWIW, while I simply could create an adapter, my goal is to surgically inject improved typing into a few select parts of that API. Similarly, I could just edit the generated code. But All That Is Just Wrong ;)

The client-side sample hopefully outlining the challenge:
```
import { paths } from './my-api.yaml'
//import { paths } from './my-api.yaml-wrapper' // failed experiments with module augmentation

import createClient from "openapi-fetch";

const { get } = createClient<paths>({});

class ComplexParam {

    constructor(readonly a, readonly b, readonly c) {}

    public toString(): string {
        return this.a + this.b + this.c;
    }

    public static of(a, b, c): ComplexParam {
        return new ComplexParam(a, b, c);
    }
}

// string as defined on API
const { } = await get("/test", {params:{query:{ complexParam: "value" }}});  

// convert to string, to satisfy API
const { } = await get("/test", {params:{query:{ complexParam: ComplexParam.of(1, 2, 3).toString() }}});  

// ergonomic, type-safe way to work with API
// currently yields: "Type 'ComplexParam' is not assignable to type 'string'"
const { } = await get("/test", {params:{query:{ complexParam: ComplexParam.of(1, 2, 3) }}});  
```

**Comment by mitchell-merry** [comment]
I haven't looked into the specifics of your question, but have you looked into the `transform` option with the Node API? https://github.com/drwpow/openapi-typescript#-transform--posttransform

**Comment by shoffmeister** [comment]
`inject` and `transform` deliver exactly what I need - thank you very much for making me read the documentation to the very end!

The code below will unconditionally swap out the existing type on a given query parameter for `ComplexParam`; 

```javascript
const types = await openapiTS(JSON.parse(dynatraceSchema), {

  immutableTypes: false,

  inject: `

import * as enriched from './enriched'

// ... and even more injected types for ergonomics

export interface ComplexParam extends enriched.ComplexParamExternal { reallyComplex: string; }
`,

  transform (schemaObject, metadata) {
    if (metadata.path === '#/paths//events/parameters/from') {
      return schemaObject.nullable ? 'ComplexParam | null' : 'ComplexParam'
    }

    if (metadata.path === '#/paths//events/parameters/to') {
      return schemaObject.nullable ? 'enriched.ComplexParamExternal | null' : 'enriched.ComplexParamExternal'
    }
  }

})
```

**Comment by mitchell-merry** [comment]
Awesome. Sounds like this can be closed?

**Comment by shoffmeister** [comment]
Yes, indeed - many thanks for your support and the great tooling!
