### ISSUE TITLE
The generated OneOf type can cause issues for large files

### ISSUE THREAD

**Issue by creativecreature** [drwpow/openapi-typescript#1077]
**Description**
I have a response where the generated types looks like this:

```
data: {
  [key: string]: { items: OneOf<[_TWELVE_DIFFERENT_TYPES_]> }
}
```

The typescript compiler errors at the usage of `OneOf` with the following error: `Type instantiation is excessively deep and possibly infinite`.

Would it be possible to detect where issues like this could occur and use unions instead?

So in my case it would be something like:

```
data: {
  [key: string]: { items: [Type1 | Type2 | Type3 ... | Type12] }
}
```

**Comment by wiktor-obrebski** [comment]
I have same issue with 9 types in `OneOf<...>`. Clearly it something wrong with `OneOf` definition.
I using `typescript@5.0.2`.

**Comment by sebastian-fredriksson-bernholtz** [comment]
I'm not sure if it's worth the tradeoff, but I patched openapi-typescript to use union `|` instead of the `OneOf` generic type to handle this in a project of mine. 

It seems like the cost of this issue might outweigh the value of being strict about excess properties.

**Comment by drwpow** [comment]
Please try the most recent release, and let me know if that fixes your issue!
