### ISSUE TITLE
using --default-non-nullable do not generate schema.ts

### ISSUE THREAD

**Issue by anthony-bernardo** [drwpow/openapi-typescript#1078]
**Description**

when launching `--default-non-nullable` parameter
the script freeze, nothing is generated

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `^6.2.1`                      |
| Node.js              | `v18.13.0`                      |
| OS + version         | `macOS 13.3.1` |

**Reproduction**

`npx openapi-typescript --default-non-nullable ./openapi.yml --output schema.ts`

with openapiyml 

```
openapi: 3.0.0
info:
  title: 'Hello API Platform'
  description: ''
  version: 1.0.0
servers:
  - url: /
    description: ''
components:
  schemas:
    Company:
      type: object
      description: ''
      deprecated: false
      properties:
        id:
          readOnly: true
          type: integer
        name:
          type: string
```

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by mitchell-merry** [comment]
The option goes after the source argument.
```
npx openapi-typescript ./openapi.yml --output schema.ts --default-non-nullable 
```
I believe this fixes your issue.
