### ISSUE TITLE
RequestBody is optional in our generated code, breaks openapi-fetch

### ISSUE THREAD

**Issue by davidkraus** [drwpow/openapi-typescript#1101]
**Description**

We generated the types with openapi-typescript 6.2.4. This resulted in the following code:
```typescript
...
"/api/xyz" : {
  post: {
    requestBody?: { ... }
  }
}
```
So the requestBody is optional, this however breaks the type checking in openapi-fetch it seems:
see https://github.com/drwpow/openapi-typescript/blob/7e4164cf566e0b1460193cd775a119fb5322d4aa/packages/openapi-fetch/src/index.ts#L39

changing the type above to 
```typescript
export type RequestBodyObj<O> = O extends { requestBody?: any } ? O["requestBody"] : never;
```
fixes the problem. Or is that a bug in the generator?

**Comment by drwpow** [comment]
This has been fixed in `openapi-fetch@0.1.4`; it was an issue with that library and not openapi-typescript (but I’m actually about to merge the two repos together so you can get extra bang for your buck filing issues! 😄)

**Comment by Wafje** [comment]
Could it be that this bug popped up again?
I have the same issue like @davidkraus is describing.

**Comment by drwpow** [comment]
@Wafje what version of openapi-fetch specifically? there were quite a few type changes recently so an exact version would be easier to debug

Also which version of TypeScript? that could affect it too

**Comment by Wafje** [comment]
Hi, I missed this update.
I am using openapi-fetch 0.9.3 with openapi-typescript 6.7.5

I am using this command as a workaround:
`"openapi-typescript http://localhost:4000/swagger/json -o ./api/api.d.ts && sed -i 's/requestBody?/requestBody/g' ./api/api.d.ts"`

It replaces `requestBody?` with `requestBody`, fixing the type checking.

**Comment by streetguy911** [comment]
@drwpow can you please explain why the requestBody field is generated as optional?

**Comment by dawsonbooth** [comment]
I'm just running into this issue myself. Why is `requestBody` generated as optional even though it can be required? This seems intentional per your comment, @drwpow.

Is there any way we can distinguish between required and optional request bodies?
