### ISSUE TITLE
feature: openapi-typescript derived types for Express handler functions

### ISSUE THREAD

**Issue by duncanbeevers** [drwpow/openapi-typescript#1144]
### 🧅 Express

We use [`express-openapi-validator`](https://github.com/cdimascio/express-openapi-validator/wiki/Documentation) to great effect, mapping requests to handlers.
However, in the handlers themselves we don't have any type-safety around the inputs / request to the handler, nor around the outputs / responses.

### 👑 Solution

We'd like an official way to add types to an Express handler, such that it conforms to the expectations expressed in the OpenAPI schema, and the types generated by `openapi-typescript`.
This may be out-of-scope for this project, but here seemed like a good starting point for the discussion.

### 🎡 Our Work

We have a working implementation of the proposed work, which consumes types as generated by `openapi-typescript`, and provides types for Express handlers.

[express-openapi.ts](https://gist.github.com/duncanbeevers/47ecbe7d51f922de5365950e4a45a001)

These typings provide a few niceties.
* Types for OpenAPI-declared inputs on Express Request
  * `req.body`
  * `req.params`
  * `req.query`
* Types for OpenAPI-declared output on Express Response
  * `res.send(…)` and `res.json(…) assume 200 OpenAPI-declared response code and enforce response body
  * `res.sendStatus(statusCode)` limited to OpenAPI-declared responses with no response body
  * `res.status(statusCode)` limited to OpenAPI-declared response codes
  * `res.status(statusCode)` limits fluent API to `.send(…)` and `.json(…)`, and enforces status-specific response body

### 🥦 Short-comings

This solution is reasonable, but has grown organically around our own usage of OpenAPI and `openapi-typescript`.

#### 🔪 Awkward to Use

In order to declare a handler we're using a type-cast and string-lookup. It would be nice to have something a bit more automatic.

```ts
import operations from 'generated/api';

export default (async function getTodo(req, res) {
  res.json(await Todo.findOne({ _id: req.params.id }));
} as OpenAPIHandler<operations['getTodo']>);
```

#### 🎩  No handling of Headers

The proposed types don't (yet) handle Header parameters, since we haven't needed those in practice. These types would need to bridge more of the OpenAPI spec to Express-equivalents.

#### 🐣 Poor fit

Maybe this just isn't the right repo for this framework-specific functionality.

### 💪 Next Steps

Do framework-specific integrations seem like something you want to bring under the roof of `openapi-typescript`?
Is there somewhere else this kind of functionality / tooling should live?

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Excellent proposal! Now that this is more of a monorepo, it should be easier to publish a thin wrapper around openapi-typescript (if that’s even needed).

This is the 2nd request for this to happen; the first came [as a PR last year](https://github.com/drwpow/openapi-typescript/pull/943). I also know there are other people doing similar things that aren’t represented as issues/PRs here. I think there’s enough quorum to pursue a better solution for everyone.

One determination whether it’s a good fit or not for this library is whether this would require **runtime** or **static** types to work. I didn’t realize at first that this library strongly enforces principles of static typing, i.e. has no runtime. There are many other approaches to typed code such as `openapi-zod-client` that do require runtime code (and therefore have performance impacts, but as a tradeoff for being able to return errors to the user). From your description it sounds like this would be a good fit because you’re already using openapi-typescript, but wanted to call that out.

I’ll have a think about this and see if there’s anything else I would add to this proposal before tackling this.

**Comment by mitchell-merry** [comment]
Is this proposal for adding a library to this monorepo that validates the types, or simply does the mapping with assertion?

**Comment by duncanbeevers** [comment]
> Is this proposal for adding a library to this monorepo that validates the types, or simply does the mapping with assertion?

I think it's more like the latter.
In our practice, the `express-openapi-validator` is doing most of the heavy lifting.
* mapping incoming requests to specific handlers
* validating request shapes
* performing custom [deserialization](https://github.com/cdimascio/express-openapi-validator/wiki/Documentation#%EF%B8%8F-serdes-optional) of request data
* validating response shapes
* performing custom serialization

This proposal is for a compile-time layer that provides type-safety while developing Express handlers for OpenAPI endpoints, but has no run-time portion.

I'm also flexible as to what the final form of this looks-like, but I'm very bullish on compile-time approach enabled by openapi-typescript, and exemplified in openapi-fetch.

**Comment by mitchell-merry** [comment]
@duncanbeevers Agreed! 

I think we should get an API proposal for this. Could you provide what you had in mind?

**Comment by duncanbeevers** [comment]
After further consideration, I'd selfishly rather not see this functionality included in `openapi-typescript`, as I wouldn't be able to offer adequate support.

If there's sufficient demand for these Express typings, or typings for other frameworks, perhaps they can be published independently, and @drwpow can link to them from the official documentation.

**Comment by drwpow** [comment]
I haven’t looked into this much at all, but recently ran across [feTS](https://github.com/ardatan/feTS) which can create a typed server endpoint around an OpenAPI schema. I think it’s higher-level than Express, but even if this is too limiting, there may be some good ideas there.

**Comment by duncanbeevers** [comment]
Closing for now. Thanks for the consideration everyone.
