### ISSUE TITLE
Creating a generic to generate the HTTP method functions

### ISSUE THREAD

**Issue by Darkchove** [drwpow/openapi-typescript#1152]
Creating a generic createMethodFunction to generate the HTTP method functions (get, put, post, etc.).

**Comment by drwpow** [comment]
I’m not sure what your issue is. Please open up a new issue using one of the preexisting templates that specifies whether this is for `openapi-typescript` or `openapi-fetch`, and whether this is a feature or bugfix. Please fill out the template! It really helps 🙂
