### ISSUE TITLE
a separate constant

### ISSUE THREAD

**Issue by Darkchove** [drwpow/openapi-typescript#1154]
**Description**

Extract the default query serializer function into a separate constant defaultQuerySerializer.

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This exists! It’s not documented, but you can `import { defaultQuerySerializer } from 'openapi-fetch';` in the latest version.
