### ISSUE TITLE
openapi-typescript errors with options.fetch is not a function

### ISSUE THREAD

**Issue by ukuhnhardt** [drwpow/openapi-typescript#1155]
**Description**

calling openapi-typescript with a url source throws error.

```
$ npx openapi-typescript https://petstore3.swagger.io/api/v3/openapi.yaml -o petstore.d.ts
✨ openapi-typescript 6.2.6
(node:18153) UnhandledPromiseRejectionWarning: TypeError: options.fetch is not a function
    at load (file:///Users/ukuhnhardt/src/uk/jira/ai-insights-ace/node_modules/openapi-typescript/dist/load.js:78:39)
    at openapiTS (file:///Users/ukuhnhardt/src/uk/jira/ai-insights-ace/node_modules/openapi-typescript/dist/index.js:41:11)
    at generateSchema (file:///Users/ukuhnhardt/src/uk/jira/ai-insights-ace/node_modules/openapi-typescript/bin/cli.js:94:24)
    at main (file:///Users/ukuhnhardt/src/uk/jira/ai-insights-ace/node_modules/openapi-typescript/bin/cli.js:167:11)
    at file:///Users/ukuhnhardt/src/uk/jira/ai-insights-ace/node_modules/openapi-typescript/bin/cli.js:203:1
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.2.6`                      |
| Node.js              | `14.21.3`                      |
| OS + version         | `macOS 13` |

**Reproduction**

`npx openapi-typescript https://petstore3.swagger.io/api/v3/openapi.yaml -o petstore.d.ts`

**Expected result**

typescript

**Checklist**

- [ /] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by ukuhnhardt** [comment]
Downloading the remote schema with curl and then running openapi-typescript works
```
$ curl https://petstore3.swagger.io/api/v3/openapi.yaml -o openapi.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20887    0 20887    0     0   9845      0 --:--:--  0:00:02 --:--:--  9875
$ npx openapi-typescript openapi.yaml -o petstore.d.ts
✨ openapi-typescript 6.2.6
🚀 openapi.yaml → file:///petstore.d.ts [29ms]

**Comment by drwpow** [comment]
This is a known issue with Node 14. Updating to 16+ (ideally 20) will fix the error (which is recommended anyway as Node 14 is end of life)

**Comment by drwpow** [comment]
Unfortunately we can’t support bugfixes for a deprecated version of Node. As a workaround, I’d recommend downgrading to 5.x as that is still Node 14 compatible. And for the most part 5.x and 6.x generate the same types with only minor differences. And 6.x supports OpenAPI 3.1 features.

**Comment by mwotton** [comment]
@drwpow is there some version of openapi-fetch that works on node 14? I tried polyfilling node-fetch in to get Headers, fetch etc, but there are a heap of type errors. I can't upgrade the version of node I'm using, unfortunately, it's not my project.

**Comment by drwpow** [comment]
Unfortunately, no, Node versions < 18 are no longer supported in most OSS projects or even by Node itself. It’s not only just a maintenance issue—supporting old versions requires a lot of work that projects don’t have the resources for. But it’s also a security issue. I know you said you don’t have control, but most projects can update Node versions fairly easily. There aren’t that many breaking changes that make it a difficult task. In many project it’s a quick, painless upgrade.
