### ISSUE TITLE
Support application/x-www-form-urlencoded body

### ISSUE THREAD

**Issue by elliots** [drwpow/openapi-typescript#1157]
**Description**

Support form encoded body

**Proposal**

```js

// handle body the same way as json in the client

// on fetch:
headers:{
  'Content-Type': 'application/x-www-form-urlencoded'
},    

body: new URLSearchParams({
   hello: 'world,
})
````
**Checklist**

- [X] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This has been added as of `0.6.0`! 🎉 Please let me know if you are still encountering issues.
