### ISSUE TITLE
External components referencing global components

### ISSUE THREAD

**Issue by pvanagtmaal** [drwpow/openapi-typescript#1160]
**Description**

When referencing a definition in an external schema, and that definition is also a reference, it is referenced as if it were in the components of the main schema.

I've looked at the code to see if this was easy to overcome but I did not see a straightforward fix. Of course, it is possible to fully quantify the file in the external ref (so filename would not become '.') but that's adjusting the schema to the code generator.

```
Paste full error message
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.2.6`                      |
| Node.js              | `18.10.0`                      |
| OS + version         | `macOS 13` |

**Reproduction**

Create two schemas, `external-test.yaml` and `external-test-2.yaml`:

```yaml
openapi: "3.0"
info:
  title: test
  version: "1.0"
paths: {}
components:
  schemas:
    external:
      $ref: 'external-test-2.yaml#/components/schemas/external'
```

```yaml
openapi: "3.0"
info:
  title: test
  version: "1.0"
paths: {}
components:
  schemas:
    external:
      $ref: '#/components/schemas/stringOrNumber'
    stringOrNumber:
      oneOf:
        - type: string
        - type: number
```

**Expected result**

```ts
export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    external: external["external-test-2.yaml"]["components"]["schemas"]["external"];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export interface external {
  "external-test-2.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: {
      schemas: {
       // This currently is components["schemas"]["stringOrNumber"]
        external: external["external-test-2.yaml"]["components"]["schemas"]["stringOrNumber"];
        stringOrNumber: string | number;
      };
      responses: never;
      parameters: never;
      requestBodies: never;
      headers: never;
      pathItems: never;
    };
  };
}

export type operations = Record<string, never>;
```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Ah I can imagine how this is a problem. Thank you for the clear description and recreation. Yes this is probably the hardest, least-straightforward part of the codebase, and there’s not an easy fix. But will look into fixing this as this is perfectly valid and should work.

**Comment by drwpow** [comment]
Closing as some recent versions have fixed quite a few bugs in this exact area. But please reopen if the issue still isn’t resolved
