### ISSUE TITLE
Property names with at sign throw parsing error in declaration file

### ISSUE THREAD

**Issue by corydeppen** [drwpow/openapi-typescript#1162]
**Description**

After generating the types, there are errors (e.g. `Parsing error: Property or signature expected`) in the `.d.ts` file that appear to be caused by unquoted property names that include an at sign. The following is a snippet taken from a [StackPath OpenAPI doc](https://stackpath.dev/openapi/5cf6ebff8cfef2001a725195).

```json
"apiStatusDetail": {
  "type": "object",
  "properties": { "@type": { "type": "string" } },
  "required": ["@type"],
  "discriminator": { "propertyName": "@type" }
}
```

The generated file includes the following:

```ts
"stackpath.rpc.Help": {
  @type: "stackpath.rpc.Help";
} & Omit<components["schemas"]["apiStatusDetail"], "@type"> & {
  links?: (components["schemas"]["stackpath.rpc.Help.Link"])[];
};
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.2.6`                      |
| Node.js              | `18.16.0`                      |
| OS + version         | `macOS 12.6.6` |

**Expected result**

Property names that include an at sign should be quoted (e.g. `"@type": "stackpath.rpc.Help";`).

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This is a bug in the RegEx that detects when object keys in JS need to be escaped or not (while also escaping `/` and `~` needed for `$ref`s). Should be a simple fix.

**Comment by pvanagtmaal** [comment]
@drwpow I'm looking into this now and I don't think it's the regex, rather [this line](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/src/transform/schema-object.ts#L181) seems to be missing an `escObjKey` call for the property name.
