### ISSUE TITLE
Error when response is plain text / csv

### ISSUE THREAD

**Issue by Visual-Dawg** [drwpow/openapi-typescript#1165]
**Description**

The parsing of the response fails when the response is not `json`.
Subsequently responses of `text/plain` and `text/csv` throw an error, which is not returned, but remains uncaught.

**Reproduction**

Query an api endpoint which return `text/*`, like `https://api64.ipify.org`.

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This is improved in `0.3.0`. Now, the `.json()` response will fall back to `.text()`. Or you can override the default behavior with the [parseAs option](https://openapi-ts.pages.dev/openapi-fetch/api/#fetch-options)

**Comment by CEOehis** [comment]
@drwpow is there a parse-as flag for the openapi-typescript CLI?

**Comment by drwpow** [comment]
> @drwpow is there a parse-as flag for the openapi-typescript CLI?

There’s not. It sounds like your server isn’t sending the right MIME types. The best solution is fixing that. But as a workaround you could write a short script that saves that file to a temporary local `.json` file and just running `openapi-typescript` locally.

Making the wrong “guess” of whether something is JSON or YAML is expensive and slows down everyone.
