### ISSUE TITLE
An empty object as the request body generates an invalid TS definition

### ISSUE THREAD

**Issue by vojty** [drwpow/openapi-typescript#1174]
**Description**

An empty object as the request body generates an invalid TS definitionL

```
export interface operations {

  /**
   * Test 
   * @description Body is ignored
   */
  test: {
    requestBody?: "*/*": never; // <-------------------------------
    responses: {
      /** @description No Content */
      204: never;
      /** @description Bad Request */
      400: never;
    };
  };
}

```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.2.8`                      |
| Node.js              | `18.6.0`                      |

**Reproduction**

Example YAML:
```yaml
openapi: 3.0.1
info:
  title: Test
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080
security:
  - api_keys: []
paths:
  /api/v1/test:
    post:
      operationId: test
      summary: Test
      description: Body is ignored
      requestBody:
        required: false
        content: {}
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
components:
  securitySchemes:
    api_keys:
      description: |
        Generate your secret API key in the app settings.
      name: secret-key
      type: apiKey
      in: header

```

The problem can be mitigated by removing `requestBody` completely in this case, but still it shouldn't generate invalid TS syntax.

**Expected result**

_(in case it’s not obvious)_

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Thanks for the great example! This should be an easy find & fix.

**Comment by drwpow** [comment]
Related: #1109
