### ISSUE TITLE
CJS not in bundle after latest PR

### ISSUE THREAD

**Issue by dino-rodriguez** [drwpow/openapi-typescript#1185]
The `.cjs` module is not present for openapi-fetch after fetching the module with `npm` and using it. See my comment on the PR here: https://github.com/drwpow/openapi-typescript/pull/1176#issuecomment-1608424912

**Comment by drwpow** [comment]
This is fixed in `openapi-fetch@0.5.0`. If you observe any additional issues, then please open another issue 🙏
