### ISSUE TITLE
All return types from schema are `<type> | undefined`

### ISSUE THREAD

**Issue by dino-rodriguez** [drwpow/openapi-typescript#1201]
All of the return types from my schema are the return type | undefined. 

In my open API compliant API, the return types of the functions are not optional, they are required. How can I make this all return the required types instead of optional types in open API fetch?

e.g. the output type of `data` of a call like this:

```
const { data } = await post('/v1/example_endpoint', {
    body: {}
  });
  ```

is 

```
{ message: string } | undefined
```

**Comment by drwpow** [comment]
It’s `| undefined` because you haven’t checked for the existence of `error` yet. Once you’ve handled `error`, then `data` will always be defined. This is to make sure your error messages are shown to the user / handled properly!
