### ISSUE TITLE
Support null in OpenAPI 3.1 union types

### ISSUE THREAD

**Issue by tyronen** [drwpow/openapi-typescript#1215]
**Description**

OpenAPI 3.1 [dropped support for nullable](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0). Instead, callers are expected to use array types:

```
# OpenAPI v3.0
type: string
nullable: true

# OpenAPI v3.1
type:
- "string"
- "null" 
```

**Reproduction**

For a type like the one above, the generated type is `OneOf<[string, Record<string, never>]>`. 

As far as I can tell, `Record<string, never>` is returned when the tool cannot tell what type it should be generating for.

**Expected result**

The generated type should be `OneOf<[string, null]>`

**Checklist**

- [X] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [X] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Yes `null` is a valid YAML datatype, but not in JSON. It must be the literal string `"null"` as you described.

**Comment by drwpow** [comment]
Your issue was still valid, though. The next release of `6.3.4` will improve the 3.1 nullable handling considerably.
