### ISSUE TITLE
Components that define `$defs` are incorrectly typed as `unknown`

### ISSUE THREAD

**Issue by killjoy1221** [drwpow/openapi-typescript#1261]
**Description**

Json-Schema (thus OpenAPI) support using `$defs` to define reuseable components. I've been able to use this to create something of a namespace, and swagger-ui can read it correctly.

When openapi-typescript reads a component schema with the `$defs` key, it is typed as `unknown`.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.3.3`                      |
| Node.js              | `v18.16.0`                      |
| OS + version         | `Ubuntu 22.04.2 LTS (Jammy Jellyfish)` |

**Reproduction**

Using this openapi spec snippet can reproduce it.

```yaml
openapi: 3.1.0
info:
  title: Test OpenAPI
  version: 0.0.0
servers:
  - url: /
paths:
  /foo:
    get:
      summary: get foo
      security: []
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ns/$defs/Foo'

components:
  schemas:
    ns:
      $defs:
        Foo:
          type: object
          properties:
            bar:
              type: string

```

**Expected result**

```ts
export interface paths {
  "/foo": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ns"]["$defs"]["Foo"]
          };
        };
      };
    };
  };
};
export interface components {
  schemas: {
    ns: {
      $defs: {
        Foo: {
          bar?: string;
        };
      };
    };
  };
};
```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This is a valid bug, and I think openapi-typescript should export types exactly like your proposal. Will just have to double-check prior art to see if `$defs` are allowed anywhere or not.

As a side point, I think it’s also worth examining how much of the JSON Schema spec this library should support. As of now, I don’t think “support transforming literally every JSON Schema to TypeScript” is realistic any time soon. But I think “support any JSON Schema feature used to generate a valid OpenAPI document” is a reasonable expectation of this library.
