### ISSUE TITLE
Generated type of additionalProperties values should not include undefined

### ISSUE THREAD

**Issue by tankers746** [drwpow/openapi-typescript#1267]
**Description**

Reposting this issue https://github.com/drwpow/openapi-typescript/issues/1070

I strongly believe that the library should generate 
```
type Foo = {
    [index: string]: string
}
```

instead of
```
type Foo = {
    [index: string]: string | undefined
}
```

The reasoning given in the issue above refers to the additional safety provided by the undefined, however this safety is now provided by `noUncheckedIndexAccess` mentioned here https://github.com/drwpow/openapi-typescript/issues/1070#issuecomment-1500751490

The current setup makes iteration difficult e.g.
```
const obj: Foo = {};
const values = Object.values(obj); -> string | undefined
```

When in reality, undefined is not present in JSON and therefore that is not accurate.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.4.0`                      |
| Node.js              | `x.x.x`                      |
| OS + version         | `macOS 13, Windows 11, etc.` |

**Reproduction**

_How can this be reproduced / when did the error occur?_

**Expected result**

_(in case it’s not obvious)_

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
See also the discussion in #1018. I agree this change is necessary, and we should reverse the original decision to do this. Would welcome a PR on this!

**Comment by drwpow** [comment]
The new release `v6.5.0` features this change

**Comment by naktinis** [comment]
Possible regression in v7?
