### ISSUE TITLE
How can I split the types into multiple files?

### ISSUE THREAD

**Issue by meftunca** [drwpow/openapi-typescript#1274]
**Description**
How can I split the types into multiple files?

I have a big openapi file and the type output in one file is 4mb. I get "out of memory" error because of this size. I want to create type files related to "RequestId" or "tags", how can I do that?

**Comment by Artemeey** [comment]
I wrote a simple plugin for redocly that split types into multiple files using redocly.yaml.
Maybe it will be useful, more info: https://github.com/topvisor/topvisor-openapi/tree/main/src/redocly-plugins

**Comment by drwpow** [comment]
@Artemeey that’s great, thanks for sharing! Your software doesn’t seem to have a license that lets people use it or use your code (e.g. MIT). But if it had an open license I’d be happy to add it to some recommended plugins section of the docs

**Comment by Artemeey** [comment]
> @Artemeey that’s great, thanks for sharing! Your software doesn’t seem to have a license that lets people use it or use your code (e.g. MIT). But if it had an open license I’d be happy to add it to some recommended plugins section of the docs

The license has been added
