### ISSUE TITLE
Errors caused by default content-type

### ISSUE THREAD

**Issue by HHongSeungWoo** [drwpow/openapi-typescript#1298]
https://github.com/drwpow/openapi-typescript/blob/ad894a5697f852709c745c22e974991b9b8b4925/packages/openapi-fetch/src/index.ts#L3C8-L3C8

If the request headers has content-type and the body is empty, Fastify does not process the request and returns an error.
Is there a reason to set content-type: application/json as the default headers?

**Comment by drwpow** [comment]
I thought that all JSON APIs expected `"Content-Type": "application/json"`? This is the first I’ve heard of it causing issues.

But you do have a good point which is it’s impossible to unset default headers in the client. While I think `"Content-Type": "application/json"` is a good default, you should still be able to unset that if desired.

**Comment by drwpow** [comment]
Starting in `0.7.4` you can unset the default headers with:

```ts
createClient({ headers: { "content-type": null } })
```

_Note: `undefined` will just be ignored; `null` is required to unset_
