### ISSUE TITLE
A recent change in the release process breaks importing into typical typescript projects

### ISSUE THREAD

**Issue by ianwremmel** [drwpow/openapi-typescript#1306]
**Description**

Somewhere between `6.4.0` and `6.5.0`, `openapi-typescript`'s internal types changed and the package can no longer be imported by projects that use `"moduleResolution": "node"`. I've been trying to switch to `"moduleResolution": "nodenext"`, but it's probably too strict to use for several years.

```
node_modules/openapi-typescript/dist/types.d.ts:1:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

1 /// <reference types="node" resolution-mode="require"/>
                        ~~~~

node_modules/openapi-typescript/dist/index.d.ts:1:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

1 /// <reference types="node" resolution-mode="require"/>
                        ~~~~

node_modules/openapi-typescript/dist/index.d.ts:2:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

2 /// <reference types="node" resolution-mode="require"/>
                        ~~~~

```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.5.0`                      |
| `typescript` | `5.1.6`                      |
| Node.js              | `18.17.0`                      |
| OS + version         | `macOS 13, Windows 11, etc.` |

**Reproduction**

_How can this be reproduced / when did the error occur?_

Install 6.5 or later, change `moduleResolution` to `nodenext` in `tsconfig.json`, and `import from 'openapi-typescript'` somewhere in your project.

**Expected result**

No errors from inside node_modules.

**Checklist**

- [x] ~My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)~ Not Applicable
- [x] ~I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))~ The URL is not found

**Comment by drwpow** [comment]
So `6.4.0` shipped the CJS bundle (https://github.com/drwpow/openapi-typescript/pull/1263), but you’re saying `6.4.0` works, but not `6.5.0`?

Agree `moduleResolution: "NodeNext"` shouldn’t be a requirement to use this package. It’s not realistically possible for most apps today.

**Comment by drwpow** [comment]
> the typescript folks seem to be formalizing a `types` key in `exports`

🤦 Oh shoot that should be there. That’s just an oversight. You’re right probably not the central issue here, but that’s a quick-and-easy fix regardless.

**Comment by ianwremmel** [comment]
Sorry, I just realized it's not a recent change. A recent change broke the local patch that I have to address the issue 🤦‍♂️. I originally patched locally against 6.3.9, so the issue is at least that old.

**Comment by drwpow** [comment]
Ah OK that makes more sense! `6.4.0` was my initial suspect and it seems that is probably where the breakage happened. Will start investigating there.

**Comment by ianwremmel** [comment]
I'm confident I originally ran into this with 6.3.9, based on this patchfile I found :) 
<img width="965" alt="Screenshot 2023-08-18 at 12 24 55 PM" src="https://github.com/drwpow/openapi-typescript/assets/1182361/d741007d-5ae4-44c0-b6fb-bcc8e8c295ff">

**Comment by ianwremmel** [comment]
I bet it's [this commit](https://github.com/drwpow/openapi-typescript/commit/1d8e76a5290116663c78a72762a0a9a9d6b1fb6a) which switch tsconfig to use `NodeNext`

**Comment by drwpow** [comment]
Sorry this took a little bit to dig into further. Just reverted this behavior; next patch version will restore the `.d.ts` files back to what they were. This entire rabbithole is such an opaque, confusing behavior of TypeScript 🙃
