### ISSUE TITLE
Cannot find name 'OperationObject'

### ISSUE THREAD

**Issue by peterkelly** [drwpow/openapi-typescript#1322]
**Description**

When attempting to use the `openapi-fetch` library, it imports `openapi-typescript-helpers`, which tries to use the `OperationObject` type declaration which is not in scope. It seems to be missing an import of this type.

**Reproduction**

```
$ npx tsc
node_modules/openapi-typescript-helpers/index.d.ts:19:51 - error TS2304: Cannot find name 'OperationObject'.

19 export type PathItemObject = { [M in HttpMethod]: OperationObject } & { parameters?: any };
                                                     ~~~~~~~~~~~~~~~


Found 1 error in node_modules/openapi-typescript-helpers/index.d.ts:19

$ cat src/index.ts 
import createClient from "openapi-fetch";
import { paths } from "./api"; // (generated from openapi-typescript)

async function main() {
    const { GET } = createClient<paths>({ baseUrl: "http://127.0.0.1:8000" });
    const { data, error } = await GET("/user", {});
    console.log(data);
}

main();

$ cat tsconfig.json 
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "outDir": "dist",
    "lib": [
        "es2017",
        "dom"
    ]
  }
}
```

Versions

- node: v20.5.1
- typescript: 5.2.2
- openapi-fetch: 0.7.4
- openapi-typescript-helpers: 0.0.1
- openapi-typescript: 6.5.3

**Expected result**

No compilation errors

**Checklist**

- [X] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Ah thank you for filing a bug! This was an error in the TypeScript setup for that package. It’s been fixed; will push a new openapi-fetch version in a bit.
