### ISSUE TITLE
Missing double quote in the "responses" section

### ISSUE THREAD

**Issue by ghostd** [drwpow/openapi-typescript#1323]
**Description**

The Typescript generated code is broken, a double quote (`"`) is missing in the "responses" section.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.5.3`                      |
| Node.js              | `18.15.0`                      |

**Reproduction**

Swagger:
```yaml
openapi: 3.0.3
info:
  title: Sample
  version: 0.0.1
paths:
  /ping:
    get:
      responses:
        400:
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: "string"
  responses:
    ErrorResponse:
      $ref: '#/components/schemas/GeneralError'
```

Generated code:
```
export interface paths {
  "/ping": {
    get: {
      responses: {
        400: components["responses"]["ErrorResponse"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    GeneralError: {
      code?: string;
    };
  };
  responses: {
    ErrorResponse": components["schemas"]["GeneralError"]; // <-- the line should start with double quote
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;
export type external = Record<string, never>;
export type operations = Record<string, never>;
```

**Expected result**

Expected code:
```
  responses: {
    "ErrorResponse": components["schemas"]["GeneralError"]; // <-- the line should start with double quote
  };
```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Thank you for the reproduction! This was literally just a double quote accidentally inserted into the string template for `#/components/responses` with a `$ref` and nowhere else. And it seems we didn’t have an existing test case for this scenario, nor did any of our gigantic test schemas have this specific combination. Really weird (but minor) bug!

Will push a release in a minute
