### ISSUE TITLE
Collection query parameter placeholders are replaced by comma separated list instead of multiple parameters

### ISSUE THREAD

**Issue by andrius-kurtinaitis** [drwpow/openapi-typescript#1331]
**Description**

A query parameter, which has a collection type (array) is being replaced by the http client by comma separated values, instead of using multiple parameters, which is a generally accepted convention for passing multi valued parameters.

**Reproduction**

This is the java (jax-rs) interface, which is used for generation of openapi:
```
	@GET
	public List<Dto> get(
			@QueryParam("siteId") List<Integer> siteIds
	) {
		return service.get(siteIds);
	}
```
The openapi json spec I get from it is:
```
 "/path": {
      "get" : {
        "parameters" : [ {
          "name" : "siteId",
          "in" : "query",
          "required" : true,
          "schema" : {
            "type" : "array",
            "items" : {
              "format" : "int32",
              "type" : "integer"
            }
          }
        } ],
```
Then, TS type generated by openapi-typescript:
```
 "/path": {
    get: {
      parameters: {
        query: {
          siteId: (number)[];
        };
      };
```
When I call the client generated by openapi-fetch
```
httpGet('/path', { params: { query: { siteId: [1, 2, 3] } } })
```
The following URL gets called:
`http://localhost:3000/path?siteId=1%2C2%2C3`
The parameter `siteId` then is not parsed by jax-rs to list of integers.

**Expected result**

I expect the following URL to be formed:
`http://localhost:3000/path?siteId=1&siteId=2&siteId=3`

**Comment by drwpow** [comment]
This is currently working as-intended. From [the docs](https://openapi-ts.pages.dev/openapi-fetch/api/#queryserializer):

> This library uses [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) to [serialize query parameters](https://swagger.io/docs/specification/serialization/). For complex query param types (e.g. arrays) you’ll need to provide your own querySerializer() method that transforms query params into a URL-safe string:
>
> ```ts
>const { data, error } = await GET("/search", {
>  params: {
>    query: { tags: ["food", "california", "healthy"] },
>  },
>  querySerializer(q) {
>    let s = "";
>    for (const [k, v] of Object.entries(q)) {
>      if (Array.isArray(v)) {
>        s += `${k}[]=${v.join(",")}`;
>      } else {
>        s += `${k}=${v}`;
>      }
>    }
>    return s; // ?tags[]=food&tags[]=california&tags[]=healthy
>  },
>});
>```

You may have decided your server wants `siteId=1&siteId=2&siteId=3` but someone else may need `siteId[]=1&siteId[]=2&siteId[]=3`, while another may want `siteId=1,2,3` (current behavior). There’s no standard way to serialize params. Even the [Swagger docs list 6 ways of doing it](https://swagger.io/docs/specification/serialization/) and that’s probably not comprehensive.

If you (or anyone reading this) can provide a good argument for one of the serialization methods being far more common than the others, I’d be open to providing better defaults for array types.

**Comment by andrius-kurtinaitis** [comment]
Thanks for clarification. I thought `siteId=1&siteId=2&siteId=3` is almost universally accepted way to do it.

**Comment by andrius-kurtinaitis** [comment]
Although Swagger has this as a its default.

**Comment by drwpow** [comment]
I’ll reopen the issue to track changing the default. I’d be open to anybody opening a PR for this
