### ISSUE TITLE
Dead link in README and issue template

### ISSUE THREAD

**Issue by ostatni5** [drwpow/openapi-typescript#1358]
**Description**
Dead link in README: [swap for any call](https://github.com/drwpow/openapi-typescript/blob/main/openapi-fetch/api#create-client)
https://github.com/drwpow/openapi-typescript/blob/b97311e0bbbe4dcc866a6c6fdaa7a05a6db0f917/packages/openapi-fetch/README.md?plain=1#L39

Also link in checklist is dead https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md

**Expected result**

Links should point to meaningful resources.

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This looks like just an accidental copy from the docs that links to relative resources. This would be a great easy PR for a first-time contributor to tackle!
