### ISSUE TITLE
Custom fetch support per call

### ISSUE THREAD

**Issue by HugeLetters** [drwpow/openapi-typescript#1369]
**Description**

SvelteKit provides a custom fetch function for loaders(which provide data for components) with a bunch of QoL improvements - this fetch functions are specific to each call so they can't be provided on `createClient` call. Would be nice to have an option to provide custom fetch function per specific openapi-fetch call.

**Proposal**

Extent FetchOptions type with a fetch parameter akin to ClientOptions - default to createClient specified fetch if not provided.

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
I’m open to this, and I think this should be relatively straightforward to implement—maybe just add the same `fetch` option to `FetchOptions` as well?
