### ISSUE TITLE
Schema Type `object` results in `Record<string, never>`

### ISSUE THREAD

**Issue by hbroer** [drwpow/openapi-typescript#1390]
**Description**

We consume a API which has a parameter which is loosly defined as object

```json
"/path/to/endpoint": {
   "get": {
     "operationId": "getSomething",
     "parameters": [
       {
         "name": "params",
         "in": "query",
         "style": "form",
         "explode": true,
         "schema": { "type": "object" },
         "example": {
           "one": "something",
            "two": "something",
          }
       }
    ]
}
```

this results in 

```
    getSomething: {
        parameters: {
            query?: {
                params?: Record<string, never>;
            };
```

I would expect the type to be `Record<string, string>`, because an empty object does not make much sense.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.7.0`                      |

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by wolfy1339** [comment]
The package is encouraging people to properly define the object, even when it's empty to avoid ambiguity.

You have to use the `additionalProperties` key

**Comment by hbroer** [comment]
I just want to note it, we define the property types by ourself to fix it and we use now only the schema definition for the responses. It is all over the place at that API. But in general it is very unlikely that an object needs to be empty ;-). We are only the consumer of the API and it will not happen in time that they will fix it just for us.

**Comment by drwpow** [comment]
Yes as @wolfy1339 stated, we encourage being specific in your schema ([docs](https://openapi-ts.pages.dev/advanced/#be-specific-in-your-schema)). It’s not that we realistically expect your schema to consist of empty objects; it’s that now you are keenly aware of an untyped parameter in your schema that you’ll need to provide typing overrides for. And that’s the goal.

If we provided a `Record<string, string>` by default you would likely have a typing error and this library would be to blame.

**Comment by hbroer** [comment]
> in your schema that you’ll need to provide typing overrides for. And that’s the goal.

We are the consumer, not our schema definition, nothing we can do ;-)
