### ISSUE TITLE
defaultQuerySerializer does not handle empty array correctly

### ISSUE THREAD

**Issue by stefanprobst** [drwpow/openapi-typescript#1403]
**Description**

the default query serializer (v0.8.0) seems to not handle empty arrays correctly.

**Reproduction**

```ts
import { defaultQuerySerializer } from "openapi-fetch";

console.log(
  defaultQuerySerializer({
    q: "term",
    categories: [],
    search: [],
    limit: 10,
    offset: 0,
  })
);

// logs:
// q=term&&&limit=10&offset=0
//       ^^^
```

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Thanks for filing. What would be expected behavior here? Would it be specifying the key but set to nothing?

**Comment by stefanprobst** [comment]
i think i'd expect an empty array to match the behavior for `null` and `undefined` (which currently is to skip the param)
