### ISSUE TITLE
Empty Openapi Type being misinterpreted as Record<string, unknown> when nullable

### ISSUE THREAD

**Issue by frednomoon** [drwpow/openapi-typescript#1407]
I found that when a field has no type information, but `nullable: true`, the resulting Typescript is `Record<string, unknown> | null`. 

I was originally thinking I may need to justify _why_ this is wrong but after some testing I found that this case is actually handled correctly for `nullable: false` - the output is simply `unknown`. I would suggest that the nullable version of this should be `unknown | null`.

** Versions **
Using `openapi-typescript@6.5.0`

**Reproduction**

I tried to simplify the Yaml as much as possible for repro:
```
openapi: 3.0.0
info:
  title: example
  version: 0.1.0

paths:
  /my_route:
    get:
      responses:
        "200":
          description: "Description"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Test"

components:
  schemas:
    Test:
      type: object
      properties:
        nullable_unknown_field:
          nullable: true

```

**Expected result**

As I said above, the result for this ends up as 
```
nullable_unknown_field?: Record<string, unknown> | null;
```
However, it seems like this should actually be:
```
nullable_unknown_field?: unknown | null;
```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`) - yes
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md)) - potentially 😅

**Comment by drwpow** [comment]
Yup this seems like a bug. Would love a PR if you’re able to provide one. Specifically, writing a failing test in [schema-object.test.ts](https://github.com/drwpow/openapi-typescript/blob/6.x/packages/openapi-typescript/test/schema-object.test.ts) first and then getting it to pass is probably the best approach.

When you open a PR, **base this against the `6.x` branch** as `main` is currently the beta v7. I can copy the changes upstream there.
