### ISSUE TITLE
openapi-fetch sends `Content-Type: application/json` header on GET requests

### ISSUE THREAD

**Issue by kmoschcau** [drwpow/openapi-typescript#1410]
**Description**

When sending GET requests with openapi-fetch, a `Content-Type: application/json` header is always included, even though GET requests should not have a body.

This causes problems in my case when talking to an ASP.NET API, which (nonsensically) tries to parse the non-existent GET body as JSON with the header present, fails, and then returns a 400. When the header is omitted or set to `text/plain`, everything works fine.

**Reproduction**

Generate a client schema from a Swagger JSON with a GET request. Then use said get request and observe that a `Content-Type: application/json` header is sent.

**Expected result**

The header should not be included.

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow** [comment]
I believe this is recommended behavior for most APIs. To unset this, you can set `"Content-Type": null` on `createClient()` to not set any headers.

Let me know if this doesn’t work as expected (I’ll add a test for this later this week—just noticed that behavior isn’t enforced/tested)

**Comment by kmoschcau** [comment]
I'll try it next Wednesday.

**Comment by kmoschcau** [comment]
Yes setting `null` on that header in createClient works. For my case I will just stick to the `text/plain` method, as I have way fewer GET requests than others. Thanks for the hint.
