### ISSUE TITLE
Where to put transform code?

### ISSUE THREAD

**Issue by Lucianod28** [drwpow/openapi-typescript#1418]
Very basic question here but I read the docs and can't seem to figure it out. I'm currently using the CLI to generate a schema.d.ts file, and now I want to add the transform shown in the [docs](https://openapi-ts.pages.dev/node/):
```typescript
import openapiTS from "openapi-typescript";
import ts from "typescript";

const BLOB = ts.factory.createIdentifier("Blob"); // `Blob`
const NULL = ts.factory.createLiteralTypeNode(ts.factory.createNull()); // `null`

const ast = await openapiTS(mySchema, {
  transform(schemaObject, metadata) {
    if (schemaObject.format === "binary") {
      return schemaObject.nullable
        ? ts.factory.createUnionTypeNode([BLOB, NULL])
        : BLOB;
    }
  },
});
```
Where does this code go? I want it to modify my schema when I generate it with the CLI. Thanks!

**Comment by drwpow** [comment]
No worries!

Transform is only available via the Node API. So you’d write a script in a `.js` file to do everything you want, and then run `node path/to/my/script.js` to execute it.

Note that when using the Node.js API you’ll have to write the file to disk yourself, but there’s [some example code in the basic usage section](https://openapi-ts.pages.dev/node/#usage)

**Comment by Lucianod28** [comment]
Ah that makes sense, thanks!
