### ISSUE TITLE
v6: dependency `undici` needs update for CVE

### ISSUE THREAD

**Issue by psychedelicious** [drwpow/openapi-typescript#1433]
**Description**

The `undici` dependency has a CVE: https://github.com/advisories/GHSA-wqq4-5wpv-mx2g

Updating the package to >=5.26.2 will bring in the fix.

It appears that in v7, this is no longer a dependency (sweet!). Can we get a v6 bump?

**Proposal**

Update the dependency to latest

**Checklist**

- [ ] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by psychedelicious** [comment]
Hmm, it looks like the `openapi-typescript@6.7.0` tag has `"undici": "^5.23.0",`, but the `6.x` branch has `"undici": "^5.26.4",`. I guess it just needs a release?

Unticking "I'm willing to open a PR" bc I believe none is needed at this point?

**Comment by drwpow** [comment]
I can release a patch version just to make it easier / resolve some lockfile issues some people may have.

**Comment by psychedelicious** [comment]
Sounds good. It's easy enough to just reinstall `openapi-typescript`, which gets the updated version of the dependency installed, but nice to not have to. Thanks!

**Comment by drwpow** [comment]
Published a patch version that just bumps `undici`.

In 7.x fetching is just done via [Redocly CLI](https://github.com/Redocly/redocly-cli) that just uses `node-fetch`, which is unexpectedly now better to use than `undici` (now that undici is just part of Node core)
