### ISSUE TITLE
Garbled characters when enum value is set to Japanese in v7

### ISSUE THREAD

**Issue by yossydev** [drwpow/openapi-typescript#1436]
**Description**
When generating with v7, if Japanese is used in enum, it causes garbled characters.

```ts
export enum ClientName {
    _ = "\u30C6\u30B9\u30C8",
    _2 = "\u30C6\u30B9\u30C82"
}
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.0-next.2`               |
| Node.js              | `20.9.0`                     |
| OS + version         | `macOS 14.1.1`               |

**Reproduction**

Reproduction repository: https://github.com/yossydev/openapi-typescript-bug-repo

**Expected result**

I would like Japanese text to be returned in Japanese as it is.

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I'm willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This seems to be an issue with the TS compiler itself :( https://github.com/microsoft/TypeScript/issues/36174

**Comment by drwpow** [comment]
Give the latest `@next` release a try; should hopefully be fixed 🙏

**Comment by yossydev** [comment]
> Give the latest `@next` release a try; should hopefully be fixed 🙏

Thank you for your response! We appreciate it!
