### ISSUE TITLE
RFC: BigInt support

### ISSUE THREAD

**Issue by rand0m-cloud** [drwpow/openapi-typescript#1439]
**Description**
In the OpenAPI spec for [qdrant](https://github.com/qdrant/qdrant), we have this definition for an ID:
```json
{
  "ExtendedPointId": {
    "description": "Type, used for specifying point ID in user interface",
    "anyOf": [
      {
        "type": "integer",
        "format": "uint64",
        "minimum": 0
      },
      {
        "type": "string",
        "format": "uuid"
      }
    ]
  }
}
```
This is causing issues in the JS REST client when the backend sends back a large number for an ID that is lost when converted to JS's number. I'm not sure how best to solve this issue because it feels like a breaking change. Currently, a `number` field is generated for `number` and `integer` fields in the OpenAPI spec. 

**Proposal**
Generate a `BigInt` field when parsing a `integer` field in the OpenAPI spec.

**Comment by marcomuser** [comment]
I think you could use the transform option to generate BigInts for integers. See: https://github.com/drwpow/openapi-typescript/blob/main/docs/src/content/docs/v6/node.md#transform--posttransform

**Comment by drwpow** [comment]
Closed this issue because this is outside the scope of this library, however, I definitely think this should:

1. Be added to the docs examples (because others may have this problem)
2. Figure out a good solution for openapi-fetch to use this since it does have a runtime component
