### ISSUE TITLE
it seems that --default-non-nullable is not working

### ISSUE THREAD

**Issue by alissawix** [drwpow/openapi-typescript#1451]
**Description**
it seems that --default-non-nullable is not working or I'm missing something..

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.7.1`                      |
| Node.js              | `20.9.0`                      |
| OS + version         | `Windows 11` |

**Reproduction**

I tried to run `npx openapi-typescript ./full_documentation.json -o ./generated-api-types.ts --default-non-nullable`
and all my properties are optional

some json part:
```
"Todo": {
        "type": "object",
        "properties": {
          "Title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "isDone": {
            "type": "boolean"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          },
          "publishedAt": {
            "type": "string",
            "format": "date-time"
          }
}}
```

and the resulting type is: 
```
Todo: {
      Title?: string;
      description?: string;
      isDone?: boolean;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      /** Format: date-time */
      publishedAt?: string;
}
```

**Expected result**

the properties not to be optional:
```
Todo: {
      Title: string;
      description: string;
      isDone: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: date-time */
      publishedAt: string;
}
```

**Checklist**

- [ ] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
From the docs (emphasis added):

> `--default-non-nullable`: Treat schema objects with **default values** as non-nullable

This is referring to schema objects that explicitly declare a `"default": "[foo]"` value, even if they are not in the `"required": []` array.

The only way to have your properties not be optional is by explicitly marking them as required:

```json5
{
  "Todo": {
    "type": "object",
    "required": ["Title", "description", "isDone", "createdAt", "updatedAt", "publishedAt"],
    // …
}
```

There’s intentionally not an option to change this behavior, because OpenAPI (and JSONSchema) have always operated this way. And configuring openapi-typescript to interpret the same schema differently would lead to many more unexpected side-effects.

Hopefully that answers your question! But feel free to ask any followups if needed!
