### ISSUE TITLE
post data with FormData doesnt wok

### ISSUE THREAD

**Issue by wusaby-rush** [drwpow/openapi-typescript#1472]
**Description**

when send data as formData it sent empty and as json payload not `multi-pat/formdata` 

**Reproduction**

```js
const payload = new formData()
// append here

client.POST('/url', {
  body: payload
})
```

**Expected result**

it should sent successfully as in browser fetch 

```js
const payload = new formData()
// append here

fetch('/url', {
  method: 'POST',
  body: payload
})
```

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Going to close this issue as I don’t see a way to automatically infer TS types from `FormData()`, but can reopen if there’s a proposal that can accomplish this behavior while correctly typechecking the requestbody
