### ISSUE TITLE
openapi-typescript@7.0.0-next.5 require('openapi-typescript') cannot export the astToString method

### ISSUE THREAD

**Issue by liangskyli** [drwpow/openapi-typescript#1482]
**Description**

openapi-typescript@7.0.0-next.5 bug:
require('openapi-typescript') cannot export the astToString method
for example: var { astToString } = require('openapi-typescript');

```
Paste full error message
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.0-next.5 bug`                      |
| Node.js              | `18`                      |
| OS + version         | `Windows 10` |

**Reproduction**

require('openapi-typescript') cannot export the astToString method
for example: var { astToString } = require('openapi-typescript');

**Expected result**

require('openapi-typescript') can export the astToString method
for example: var { astToString } = require('openapi-typescript');

**Checklist**

- [ ] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
It’s recommended to use the ESM (`import`) version of the library rather than deprecated CommonJS (`require`). Mostly because the library itself is written in ESM. And the CommonJS version is exported via [esbuild](https://esbuild.github.io/), and is in an “as-is” state.

That said, I think the following workaround is possible?

```ts
const { astToString } = require('openapi-typescript').default;
```

But also, if there are any [esbuild settings](https://esbuild.github.io/) that would achieve the desired end result, we’re open to improving this.

**Comment by liangskyli** [comment]
```
const { astToString } = require('openapi-typescript').default;
```
use this alse no work!
<img width="844" alt="image" src="https://github.com/drwpow/openapi-typescript/assets/31531283/c99f8ca1-5c63-4c79-af99-fb2a6419e36f">

**Comment by liangskyli** [comment]
I think there should be an issue with the CJS package

**Comment by Colmea** [comment]
Hi,
Sorry to comment on a closed issue, but I'm still not able to `import { astToString}` from any release (I use the ESM "import").
I tried: next, latest, 6.7.4, 6.6.2, ...

`Module '"openapi-typescript"' has no exported member 'astToString'. Did you mean to use 'import astToString from "openapi-typescript"' instead?ts(2614)`

Should I open a separate issue ? Or could you point me to a release that includes this astTostring ?

Thank's for your work !

**Comment by liangskyli** [comment]
> Hi, Sorry to comment on a closed issue, but I'm still not able to `import { astToString}` from any release (I use the ESM "import"). I tried: next, latest, 6.7.4, 6.6.2, ...
> 
> `Module '"openapi-typescript"' has no exported member 'astToString'. Did you mean to use 'import astToString from "openapi-typescript"' instead?ts(2614)`
> 
> Should I open a separate issue ? Or could you point me to a release that includes this astTostring ?
> 
> Thank's for your work !

you can use openapi-typescript@7.0.0-next.7, this bug is only fix cjs require bug.  ESM "import" is fine in V7.
