### ISSUE TITLE
typescript-fetch: dynamic fetch url

### ISSUE THREAD

**Issue by FreeAoi** [drwpow/openapi-typescript#1493]
**Description**

Add the possibility of passing a url different from the one described in createClient when making a request because there is some API's that have url's based on some user property or another reason (like RiotGames API which url is based on region but the data type is the same) so in that way instead of creating a client for each different url variation we can pass a differente url

**Proposal**

```ts
// asumming example of RiotGames API
const client = createClient<paths>({
    headers: {
        "X-Riot-Token": "somekey"
    }
});

client.GET("/some-api-url", {
    overwriteBaseURL: "https://americas.api.riotgames.com" 
});

client.GET("/some-api-url", {
    overwriteBaseURL: "https://asia.api.riotgames.com" 
});
```

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This is possible with [middleware now](https://openapi-ts.pages.dev/openapi-fetch/middleware-auth)! But be warned that you may not get the proper type safety when you’re rearranging the runtime.
