### ISSUE TITLE
FreeForm Object is generated as empty object

### ISSUE THREAD

**Issue by holomekc** [drwpow/openapi-typescript#1495]
**Description**

When a property is defined as a so called [FreeForm object](https://swagger.io/docs/specification/data-models/data-types/#free-form) in the shortest form:
```yaml
  properties:
    something:
      type: object
```
The generated code uses:
```typescript
Record<string, never>
```
Which basically means that it is an empty object.

**Reproduction**

As mentioned above

**Expected result**

A FreeForm object allows to set any additionalProperties as mentioned in the specification.

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This is intended behavior. Please see [the docs](https://openapi-ts.pages.dev/advanced#be-specific-in-your-schema) for more explanation.
