### ISSUE TITLE
Types missing for parameters with duplicate names but different locations

### ISSUE THREAD

**Issue by JohannCooper** [drwpow/openapi-typescript#1498]
**Description**

If an operation contains two parameters with the same `name` but different locations (`in`), types will only be generated for one of the parameters. According the OpenAPI Specification v3.0.3, "a unique parameter is defined by a combination of a name and location" ([source](https://spec.openapis.org/oas/v3.0.3#parameter-object)).

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.7.3`                      |
| Node.js              | `18.16.1`                      |
| OS + version         | `Ubuntu 23.10` |

**Reproduction**

Using the schema below, you will see that a parameter type is only generated for the parameter with `in: path`.

```yml
openapi: 3.1.0
info:
  title: Sample API
  version: 0.1.9
  license:
    {
      "name": "Sample License",
      "identifier": "Sample-License",
      "url": "https://license.foobar.com",
    }
servers:
  - url: http://api.foobar.com/v1
paths:
  /users/{userId}:
    get:
      security:
        - {}
      operationId: retrieveUser
      summary: Returns a user by ID.
      parameters:
        - name: userId
          in: query
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200":
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  name:
                    type: string
                    example: Jessica Smith
        "400":
          description: The specified user ID is invalid (not a number).
        "404":
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

```

**Expected result**

A type is generated for BOTH parameters, despite their non-unique names.

**Checklist**

- [X] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [X] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Fixed and released in `6.7.4`!
