### ISSUE TITLE
The 'styleguide' field is deprecated warning printed to console on every call to openapiTS()

### ISSUE THREAD

**Issue by rzyns** [drwpow/openapi-typescript#1499]
**Description**

When using `openapi-typescript` programmatically, with each call to the `openapiTS()` function (default export), the following warning is printed to the console:

```
The 'styleguide' field is deprecated. Read more about this change: https://redocly.com/docs/api-registry/guides/migration-guide-config-file/#changed-properties
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.0.next-5`                      |
| Node.js              | `18.17.1`                      |
| OS + version         | `MacOS 14.2.1` |

**Reproduction**

Call the `openapiTS()` function 

**Expected result**

No warning about deprecated redocly config properties is written to the console

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Thanks for raising. This is a known bug for now, at least until Redocly updates types. This will be resolved before the first release candidate.

**Comment by drwpow** [comment]
Fixed! Removed in the latest `@next` package, which updates the Redocly internal dep.
