### ISSUE TITLE
Reduce the size of the package (v7)

### ISSUE THREAD

**Issue by kazuma1989** [drwpow/openapi-typescript#1501]
**Description**

I would like to reduce the size of the package. (v7)

Currently, the package install size is 38 MB, but reducing it should improve the speed of `npx` and `npm install` on CI.
cf. https://packagephobia.com/result?p=openapi-typescript@7.0.0-next.5

Of the 38 MB, 30 MB is the `typescript` package and 7 MB is the `@redocly/openapi-core` package.
cf. https://packagephobia.com/result?p=%40redocly%2Fopenapi-core%2C+typescript

The `typescript` package is probably in peer if you use openapi-typescript, so there is no need to have it in **dependencies**.
The `@redocly/openapi-core` package may possibly be a core feature of openapi typescript, but if it is not, but is a package that does remote schema acquisition and validation, it is fine to have it in peer.

**Proposal**

Move dependencies on `typescript` from dependencies to peerDependencies.
In addition, if possible, move dependencies on `@redocly/openapi-core` from dependencies to peerDependencies as well.

If you want to use the all-in-one openapi-typescript, you can install the whole package including the peers, or if you only want schema-to-type conversion functionality or if you want fine-grained control, you can install only the lightweight openapi-typescript.

**Checklist**

- [ ] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

Sorry, but no. I'm not familiar with `@redocly/openapi-core`. 😢

**Comment by wolfy1339** [comment]
Typescript is used for it's AST, in this case it is a production dependency.

The package uses `@redocly/openapi-core` for parsing schemas, and validation, and some other things.

See the v7 release notes: https://github.com/drwpow/openapi-typescript/issues/1368#issue-1929252332

**Comment by drwpow** [comment]
I’m not opposed to making both deps peerDeps. It’s a safe assumption every consumer will have typescript as you said. Redocly could remain as a dep, but also people may find they want to use some features of this tool outside of openapi-typescript at which point it should be an explicit dep. So it’s not a huge ask.

**Comment by drwpow** [comment]
Update: the next `@next` package will move `typescript` to peerDeps, but I’m going to keep `@redocly/openapi-core` in deps for now. Reason is that’s more of an internal package that people probably won’t consume directly. If we end up needing the CLI, that should be a peerDep. But `@redocly/openapi-core` is fairly lightweight, all things considered.
