### ISSUE TITLE
Change client headers

### ISSUE THREAD

**Issue by ws-rush** [drwpow/openapi-typescript#1503]
**Description**

Change client headers after initiate it

**Proposal**

provide ability to change headers like `client.headers['Authorization'] = `ApiToken ${token}``

**Comment by drwpow** [comment]
I don’t see why we couldn’t add this. This would probably require a minor API change (`createClient()` → `new FetchClient()`), but could allow for more utility such as this without any additional footprint.

**Comment by ws-rush** [comment]
Thanks for your response, I solved this easily with middlware
