### ISSUE TITLE
Converts anyOf: type: object to Record<string, never>

### ISSUE THREAD

**Issue by PythonCoderAS** [drwpow/openapi-typescript#1514]
**Description**

If I have a component with a field where it has `{"anyOf": [{ "type": "object" }, {"type": "null"}]}`, the resulting output is `Record<string, never> | null`.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.7.4`                      |
| Node.js              | `v21.6.0`                      |
| OS + version         | `macOS 14` |

**Reproduction**

openapi.json:

```json
{
  "paths": {
    "/sample": {
      "requestBody": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SampleBody"
            }
          }
        },
        "required": true
      }
    }
  },
  "components": {
    "schemas": {
      "SampleBody": {
        "properties": {
          "sampleField": {
            "anyOf": [
              {
                "type": "object"
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    }
  }
}
```

Generated:

```ts
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/sample": {
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SampleBody: {
      sampleField?: Record<string, never> | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
```

**Expected result**

I wanted a `Record<string, any>`.

**Checklist**

- [ ] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
That’s correct. A `{ "type": "object" }` has no properties (`Record<string, never>`), and you didn’t declare `additionalProperties` explicitly. And the `| null` is correct. See [the docs on this behavior](https://openapi-ts.pages.dev/advanced#be-specific-in-your-schema).

openapi-typescript will never generate a `any` type because that’s basically not typechecking at all. In order to achieve that behavior, you’ll have to either make your OpenAPI schema more explicit (recommended), or override the type with the desired type (i.e. OpenAPI schema didn’t declare a descriptive type, therefore openapi-typescript couldn’t, so I’ll have to override it manually in TypeScript).

**Comment by PythonCoderAS** [comment]
> That’s correct. A `{ "type": "object" }` has no properties (`Record<string, never>`), and you didn’t declare `additionalProperties` explicitly. And the `| null` is correct. See [the docs on this behavior](https://openapi-ts.pages.dev/advanced#be-specific-in-your-schema).
> 
> openapi-typescript will never generate a `any` type because that’s basically not typechecking at all. In order to achieve that behavior, you’ll have to either make your OpenAPI schema more explicit (recommended), or override the type with the desired type (i.e. OpenAPI schema didn’t declare a descriptive type, therefore openapi-typescript couldn’t, so I’ll have to override it manually in TypeScript).

What if it's intended that I can send something with whatever keys and values I want to the backend (for example, it's an extra field that's saved to the DB as a JSON type)? Is there a good way to represent that the type of the record doesn't matter?

**Comment by drwpow** [comment]
Yes! That’s `additionalProperties`. You can give that a type, and be as descriptive as possible. It will let any arbitrary keys return the provided shape.

You can also set `additionalProperties: true` to generate `Record<string, unknown>`, but it’s always best to just pass a full Schema Object to additionalProperties (`$ref`s work too)

**Comment by lrenn** [comment]
>That’s correct. A { "type": "object" } has no properties (Record<string, never>), and you didn’t declare additionalProperties explicitly. And the | null is correct. See [the docs on this behavior](https://openapi-ts.pages.dev/advanced#be-specific-in-your-schema).

> openapi-typescript will never generate a any type because that’s basically not typechecking at all. In order to achieve that behavior, you’ll have to either make your OpenAPI schema more explicit (recommended), or override the type with the desired type (i.e. OpenAPI schema didn’t declare a descriptive type, therefore openapi-typescript couldn’t, so I’ll have to override it manually in TypeScript).

But this doesn't follow the spec.  The spec says that `additionalProperties` defaults to true, but the code doesn't generate that way.  I get that people have strong opinions about `any`, but it should follow the spec no?  At least an option to overwrite the default value?

> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#schemaObject) and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties defaults to true.

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md
