### ISSUE TITLE
`--exclude-deprecated` flag is not applied to query and path

### ISSUE THREAD

**Issue by smaspe** [drwpow/openapi-typescript#1532]
**Description**

`--exclude-deprecated` flag is not applied to query and path.

No error message, but the deprecated fields are not excluded

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.7.4`                      |
| Node.js              | `21.5.0`                     |
| OS + version         | `macOS 14.2.1`               |

**Reproduction**

Considering the following bit of openapi yaml:

```yaml
openapi: 3.0.3
info:
  title: "Some API"
  version: "1"
components:
  schemas: {}
paths:
  "some_path":
    get:
      parameters:
        - schema:
            type: string
          deprecated: true
          in: query
          name: id
```

Result

```ts
export type paths = {
  "some_path": {
    get: {
      parameters: {
        query?: {
          /** @deprecated */
          id?: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
};
```

**Expected result**

```ts
export type paths = {
  "some_path": {
    get: {
      parameters: {
        query?: {
        };
      };
      responses: {
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
};

```

Notice that the `id` field, which is in the `query` object, is expected to be excluded (I also happy without the parameters or query objects)

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

(If I find how to fix the issue, though)

**Comment by drwpow** [comment]
This indeed looks like a bug, and would welcome a PR on this! The easiest way to fix this would be adding a failing test in [operation-object.test.ts](https://github.com/drwpow/openapi-typescript/blob/6.x/packages/openapi-typescript/test/operation-object.test.ts) in the `6.x` branch. Then in the operation-object transformer, remove any deprecated params [from the params object](https://github.com/drwpow/openapi-typescript/blob/6.x/packages/openapi-typescript/src/transform/operation-object.ts#L19).

Be sure to base off `6.x`—the current `main` is for the upcoming `7.x` release.

**Comment by benevbright** [comment]
@drwpow thanks a lot. I opened PR https://github.com/drwpow/openapi-typescript/pull/1551
