### ISSUE TITLE
Exception in catch block: `TypeError: Response.text: Body has already been consumed.`

### ISSUE THREAD

**Issue by tgross35** [drwpow/openapi-typescript#1544]
**Description**

If the error response is not JSON, this will raise a type error rather than returning the error body text.

**Reproduction**

Use the fetch API to hit an endpoint that returns a 4xx response with invalid JSON (i.e. plaintext). Based on debugging, the following is the issue:

```js
    // handle errors (always parse as .json() or .text())
    let error = {};
    try {
      error = await response.json();
    } catch {
      error = await response.text();
    }
```

`await response.json();` seems to first consume the body, then try parsing JSON. If reading the body succeeds but parsing the JSON fails, then the `catch` block will hit and `response.text()` will fail (since the body has already been consumed).

**Expected result**

`error` should probably still contain the error text, even if the response is non-JSON. I believe that the below would fix this:

```js
    const text = await response.text();
    try {
      error = JSON.parse(text);
    } catch {
      error = text;
    }
```

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Great catch! We had tests for unexpected responses for `data`, but not for `error`. 

This would normally be a great issue for someone to pick up, but given this could break some sites and is a regression from the `0.9.0` version released earlier today, probably better to patch it sooner than later.

**Comment by tgross35** [comment]
Thanks for the quick fix!
