### ISSUE TITLE
Document Chinese support

### ISSUE THREAD

**Issue by phk422** [drwpow/openapi-typescript#1560]
Hi, @drwpow ! For the convenience of Chinese users, I want the document to support Chinese and I can participate in the construction and translation

**Comment by drwpow** [comment]
We would love that! Vitepress makes i18n easy; I just haven’t set it up yet. I will make some placeholder documents and let you (and others) contribute as they’re able to.

What would be a good ISO URL path to set up placeholders? `/zh/…`, `/yue/…`, or something else?

**Comment by drwpow** [comment]
Opened up #1561 for feedback! Please suggest any/all changes. Also see the [preview deployment](https://i18n.openapi-ts.pages.dev/). Ideally you could open up a few PRs against this branch, and we could merge in, just so a couple articles are filled in. Then happy to merge when there’s any content at all, and we can build it over time (doesn’t have to be complete 1st pass or anything)

**Comment by phk422** [comment]
Hello @drwpow ,Before we get started, I realized when using the light theme, the Get start button on the home page is not visible.
![image](https://github.com/drwpow/openapi-typescript/assets/59734322/feeadaf8-22ab-4a92-9786-7c2f5929e76e)

**Comment by drwpow** [comment]
The button color is set with [oklch](https://caniuse.com/?search=oklch); does your browser/OS not support that? And if not, what are you using? (I had thought it had wide support now but I guess I was mistaken)

**Comment by drwpow** [comment]
Oh! It’s not `oklch()` that’s the problem; it’s that the color is in the [P3 gamut](https://oklch.com/#40,0.2,260,100) and needs a fallback for non-P3 monitors. Will fix! Thank you.

**Comment by phk422** [comment]
> The button color is set with [oklch](https://caniuse.com/?search=oklch); does your browser/OS not support that? And if not, what are you using? (I had thought it had wide support now but I guess I was mistaken)

My Google browser hasn't been upgraded for a long time, but when I upgraded to the latest version, it worked fine. Maybe it's a browser version compatibility issue

**Comment by drwpow** [comment]
It’s live! 🙌 Thanks so much for all your hard work! 🙂 There are still a few more pages to translate, but I wanted to at least get all the pages you have done up so that the work can happen as you have time to (and also for others to help contribute—maybe this will even inspire other languages). Thanks so much for making this happen ❤️

**Comment by drwpow** [comment]
This has been completed! 🎉 While there will always be room for additional PRs and fixes, I think this ticket has served its purpose.
