### ISSUE TITLE
Fetch method type incorrectly blocks `headers`

### ISSUE THREAD

**Issue by mikestopcontinues** [drwpow/openapi-typescript#1573]
**Description**

`FetchOptions` block adding [custom headers](https://github.com/drwpow/openapi-typescript/blob/ba1aca51cf6adf7983157ac904b6ab19b9a894d8/packages/openapi-fetch/src/index.d.ts#L110) to a request, but [`coreFetch` supports it](https://github.com/drwpow/openapi-typescript/blob/ba1aca51cf6adf7983157ac904b6ab19b9a894d8/packages/openapi-fetch/src/index.js#L35).

The fetch methods should support adding custom headers, as many apis rely on headers for metadata related to the request. Additionally, it's sometimes necessary to override the auth for a particular api request. For example, if you're using `openapi-fetch` in your backend, and you need to authenticate as the current user.

I currently use custom headers for both of these things.

**Reproduction**

Try adding `{headers}` to any request method.

**Expected result**

It should not throw a type error.

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by mikestopcontinues** [comment]
Apologies, this is completely mistaken. It was an issue with my wrapper and the new version of `openapi-fetch`.

**Comment by drwpow** [comment]
Thanks for reporting! There’s always the possibility of some weird behavior with the new middleware and some internal changes to how that `Request` gets built. Glad you were able to find a workaround, and please open up any additional issues if you come across anything else 🙂
