### ISSUE TITLE
Lost type-safety while modify response in the middleware

### ISSUE THREAD

**Issue by JE-lee** [drwpow/openapi-typescript#1583]
**Description**

All of my backend api response data specified the shape like this:
```typescript
type Vo = {
  code: number;
  message: string;
  data: any;
}
```
I need to access the meaningful data by typing the word 'data' twice.
```typescript
const res = await client.GET("/api/v1/space")
const list = res.data?.data.content
```

To avoid this unnecessary repetition, I modified the response in the middleware to extract only the data like this:

```typescript
const extractResponseMiddleware: Middleware = {
  onResponse: async (res, options) => {
    const body = await res.json();
    if (body.code === 0) {
      return new Response(JSON.stringify(body.data), {
        status: 200,
        statusText: "OK",
        headers: res.headers,
      });
    } else {
      throw new Error(body.message)
    }
  }
}
```
However, this modification didn't affect the TypeScript checking of `const list = res.data?.data.content`. 
Instead, it resulted in a runtime error because the actual access method is `const list = res.data.content`.
It seems like we lost the right type of the response.

I'm not sure if this issue can be resolved.

**Comment by drwpow** [comment]
Correct—middleware is runtime; openapi-typescript relies on static inference at build time to assert type safety. There’s no way to update your types based on what happens at runtime in middleware; modifying your response will always result in type errors.

Middleware is better used for things like auth, or logging, or _appending_ requests/responses with additional data, rather than modifying them outright.

**Comment by JE-lee** [comment]
This is my workaround. Modifying the response and modifying the `paths` type at the same time.
```typescript
type Vo<T> = {
  code: number;
  message: string;
  data: T;
};

type ExtractType<T> = T extends Vo<infer R>
  ? R
  : T extends Object
  ? { [K in keyof T]: ExtractType<T[K]> }
  : T;

const client = createClient<ExtractType<paths>>()
```
Now I get the simplified response as the type-safety of the responses.
