### ISSUE TITLE
Type discrimination between `data` and `error` doesn't work

### ISSUE THREAD

**Issue by illright** [drwpow/openapi-typescript#1609]
**Description**

A simple if-statement on `dataRes.data` fails to correctly discriminate `data` and `error`, which results in the `error` type being `never`:

```ts
const dataRes = await GET('/');

if (dataRes.data) {
  expectTypeOf(dataRes.data).toEqualTypeOf({
    objects: [{ id: '', name: '' }],
  });
} else {
  expectTypeOf(dataRes.data).toBeUndefined();
  expectTypeOf(dataRes.error).toEqualTypeOf({ errors: { body: [''] } });
}
```

<details><summary>The OpenAPI spec used for this example</summary>

```yaml
openapi: 3.0.1
info:
  title: Test API
  version: 1.0.0
  
paths:
  /:
    get:
      description: List objects
      operationId: GetObjects
      responses:
        '200':
          $ref: '#/components/responses/ObjectsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/GenericError'

components:
  schemas:
    Object:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    GenericErrorModel:
      required:
        - errors
      type: object
      properties:
        errors:
          required:
            - body
          type: object
          properties:
            body:
              type: array
              items:
                type: string
  responses:
    ObjectsResponse:
      description: Objects
      content:
        application/json:
          schema:
            required:
              - objects
            type: object
            properties:
              objects:
                type: array
                items:
                  $ref: '#/components/schemas/Object'
    Unauthorized:
      description: Unauthorized
      content: {}
    GenericError:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericErrorModel'
```

</details>

**Reproduction**

https://stackblitz.com/edit/vitejs-vite-vnadlg?file=README.md&view=editor

**Expected result**

It should allow checking `dataRes.data` or `dataRes.error` and choosing either the success type or the error type

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by illright** [comment]
I investigated this issue further, turns out that the problem is in the `FilterKeys` utility type and its filtering by MIME type. When there are several error responses and they have non-overlapping content types, instead of filtering those out, it's reducing the type to `never`. Here's a minimal TypeScript snippet that demonstrates the issue:

```ts
type FilterKeys<Obj, Matchers> = Obj[keyof Obj & Matchers];

type Responses = {
  200: { "application/json": string; };
  401: {}
  422: { "application/json": number };
}

// this is `never`
type Result = FilterKeys<FilterKeys<Responses, ErrorStatus>, "application/json">
```

**Comment by drwpow** [comment]
Ah great investigation. I hadn’t dug into it yet, but that’s currently an untested code path and I could see that causing errors. Thanks for opening a PR!

**Comment by topaxi** [comment]
I came here due to #1723.

Something like [this](https://www.typescriptlang.org/play/?ssl=20&ssc=8&pln=15&pc=1#code/C4TwDgpgBAYglgG2BATgaQiAzgHgPIBGAVgDRQCyAhsAMYAWqWAfFALxSFFQQAeyAdgBMsHYgG0A1pgD2AM1FcAZBWr1GAXSgB+BZJnzOUZVVoMUWTQC5dUkHIVGVpjVAA+UfhABuqANwAof1BIDgkAJQgsMGl+LAgAYWlBSLYoACYABgyg8GgAURQUaRQIqJi4xOSRdgAWDIBGNygatLSmgFYsgJyQ0ujYlPYAb38odKzrIagAIkowMAQ4Gmo4GIB6IiwY6esImmLBHCxgFDh+AHMyY9OLpl8Z5D41umAAWwQdqGuz86gAXwCYzq9Umf1GzVakxmcwWSxW60222s-AArq8CKh-oCoJ0MlDpo9gM83h9rN8Lv9-GCetA8OFIv04tVYIhkOhMLg+uVImQ6VyBpVIkxwVA1msAHpaQLBaAAKQAyngAHJ8hnc5nwJCoDDYfD0soDLBkWbzRbLYCrfgbLb8abCsaiiVSmlQAASABVyAAZVUGpmpTVsnW4X2MnkPXhEl7vO0isWS6W5KAFIolNWGgOs7UcnD8plkFPFPMJJJCuNOxMhACC-BAhbTfsGLK17N19eLRqgAAMACRDcnnP5rPsDv5d+1jePOmVQBXK9vp-3sQPZtuFIuL8Mm2Hmy3W7YTx0Jl0e70LxsarOt3DnsOdgmR4kxw9ToA) seems to do a bit better, although I'm not confident making the change for a type that is being used as much as `FilterKeys` :sweat_smile: 

```ts
type FilterKeys<Obj, Matchers> = Obj extends Obj[keyof Obj & Matchers] ? Obj[keyof Obj & Matchers] : Obj[keyof Obj & Matchers] | never;

type OkResponseCodes = 200
type ErrorResponseCodes = 401 | 422 | 500;

type Responses = {
  200: { "application/json": Record<string, string>; "text/html": string };
  401: {}
  422: { "application/json": number };
  500: { "text/html": string }
}

type OkResponses = FilterKeys<Responses, OkResponseCodes>
   //^? { "application/json": Record<string, string>; "text/html": string; }

type JSONOkResponses = FilterKeys<OkResponses, "application/json">
   //^? Record<string, string>

type HTMLOkResponses = FilterKeys<OkResponses, "text/html">
   //^? string

type ErrorResponses = FilterKeys<Responses, ErrorResponseCodes>
   //^? {} | { "application/json": string; } | { "text/html": string; }

type AnyErrorResponses = FilterKeys<ErrorResponses, `${string}/${string}`>
   //^? string | number

type JSONErrorResponses = FilterKeys<ErrorResponses, "application/json">
   //^? number

type HTMLErrorResponses = FilterKeys<ErrorResponses, "text/html">
   //^? string
```
