### ISSUE TITLE
Uncaught error when body is `undefined` in request init

### ISSUE THREAD

**Issue by jaredLunde** [drwpow/openapi-typescript#1666]
**Description**

> Uncaught TypeError: Cannot set property body of #<Request> which has only a getter

<img width="435" alt="Screenshot 2024-05-17 at 4 53 14 PM" src="https://github.com/drwpow/openapi-typescript/assets/86995/c98fd420-2096-4670-b79a-1fa8d10b08c8">

https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/src/index.js#L16-L20

Basically, `body` is a getter on the `Request` object and the linked code is trying to write to it. One work around could be to wrap it in a try/catch. Otherwise I think you'll have to ignore some properties in the request init

**Reproduction**

Add a `body` to the request init object in `openapi-fetch@0.9.6` e.g. `client.POST('/', {body:undefined})`.

Happens in all major browsers AFAICT

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by FreeAoi** [comment]
Hello! I can't reproduce the bug with the information provided, could you please create a repository where we can test it?

**Comment by jaredLunde** [comment]
Perhaps it is related to Bun, Astro, or Vite in some way. I'm not 100% sure where the Request global is being set, but I had assumed it was the browser's. Unfortunately I can't figure out how to install Bun on StackBlitz to dig further into a repro. Regardless, there's clearly some incompatibility in the vast JS/TS ecosystem as a result of overwriting `Request` properties that are not "custom". Finding some other means of adding them would probably be beneficial for that reason.

**Comment by jaredLunde** [comment]
Since `body` can be `undefined`, I'm guessing the naive check agains `!this["body"]` in the `CustomRequest` object is returning a false positive, while `key in this` would not return a false positive.

**Comment by FreeAoi** [comment]
I will take a look on this and if its necessary I will make a PR to fix it

**Comment by jaredLunde** [comment]
Oh wow, I'm so sorry. I have a repro: https://stackblitz.com/edit/vitejs-vite-3tdy1b?file=src%2FApp.tsx

If `body` is `undefined` you can reproduce the issue easily in the browser.

**Comment by FreeAoi** [comment]
Alr makes sense https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/src/index.js#L17 return a false positive, you could do the PR fixing this by changing that conditional to `!(key in this)`
