### ISSUE TITLE
`type: object` generating `Record<string, never>`

### ISSUE THREAD

**Issue by CalebJamesStevens** [drwpow/openapi-typescript#1686]
**Description**
When using the type `object` in the yaml file, it gets converted to Record<string, never> in TypeScript
```yaml
paths:
  /endpoint:
      post:
        summary: Summary
        description: Some description
        responses:
          200:
            description: Some description
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    propertyOne:
                      type: array
                      items:
                        type: object
                    propertyTwo:
                      type: object
```
```ts
  endpointPost: {
    responses: {
      /** @description Return the results of the resolution */
      200: {
        content: {
          "application/json": {
            propertyOne?: Record<string, never>[];
            propertTwo?: Record<string, never>;
          };
        };
      };
```

**Reproduction**

Run the current typescript converter on a yaml file with the configuration above

**Expected result**

A valid type for objects

**Checklist**

- [ x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This is intentional behavior to prevent `Record<string, any>` (or even `Record<string, unknown>`) because it’s ambiguous. [See the docs on why this happens and how to generate more specific types](https://openapi-ts.pages.dev/advanced#be-specific-in-your-schema).
