### ISSUE TITLE
Is there a plan to support cookie parameters?

### ISSUE THREAD

**Issue by zaru** [drwpow/openapi-typescript#1689]
**Description**

Hello! I’m using openapi-fetch conveniently. Thank you. I would be delighted if openapi-fetch supported cookie parameters. Currently, I am sending cookies from the headers as follows:

```ts
const { data, error } = await fetchClient.GET("/me", {
  params: {
    header: {
      Cookie: "_session_id=foobar",
    },
  },
});
```

**Proposal**

I propose that we add support for specifying cookie parameters directly. For example:

```ts
const { data, error } = await fetchClient.GET("/me", {
  params: {
    cookie: {
      _session_id: "foobar",
    },
  },
});
```

I found that adding the following code to the index.js of openapi-fetch works, but I’m not sure if this is the correct approach:

```diff
diff --git a/packages/openapi-fetch/src/index.js b/packages/openapi-fetch/src/index.js
index e0cb43c..e612304 100644
--- a/packages/openapi-fetch/src/index.js
+++ b/packages/openapi-fetch/src/index.js
@@ -76,6 +76,14 @@ export default function createClient(clientOptions) {
       ...init,
       headers: mergeHeaders(baseHeaders, headers, params.header),
     };
+
+    if (params.cookie) {
+      const cookieValue = Object.entries(params.cookie)
+        .map(([key, value]) => `${key}=${value}`)
+        .join("; ");
+      requestInit.headers.set("Cookie", cookieValue);
+    }
+
     if (requestInit.body) {
       requestInit.body = bodySerializer(requestInit.body);
     }
```

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow-figma** [comment]
Love this request! I think as a start, I’d love to see **documentation added** on [the middleware section](https://openapi-ts.pages.dev/openapi-fetch/middleware-auth#middleware) on a way to achieve this with middleware—listening for the cookie header and adding it to the request. We could also maybe add it as a generic [example](https://openapi-ts.pages.dev/openapi-fetch/examples) as well.

I feel that people managing the nuances of cookie management via middleware is a better option than baking an opinionated approach to cookies in this library. But say we document everything and learn that there’s more indirection / a simpler way to allow this with less boilerplate, at which point I’d consider adding this as a feature. But either way, **I think documentation is the place to start**!

**Comment by zaru** [comment]
Thank you for the response! I agree that implementing this via middleware seems more appropriate. I will first try it with middleware, and if I feel it is worth adding to the documentation, I will make a proposal.
