### ISSUE TITLE
Types are not sent to stdout if `-o` is omitted

### ISSUE THREAD

**Issue by jfsiii** [drwpow/openapi-typescript#279]
### Steps to reproduce
```
npx @manifoldco/swagger-to-ts https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json
```

### What I expect to happen
See TS types printed to the screen as [documented](https://github.com/manifoldco/swagger-to-ts#cli-options) 

### What I observe
No TS types are shown

```
npx @manifoldco/swagger-to-ts https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json
This library has been updated to 2.0 with improved generation. If you experience issues you can use the deprecated v1 with `npx @manifoldco/swagger-to-ts@1 …`
🤞 Loading spec from https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json…
```

**Comment by drwpow** [comment]
This would be a good feature! Would love a PR from anyone able to provide it.

**Comment by jfsiii** [comment]
@drwpow Are the docs wrong or do I misunderstand them?

One issue with printing to stdout is the `This library has been ...` & `🤞 Loading spec ...` lines currently go to stdout, which puts them in the output file, e.g.

```
> swagger-to-ts https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json > types.ts
> cat types.ts
✨ swagger-to-ts 2.0
This library has been updated to 2.0 with improved generation. If you experience issues you can use the deprecated v1 with `npx @manifoldco/swagger-to-ts@1 …`
🤞 Loading spec from https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json…
```

Should those lines only be printed to stdout if the output flag/alias is given? I can't immediately think of a way to display to the screen and still support pipes. LMK if you have any ideas/suggestions.

**Comment by drwpow** [comment]
> @drwpow Are the docs wrong or do I misunderstand them?

Sorry; I was unclear. Yes, the docs are wrong—it doesn’t export to stdout, and I don’t think it ever has. 

This isn’t by design, just oversight. I think it may have been a behavior I had planned on implementing but never did. I’m in solid agreement that stdout should be supported, and it should be the default behavior without the `-o` flag.
