### ISSUE TITLE
[Repo update] New name?

### ISSUE THREAD

**Issue by drwpow** [drwpow/openapi-typescript#332]
Hello! As many of you have pointed out, releases slowed down while this repo was under an organization I was no longer a part of. Now that’s changed, and I’m now owner of the repo name, and now get all notifications & updates again.

However, this also means the npm name has to change as well, from `@manifoldco/swagger-to-ts` to… something!

It looks like `swagger-to-ts` is already taken by [an existing npm package](https://www.npmjs.com/package/swagger-to-ts), but is there a better name (maybe shorter)? Here are some possibilities:

- `oapi-ts`: Celebrating Swagger’s name change to OpenAPI, and adding `ts` at the end. Short, sweet.
- `oapi-typescript`: Same, but longer
- `swagger2ts`: similar concept
- ??? other suggestions?

Note that the next release will be at this new namespace, and we’ll add a deprecation warning to `@manifoldco/swagger-to-ts`.

cc @gr2m

**Comment by gr2m** [comment]
Hey, congrats on the move! I like descriptive names, what about `openapi-to-typescript`?

I'm also a fan of merging projects, maybe you can reach out to the maintainer of openapi-to-ts and see if you want to join forces? It seems like you have both the same scope?

**Comment by drwpow** [comment]
Update: new repo is at `openapi-typescript`! 🎉 Closing this because it’s been named, and that’s also what the deprecation notice has been set to for `@manifoldco/swagger-to-ts`.
