### ISSUE TITLE
requestBody parameters are missing

### ISSUE THREAD

**Issue by gr2m** [drwpow/openapi-typescript#338]
For example, GitHub's example schema (`tests/v3/specs/github.yaml`) has lots of `requestBody` parameters. But the generated TypeScript types (`tests/v3/expected/github.ts`) do not have any of it

As suggested in my comment here: https://github.com/drwpow/openapi-typescript/issues/236#issuecomment-701054647, I'd transform something like this

```yml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                homepage:
                  type: string
                private:
                  type: boolean
                  default: false
              required:
                - name
```

into

```ts
      requestBody: {
        "application/json": {
          name: string;
          description?: string;
          homepage?: string;
          private?: boolean;
        };
      };
```

**Comment by drwpow** [comment]
Yup! That makes perfect sense to me. I think your suggestion follows this projects rough guideline of “as close as possible to the spec”
