### ISSUE TITLE
export operations interface

### ISSUE THREAD

**Issue by gr2m** [drwpow/openapi-typescript#341]
As suggested in my comment at https://github.com/drwpow/openapi-typescript/issues/236#issuecomment-701054647, I'd prefer to export an `operations` interface, besides `paths` and `components`.

Instead of setting the types for each operation in the `paths` object, I'd reference an `operation` key using the operations ID`. In the example of the GitHub OpenAPI schema,

```ts
export interface paths {
  "/": {
    /**
     * Get Hypermedia links to resources accessible in GitHub's REST API
     */
    get: {
      // ...
    }
  }
}
```

would result in

```ts
export interface paths {
  "/": {
    get: operations["meta/root"]
  }
}
export interface operations {
  /**
   * Get Hypermedia links to resources accessible in GitHub's REST API
   */
  "meta/root": {
     // ...
  }
}
```

`operationId`s are great to generate SDK methods. Having the `operation` export with direct access to operation types would make it easier to access the operation types for parameters and responses

**Comment by drwpow** [comment]
I‘m looking at the spec at this seems like it‘d be the first departure we‘d have from the OpenAPI schema format. It looks like the way `get: operations["meta/root"]` is used, it seems like the `paths` interface would behave the same way, which would be my only concern.

But what is the advantage here? Would this primarily save some typing to use `operations["meta/root"]` rather than `paths["/"]["get"]["meta/root"]`?

**Comment by gr2m** [comment]
I don't think this change should break anything. `paths["/"]["get"]` would result the same thing as `operations["meta/root"]`, it would just add an alternative means of accessing the operation types, it can by quite cumbersome to access them if the paths get long and complicated. For exmaple

```js
paths["/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments/{comment_number}/reactions/{reaction_id}"]["delete"]
```

would result the same as

```js
operations["reactions/delete-for-team-discussion-comment"]
```

**Comment by drwpow** [comment]
Cool. Thanks for clarifying, and for providing a better usecase. In that case I’m in favor of this, and agree that‘d be an improvement. Also, I think as `operationId` isn‘t a super-used aspect of OpenAPI as far as I‘m aware, I’m fine with adding some QoL stuff on top of that.

**Comment by gr2m** [comment]
cool I'll look into it thanks!
