### ISSUE TITLE
Numeric status codes

### ISSUE THREAD

**Issue by jankuca** [drwpow/openapi-typescript#380]
Hello, I really like this library but I had to fork it to be able to actually use it.

My issue is that the `responses` object lists the response status codes as strings. I need to be able to use numeric values in my codebase and I am not able to check them against the generated TS types.

---

My solution was to replace the `{ [statusCode]: responseBodies }` object with a discriminated union:

```ts
responses:
  | { statusCode: 200, bodies: … }
  | { statusCode: 202, bodies: … }
  | { statusCode: 400, bodies: … }
```

I can get a numeric enum from that simply by using `responses['statusCode']`.

---

I've also noticed that TS allows actual numeric keys such as `{ 200: … }` (instead of `{ "200": … }`) so that could be enough.

Would such a change be acceptable? What is the actual reason the keys are strings anyway?

**Comment by gr2m** [comment]
I've run into a similar problem. I worked around it by using a type map

```
type StatusCodes = {
  "200": 200,
  "201": 201,
  // etc
}
```



> I've also noticed that TS allows actual numeric keys such as `{ 200: … }` (instead of `{ "200": … }`) so that could be enough.
> 
> Would such a change be acceptable? What is the actual reason the keys are strings anyway?

I'd like that, too. I don't see a reason why the status code type should be a string

**Comment by jankuca** [comment]
I went ahead and prepared a PR for this change.

**Comment by drwpow** [comment]
I agree with this reasoning, and the PR at first glance looks great too. Will test it a bit more later tonight.

Thank you!
