### ISSUE TITLE
Response Headers

### ISSUE THREAD

**Issue by jankuca** [drwpow/openapi-typescript#393]
The response headers defined in the OpenAPI document are lost. It would be great to be able to type-check them.

Two possibilities:

1. (breaking change) Changing the format of the responses to include both content and headers: 

```
responses: {
  [statusCode: number]: {
    content: { [contentType: string]: … },
    headers: { [name: string]: string }
  }
}
```

2. (backwards-compatible change) Adding a separate field for response headers:

```
responses: {
  [statusCode: number]: { [contentType: string]: … }
},
responseHeaders: {
  [statusCode: number]: { [name: string]: string }
}
```

---

In the OpenAPI format, response headers are placed in the response objects such as

```
"responses": {
  [statusCode]: {
    "description": "…",
    "content": {
      [contentType]: …
    },
    "headers": { [name]: "…" }
  }
}
```

**Comment by gr2m** [comment]
I would prefer the first option, even though it's a breaking change.

**Comment by drwpow** [comment]
I think I added support for this here: https://github.com/drwpow/openapi-typescript/pull/429

I also am in favor of option #1, because I’ve found whenever you don’t perfectly match the Swagger schema you’re gonna have a bad time 🙂

**Comment by tshelburne** [comment]
It's working for me as in option 1.

**Comment by drwpow** [comment]
This is now released in `3.x` of this library! 🎉 Closing, but please reopen if you encounter any problems.
