### ISSUE TITLE
'definitions' missing from schema

### ISSUE THREAD

**Issue by shalltears** [drwpow/openapi-typescript#398]
E:\gim>npx openapi-typescript C:\Users\shall\Desktop\swagger.json --output schema.ts
✨ openapi-typescript 2.4.2
� Loading spec from C:\Users\shall\Desktop\swagger.json…
Error: ⛔️ 'definitions' missing from schema https://swagger.io/specification/v2/#definitions-object
    at generateTypesV2 (E:\gim\node_modules\openapi-typescript\dist-node\index.js:203:13)
    at swaggerToTS (E:\gim\node_modules\openapi-typescript\dist-node\index.js:541:32)
    at E:\gim\node_modules\openapi-typescript\bin\cli.js:56:18

my json file in desktop，why can not use

![image](https://user-images.githubusercontent.com/37053882/101110118-4a137600-3613-11eb-9cbe-9c43562d07f7.png)

**Comment by drwpow** [comment]
Does your file have a top-level `definitions` key? That’s needed to use `2.0` support. See the [Stripe OpenAPI V2 example](https://github.com/drwpow/openapi-typescript/blob/main/examples/stripe-openapi2.ts)

**Comment by divyenduz** [comment]
Is it required in the spec though? I was looking at Strava API in the platground https://developers.strava.com/playground/ and their swagger file has no top level `definitions` https://developers.strava.com/swagger/swagger.json

**Comment by drwpow** [comment]
Good news! As of v3 of this library, we now generate more of the Swagger 2.0 schema (`paths`, for example), so this error has gone away. Closing this issue, but please reopen if you encounter any issues.
