### ISSUE TITLE
Set exit codes for errors

### ISSUE THREAD

**Issue by marcinjosinski** [drwpow/openapi-typescript#423]
Hello 👋, 
first of all, thanks for maintaining such a great package!

I run openapi-typescript in CI and noticed that even unsuccessful schema conversion returns an exit code of 0.

For example:
```bash
$ npx openapi-typescript swagger.yaml --output schema.ts
✨ openapi-typescript 2.4.2
🤞 Loading spec from swagger.yaml…
❌ "Cannot find spec under the following path: /.../swagger.yaml"
$ echo $?
0
```

I've built a workaround to this but maybe it'd be a good idea to return different exit statuses for errors.

**Comment by gr2m** [comment]
I agree, what do you think @drwpow?

Could you get a pull request going? We can discuss details there

**Comment by drwpow** [comment]
This seems like a good change; definitely shouldn’t be exiting `0` on a fatal error like this. I’ll open up a PR and we can discuss more. Thanks for raising!
