### ISSUE TITLE
Subschemas of type=object silently omit information from properties when anyOf/oneOf are set

### ISSUE THREAD

**Issue by dbjorge** [drwpow/openapi-typescript#461]
#### Summary

Subschemas of `"type": "object"` which include both `properties` and `oneOf`/`anyOf` clauses are not being parsed correctly; in particular, it appears that if an object specifies `oneOf`/`anyOf`, it results in the generated typings omitting any information specified under `properties`, rather than combining them like the reference docs on [json-schema.org](https://json-schema.org/understanding-json-schema/reference/combining.html) and [swagger.io](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) suggest should be happening.

#### Impact

This comes up in a few places in GitHub's OpenAPI specification (https://github.com/octokit/rest.js/issues/2000)

#### Minimal repro

Note that `prop_in_root_properties` does not appear in the output:

```yaml
{
  "openapi": "3.0.3",
  "components": {
    "schemas": {
      "oneOf-example": {
        "type": "object",
        "properties": {
          "prop_in_root_properties": { "type": "string" },
        },
        "oneOf": [
          {
            "properties": {
              "prop_in_anyOf_clause_a": { "type": "string" }
            },
          },
          {
            "properties": {
              "prop_in_anyOf_clause_b": { "type": "string" }
            },
          },
        ],
      },
      "anyOf-example": {
        "type": "object",
        "properties": {
          "prop_in_root_properties": { "type": "string" },
        },
        "anyOf": [
          {
            "properties": {
              "prop_in_anyOf_clause_a": { "type": "string" }
            },
          },
          {
            "properties": {
              "prop_in_anyOf_clause_b": { "type": "string" }
            },
          },
        ],
      },
    },
  },
}
```

```bash
> npx openapi-typescript .\repro-schema.yaml
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    "oneOf-example":
      | {
          prop_in_anyOf_clause_a?: string;
        }
      | {
          prop_in_anyOf_clause_b?: string;
        };
    "anyOf-example": Partial<{
      prop_in_anyOf_clause_a?: string;
    }> &
      Partial<{
        prop_in_anyOf_clause_b?: string;
      }>;
  };
}

export interface operations {}
```

**Comment by drwpow** [comment]
You know, this was actually a point of confusion for me when writing this, and I thought “there’s no way `properties` and `anyOf` / `oneOf` would be used together. I guess I was wrong! 🙂 

For clarification, though, on the link you posted, I’m actually not seeing `properties` used in combination with `anyOf` or `oneOf`, in either of your links. Though if I try and through that in the OpenAPI validator, it does let me do that. However, does this make sense to do so logically? I’m still unclear on whether `properties` and `anyOf`/`oneOf` is an “AND” or “OR” relationship (I think you’re saying the octokit schema assumes the former, but do others have that same assumption)?

I’m OK with adding this behavior if it’s beneficial to your usecase; I just want to make 100% sure that I’m not violating the spec here.

**Comment by dbjorge** [comment]
I definitely agree that it's more important to respect the spec than our specific current use case! I appreciate you wanting to double check what the spec says the behavior should be 👍 

I think the relevant spec here would be [OpenAPI v3.0.3 section 4.7.24 (Schema Object)](http://spec.openapis.org/oas/v3.0.3.html#schema-object), which says:

> The Schema Object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. This object is an extended subset of the [JSON Schema Specification Wright Draft 00](https://json-schema.org/).
>
> For more information about the properties, see [JSON Schema Core](https://tools.ietf.org/html/draft-wright-json-schema-00) and [JSON Schema Validation](https://tools.ietf.org/html/draft-wright-json-schema-validation-00). Unless stated otherwise, the property definitions follow the JSON Schema.
> ...
> The following properties are taken from the JSON Schema definition but their definitions were adjusted to the OpenAPI Specification.
> ...
> allOf - Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema.
> oneOf - Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema.
> anyOf - Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema.
> not - Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema.
> ...
> properties - Property definitions MUST be a Schema Object and not a standard JSON Schema (inline or referenced).

This doesn't specify a definition adjustment to how the `properties` and `anyOf`/`oneOf`/etc interact with one another, so I believe the references JSON schema spec applies. I think the relevant part is section [4.3 (Linearity)](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-4):

> Validation keywords typically operate independent of each other, without affecting each other.
> For author convienence, there are some exceptions:
> - "additionalProperties", whose behavior is defined in terms of "properties" and "patternProperties"; and
> - "additionalItems", whose behavior is defined in terms of "items"

...where a "validation keyword" is defined generally in [section 5](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5) as:

> Validation keywords in a schema impose requirements for successfully validating an instance.

...and subsequent sections give more precise definitions of `properties` (5.16), `anyOf` (5.23), `oneOf` (5.24), etc as being specific validation keywords.

My reading of the phrases "validation keywords... operate independently of each other" together with "validation keywords... impose requirements for successfully validating an instance" is that each validation keyword must be independently satisfied to successfully validate an instance. I could imagine interpreting this differently, though, it would be nice if the spec were a little more explicit.

**Comment by drwpow** [comment]
Thanks for all the thought put into it! I’m glad to hear that you also see the spec as being ambiguous here. In that case, then I’m fine filling in the gaps. Because you‘re right—this is technically _valid_ but the behavior just isn’t clear.

I think this would be a good addition to the library. I may not have time to make a PR for this myself anytime soon, but I’d welcome a contribution here! [This code](https://github.com/drwpow/openapi-typescript/blob/main/src/transform/schema.ts#L102) should be the only thing you need to modify. And as long as we add a test for this confirming that we’re only adding functionality, not changing schema generation for anything else, then I’m on board.

**Comment by dbjorge** [comment]
Understood, thank you!

**Comment by drwpow** [comment]
The handling for `oneOf`/`anyOf`/`allOf` has been reworked and greatly improved in the upcoming v6 release. Hopefully this problem will be fixed with the upcoming release.

I did run across this note on [illogical schemas](https://json-schema.org/understanding-json-schema/reference/combining.html#illogical-schemas) on the JSON Schema docs, which does seem to point out that not every permutation can be resolved. But again, in the v6 version, all conceivably-logical interpretations of these 3 properties have been improved (and if not, please open another issue on the matter 🙏 )
