### ISSUE TITLE
openapi 2: Undescriptive error on missing definitions

### ISSUE THREAD

**Issue by tstelzer** [drwpow/openapi-typescript#469]
Given a spec without a `definitions` section, `openapi-typescript` throws `TypeError: Cannot convert undefined or null to object`.

I would expect a more descriptive error that hints at adding a `definitions` section.

Version: 3.0.1

**Comment by drwpow** [comment]
Ah this is a bug. We’re supposed to be able to handle Swagger v2 schemas without definitions now because the spec allows it, but I think we’re just missing a null check somewhere (maybe the TypeScript types need to be looser too).

**Comment by drwpow** [comment]
Just released in `3.0.4`.
