### ISSUE TITLE
http client generation

### ISSUE THREAD

**Issue by FedeBev** [drwpow/openapi-typescript#498]
Hi there,

I know that right now the generation of an http client is not one of the goals of this project, but would you be open to think about that?
I think this could be really useful because, as far as i know (please, tell me if I'm wrong), there is nothing native for the node/js/ts world that generates both types and client (maybe with a validation layer, woud be "easy" with something like [ajv](https://github.com/ajv-validator/ajv)).
The only options I know are swagger-codegen and swagger-hub. In my opinion, the main problems are that the first one is java-based (so you need java or docker to use that) and with a very very low customization level, the second one is online and I think this is a very awkward approach in a real world project. 

If you are open to evaluate this proposal, I'll be glad to help and contribute.
Thanks

**Comment by gr2m** [comment]
I think that is out of scope for `openapi-typescript`. I use it as part of generating code for GItHub's JavaScript SDK (@octokit), but it's very custom to what we need for GitHub, it couldn't be easily applied to other schemas.

**Comment by drwpow** [comment]
Hey FedeBev! I love the suggestion, but as someone that’s familiar with Swagger’s HTTP Client as well as having built my own, that’s a pretty big task, and one I feel would be best served as a separate project altogether.

> The only options I know are swagger-codegen and swagger-hub. In my opinion, the main problems are that the first one is java-based (so you need java or docker to use that) and with a very very low customization level, the second one is online and I think this is a very awkward approach in a real world project.

You did pinpoint exactly why this project exists, though! 😄 I was frustrated with Swagger Codegen myself, and there weren’t other lightweight alternatives to do what I wanted. So I definitely feel your pain in that aspect.

> If you are open to evaluate this proposal, I'll be glad to help and contribute.

What do you think about starting this up yourself? I wouldn’t have the time to manage a Swagger-generated HTTP client myself, but if this is something you’re interested in, I’d be happy to help contribute myself. And if you haven’t created an open source library yourself before, I’d be happy to share everything I’ve learned and help with project setup, too.

**Comment by drwpow** [comment]
Going to close, but my offer still stands: happy to offer help/advice/contributions to any other project that handles client generation. That’s basically a “from scratch” addition, and outside the scope of this project for now.
