### ISSUE TITLE
Enhancement: readonly arrays

### ISSUE THREAD

**Issue by laurence-myers** [drwpow/openapi-typescript#501]
It would be nice if we could use `ReadonlyArray` in place of `[]`. Currently, trying to return a `ReadonlyArray` in a response will fail type checking, because the response requires a mutable array.

e.g.

```
    ErrorResponse: {
      //errors: components["schemas"]["Error"][]; // old way
      errors: ReadonlyArray<components["schemas"]["Error"]>; // new way
    };
```

**Comment by drwpow** [comment]
Interesting! This makes sense to me.

Just for clarification: should _all_ arrays be `Readonly` in TS generation? My gut instinct would be yes, but I’d like to confirm that’s what you’d think.

**Comment by laurence-myers** [comment]
Yes, that'd be my preference. 🙂 But it would depend on the codebase, and
whether it generally uses immutable data. Some apps might want to add items
to an array while building a response, or "pop" items from an input array
(e.g. if it's an intermediate proxy), particularly if performance is a
concern.

Maybe it should be configurable, via CLI option etc.

**Comment by drwpow** [comment]
That’s a fair point. My initial assumption was to treat it as immutable, but now that you say that, I myself have used this library to **generate new structures** before sending to an API (e.g. a `ReadonlyArray<>` would be a pretty bad structure if you were POST-ing something).

I like the idea of a CLI flag that just turns all arrays into `ReadonlyArray<>`. Looking at the OpenAPI spec, I see [readOnly](https://swagger.io/specification/#schemaReadOnly) as a schema option, but reading the description of “it MAY be sent as part of a response but SHOULD NOT be sent as part of the request” makes me think that this is something different than your idea. I think your idea is more of a TypeScript concern than a property of your OpenAPI schema, which makes me think a flag may be best.

**Comment by dnalborczyk** [comment]
I second this. it would be great if we could also make all types immutable, not only arrays.

e.g. [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator) for typescript has an option to generate immutable types: https://graphql-code-generator.com/docs/plugins/typescript

> immutableTypes
> type: boolean default: false
> 
> Generates immutable types by adding readonly to properties and uses ReadonlyArray


```ts
type Foo {
	readonly bar: readonly foobar[]
}
```
