### ISSUE TITLE
Schema handles object with additionalProperties: "true" or "{}" wrongly 

### ISSUE THREAD

**Issue by FabioWanner** [drwpow/openapi-typescript#504]
As per definition https://swagger.io/docs/specification/data-models/dictionaries/  setting additionalProperties to "true" or "{}"
allows the value to be of any type. 

Example: The swagger.json contains something along:

```
"foo": {
    "type": "object",
    "additionalProperties": { },
},
```

openapi-typescript would generate:

```
foo?: { [key: string]: { [key: string]: any } }
```

Expected:
```
foo?: { [key: string]: any }
```

This issue is related to https://github.com/drwpow/openapi-typescript/issues/311.

**Comment by FabioWanner** [comment]
**Addition:** Setting `additionalProperties` to `false` is also handled wrongly. This statement means that no additional properties are in this object, just the ones listed in `properties`. `additionalProperties: false` is the same as omitting `additionalProperties`.

Currently setting `additionalProperties: false` outputs:
```
foo?: { [key: string]: any }
```
That said: having something in the swagger.json like the following with no `properties` or `additionalProperties` is quite pointless since this would represent an empty object only (which we can't represent in typescript right?).
```
"foo": {
    "type": "object",
},
```

Therefore either `properties` or `additionalProperties` or both need to be set when using type `object`.

**Would be nice to discuss the matter as I would plan in some time to fix these issues next week.**

**Comment by drwpow** [comment]
Those are good catches! Thank you. Yes I agree with everything proposed here. Seems straightforward, and I don’t think this would cause any issues for anyone; it would be an improvement.

Yes would love a PR if you’re able to provide one! Of course, tests are very much welcome—they ensure that your feature sticks over time and doesn’t regress with a future change. Also happy to provide any context or answer any questions needed.
