### ISSUE TITLE
"version missing" error for remote resource, vs. no error for resource from file system

### ISSUE THREAD

**Issue by jeffmath** [drwpow/openapi-typescript#505]
When I enter `npx openapi-typescript https://api.development.joinderapp.com/swagger/v1/swagger.json`, I get an error saying `version missing from schema; specify whether this is OpenAPI v3 or v2`, even though the `openapi` field is defined within the top-level object of the swagger.json file.

But, if I download the swagger.json file and then enter `npx openapi-typescript swagger.json`, the types are generated without an error.

**Comment by jeffmath** [comment]
Nevermind, I see now that the problem is caused by the resource in question requiring access to a VPN.  Though, you might consider changing the error message in such cases to indicate that the resource can't be accessed.

**Comment by drwpow** [comment]
Yes it looks like that URL is something I can’t access. But yes, good suggestion! We should improve the error message. Also we should at least support basic authentication. Will add that soon.
