### ISSUE TITLE
Import error with >=3.1.0, with Typescript

### ISSUE THREAD

**Issue by scvnathan** [drwpow/openapi-typescript#519]
Hello,

I'm getting an import error (`node_modules/openapi-typescript/types/index.d.ts' is not a module.`) with versions above 3.1.0 building with Typescript. 3.0.4 and below works fine.

I can push up an example repository if you like, but you can repro this by creating a new package with `openapi-typescript` and `typescript`, building with `tsc`, and just import from `openapi-typescript` in the index file.

Let me know if you need more information

**Comment by drwpow** [comment]
Thanks for reporting. I’ll look into it. We had to change the npm bundling, and I will investigate the error with the TypeScript types. Will push a fix soon; sorry for the inconvenience!

**Comment by scvnathan** [comment]
Thanks!

**Comment by drwpow** [comment]
Should be fixed in `3.1.2`. Please let me know if you have any further problems

**Comment by scvnathan** [comment]
Just tested this out - success! Thanks for the great work @drwpow 👍
