### ISSUE TITLE
Feature request: generate Runtypes code

### ISSUE THREAD

**Issue by codeclown** [drwpow/openapi-typescript#531]
It might be out of scope for this project, but a way to generate Runtypes-code instead of plain types from an OpenAPI spec would be super useful.

[Runtypes](https://github.com/pelotom/runtypes) is great for typing request payloads because it can also validate them in runtime, e.g.

```ts
import { Record, Static } from 'runtypes';
const Foobar = Record({...});
type Foobar = Static<typeof Foobar>;
app.post('/foobar', (req, res, next) => {
  const body: Foobar = Foobar.check(req.body);
  // body is of type Foobar
});
```

**Comment by drwpow** [comment]
This is an interesting suggestion, thank you! I have a feeling that the easiest path to this would possibly to generate Runtypes code from the final TypeScript output of this library. Would that be possible?

**Comment by codeclown** [comment]
It would feel a bit backwards since typically you derive the TS types from Runtypes via `Static<typeof RuntypeType>`. So now you'd have OpenAPI->TS->Runtypes+TS, whereas the feature request would allow for: OpenAPI->Runtypes+TS

But again I understand that implementing this functionality to openapi-typescript might very well not be worth it (added complexity and maintenance burden vs. benefit).

Then again, making a brand new tool with almost identical functionality, just different output format, simply feels a bit overlapping.

(Btw if anyone lands here looking for a way to validate schema in runtime, a suitable tool to use along with openapi-typescript is [express-openapi-validate](https://github.com/Hilzu/express-openapi-validate)).

**Comment by drwpow** [comment]
Ah, got it. Yeah that would basically be a complete library rewrite 😅. I don’t really have the ability to take that on at the moment, and I’m also unfamiliar with Runtypes’ TypeScript compiler too. But if this is something you‘re interested in making yourself I’d be happy to contribute and am happy to tell you everything I know about OpenAPI type generation.

**Comment by cobraz** [comment]
I plan to create this! In preparations to this I built [generate-runtypes](https://github.com/cobraz/generate-runtypes).

I am still trying to find the easiest way, and would be happy to either contribute to this library or join up with someone!

**Comment by cobraz** [comment]
Hey again!

I started to do a write-up figuring out what to do next. If anyone would be interested, I'd love to get some feedback on this: https://gist.github.com/cobraz/a0031905833bc58d233451fe537f3019

**Comment by nponeccop** [comment]
What about `io-ts`? Is `runtypes` a competitor of `io-ts`? `io-ts` seem to have a pretty large infrastructure.

**Comment by cobraz** [comment]
> What about `io-ts`? Is `runtypes` a competitor of `io-ts`? `io-ts` seem to have a pretty large infrastructure.

`io-ts` is an alternative to `runtypes`, and they are competitors.

**Comment by drwpow** [comment]
Thanks for the suggestion! In order to clean up old issues on this library, I’m going to say that this is out-of-scope for this library for now.
