### ISSUE TITLE
Property 'schema' does not exist on type 'components'

### ISSUE THREAD

**Issue by andrenarchy** [drwpow/openapi-typescript#553]
I get the error `Property 'schema' does not exist on type 'components'` from typescript and it seems in the generated ts file `'schema'` needs to be replaced with `'schemas'`:

```typescript
// ...
content: {
  'application/json': {
    data?: components['schema']['ItemsSerialMscs'][]
  }
}
// ...
```

**Comment by andrenarchy** [comment]
After some more investigation I think this is actually an error in the OAS JSON (coming from the Directus 9 API).

**Comment by drwpow** [comment]
OK. Please report back if you find an error with a library.

This library’s goal is to trust the spec its given, and assume it’s already been validated. So if it encounters `$ref: "#/schema/ItemsSerialMscs"` it will transform it into what you see above rather than throw an error.
