### ISSUE TITLE
Error: Couldn't resolve parser "typescript". Parsers must be explicitly added to the standalone bundle.

### ISSUE THREAD

**Issue by lie5860** [drwpow/openapi-typescript#556]
like https://github.com/prettier/prettier/issues/6264
Add plugin in the source code to solve the problem.

**Comment by lie5860** [comment]
try to use options.prettierConfig,but show ❌ TypeError: Cannot read property 'sync' of undefined

**Comment by drwpow** [comment]
That’s good to know! Thank you I will fix.
