### ISSUE TITLE
Generate typings from any JSON schema

### ISSUE THREAD

**Issue by codeclown** [drwpow/openapi-typescript#571]
It would be really useful if openapi-typescript would support generating typings from any JSON schema specification, not necessarily an OpenAPI spec with endpoints etc.

For example, with Helm charts it's possible to define a simple `values.schema.json` file which Helm will then use to validate variable values at runtime. This is just one example of where one might have a JSON schema spec that's not an OpenAPI spec.

Would this be possible to implement? Would you accept a PR if so?

---

## Steps to reproduce

1. Save a basic JSON schema in file `values.schema.json`:

```json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "required": [
    "image"
  ],
  "properties": {
    "image": {
      "type": "object",
      "required": [
        "repository",
        "pullPolicy"
      ],
      "properties": {
        "repository": {
          "type": "string",
          "pattern": "^[a-z0-9-_]+$"
        },
        "pullPolicy": {
          "type": "string",
          "pattern": "^(Always|Never|IfNotPresent)$"
        }
      }
    }
  }
}
```

2. Run openapi-typescript:

```bash
npx openapi-typescript values.schema.json --output schema.ts
```

## Expected results

openapi-typescript would create file `schema.ts` with typings of the specified schema.

## Actual results

```
npx: installed 72 in 6.314s
✨ openapi-typescript 3.2.3
🔭 Loading spec from values.schema.json…
Error: 🚏 version missing from schema; specify whether this is OpenAPI v3 or v2 https://swagger.io/specification
    at Object.swaggerVersion (/Users/martti/.npm/_npx/21878/lib/node_modules/openapi-typescript/dist/cjs/utils.js:57:11)
    at swaggerToTS (/Users/martti/.npm/_npx/21878/lib/node_modules/openapi-typescript/dist/cjs/index.js:31:61)
    at main (/Users/martti/.npm/_npx/21878/lib/node_modules/openapi-typescript/bin/cli.js:75:18)
```

**Comment by drwpow** [comment]
I don’t see why we couldn’t support this! Because OpenAPI is based on JSON schema this seems like a natural fit. And yes I’d be open to a PR adding this.

**Comment by LironHazan** [comment]
I'd tried to utilize another tool for that but I'm not 100% sure it currently fits the need, the output is as follows:

```
export interface Simple {
  image: {
    repository: string;
    pullPolicy: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
```
I named the "values.schema.json" file as simple.json and it created the above type, I'll try to look into it a bit deeper.

**Comment by LironHazan** [comment]
@codeclown @drwpow I hope it's ok I joined in, I have a use case in which I'm checking the ability of using openapi-typescript but I also need an option of creating types from plain jsons which lead me into looking for a way of generating json-schema of a plain json and into this thread,

I looked into another json-schema-to-types generator called dtsgenerator, it seem to work fine with the [example](https://github.com/horiuchi/dtsgenerator/blob/master/test/snapshots/json-schema-draft-04/advanced-example/advanced_example.json)  I included on this PR -->  LironHazan:571-dtsgenerator
But it didn't played nice with values.schema.json

LMKWYT \m/

**Comment by drwpow** [comment]
Update: since [json-schema-to-typescript](https://www.npmjs.com/package/json-schema-to-typescript) exists, I’d recommend people use that project instead. I think for now, this project should limit itself to only the OpenAPI spec.
