### ISSUE TITLE
additionalProperties is not correctly defaulted to true

### ISSUE THREAD

**Issue by mehalter** [drwpow/openapi-typescript#583]
I am running into an issue where some of my openapi specifications are not generating to the correct typescript object because they do not include the `additionalProperties`. According to the OpenAPI specification this is default to true (https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md):

> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties defaults to true.

With this being the case, shouldn't it automatically add the union with `& { [key: string]: any }` unless `additionalProperties` is set to something else i.e. a schema or `false`?

When I run the following openapi definition:

```
{
    "openapi": "3.0.0",
    "info": {
        "title": "Generated by cue.",
        "version": "no version"
    },
    "paths": {},
    "components": {
        "schemas": {
            "Blueprint": {
                "$ref": "#/components/schemas/Contract"
            },
            "Contract": {
                "type": "object",
                "required": [
                    "slug"
                ],
                "properties": {
                    "slug": {
                        "type": "string"
                    }
                }
            }
        }
    }
}
```

I get the typescript:

```
export interface paths {}

export interface components {
	schemas: {
		Blueprint: components['schemas']['Contract'];
		Contract: {
			slug: string;
		};
	};
}

export interface operations {}
```

where it should be `Contract: { slug: string; } & { [key: string]: any }`

Thanks for your help and all the work put into this project!

**Comment by mehalter** [comment]
Also to note this only seems to be a part of OpenAPI 3 and not OpenAPI 2

**Comment by mikehalmamoj** [comment]
Hmmm is this right?  It also says: `This object cannot be extended with additional properties and any properties added SHALL be ignored.` (https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#fixed-fields-19)

Admittedly I'm just sulking because my linter doesn't like `any` :smile:

**Comment by drwpow** [comment]
> Hmmm is this right? It also says: `This object cannot be extended with additional properties and any properties added SHALL be ignored.`

Yeah this behavior should be behind a flag. I’m not sure which should be the default behavior, but it should be controllable. I’m kinda leaning toward the `& { [key: string]: any }` as the default, just because it’s more lenient / probably works for more people, but don’t feel strongly.

**Comment by mikehalmamoj** [comment]
As we're in control of the server side too, I think we'll probably set that additionalProperties flag to false.  It's strange to default to true though - "Here is my contract (but I might stick a bunch of random properties on the end if I feel like it)" - that's not my idea of a contract :smile: 

+1 for putting this behaviour behind a flag.  Agree you should be more lenient with the default.

**Comment by drwpow** [comment]
> It's strange to default to true though - "Here is my contract (but I might stick a bunch of random properties on the end if I feel like it)" - that's not my idea of a contract 😄

Phrasing it like that, perhaps it is better default off. It may be something that people aren’t expecting, and may bite them if they’re not aware of it. OK I’ll do that—introduce the flag, then make the default behavior what it used to be before this last release. That shouldn’t be too disruptive seeing as this is relatively new, and you can always opt in if needed.
