### ISSUE TITLE
Property values with defaults are being incorrectly typed as possibly undefined when they shouldn't be.

### ISSUE THREAD

**Issue by rustyconover** [drwpow/openapi-typescript#584]
Hi Team,

Thank you for a great module.

It seems the logic in the link below is insufficient to handle if a property able to be defined or undefined.

https://github.com/drwpow/openapi-typescript/blob/4c51afc45f449943bc9e2c58639606b15aaa88b8/src/transform/parameters.ts#L58

If a property isn't required in an object but that property has a default value specified, that property will never be undefined.  See the docs at:

https://swagger.io/docs/specification/describing-parameters/

Rusty

**Comment by mehalter** [comment]
This was accidentally mentioned in the above PR, sorry for the confusion!

**Comment by rustyconover** [comment]
Okay I was just looking at the diff and it didn't make sense.

**Comment by rustyconover** [comment]
I have a partial fix but I can't figure out how to resolve the refs at runtime.

**Comment by rustyconover** [comment]
I'm unsure of how to call

```
unrefComponent(components: any, ref: string): any 
```

in ```transformParametersArray```

**Comment by gr2m** [comment]
@drwpow #613 marked types for request parameters as required if they have a default value, but that is not correct, I think the change should only apply to response types. I'm looking into it

**Comment by rustyconover** [comment]
@gr2m Please see my comment: https://github.com/drwpow/openapi-typescript/pull/613#issuecomment-850342706

**Comment by drwpow** [comment]
This is now supported, though it must be enabled with the `--default-non-nullable` flag. This may be unexpected (unsafe) behavior for those not expecting it, but users are still able to opt in.
