### ISSUE TITLE
Path not decoded

### ISSUE THREAD

**Issue by glen-84** [drwpow/openapi-typescript#587]
Given the following input (from a spec bundled with swagger-parser):

```json
"/tournaments/{id}/player-registrations": {
    "$ref": "#/paths/~1tournaments~1%7Bid%7D~1register~1player"
}
```

The resulting TS looks like this:

```ts
  "/tournaments/{id}/player-registrations": paths["~1tournaments~1%7Bid%7D~1register~1player"];
```

With the error: `Property '~1tournaments~1%7Bid%7D~1register~1player' does not exist on type 'paths'.`.

The spec is considered valid, but I'm still not 100% sure whose responsibility it is to decode the path (swagger-parser or this project).

**Comment by drwpow** [comment]
That is valid as you say, but it seems that it’s being transformed correctly at least as far as `openapi-typescript` can do. We wouldn’t have any way of knowing whether or not that needed transforming; after all some people may want the `%` signs in their final types and transforming this for you may break others’ schema.

I believe this is an issue with `swagger-parser`, or this is something you could fix by decoding symbols in your schema before running `openapi-typescript`.

A little tip: most people don’t know that there’s a great transformer built in to JS! It’s called the [JSON.parse() reviver](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#using_the_reviver_parameter). Using this, you can take a JSON-compatible structure like an OpenAPI spec, and transform only the parts you want to, with vanilla JS and no libraries ([example of using JSON.parse reviver](https://gist.github.com/drwpow/37d65f87501d05af4e1372511e0d32e4)). Not saying you have to do this, but just trying to spread the word that changing values deep within a nested JSON object can be easier than people realize 🙂

**Comment by glen-84** [comment]
I was about to submit an issue to swagger-parser, but on further thought, I don't think that this is actually a bug with that tool.

`#/paths/~1tournaments~1%7Bid%7D~1register~1player` is a valid ref, and `#/paths//tournaments/{id}/register/player` would _not_ be valid, so there's nothing that swagger-parser can do in this regard.

I'm thinking that openapi-typescript should probably use something like [json-ptr](https://github.com/flitbit/json-ptr) when dealing with references:

```js
JsonPointer.decode("#/paths/~1tournaments~1%7Bid%7D~1register~1player");
// ["paths", "/tournaments/{id}/register/player"]

JsonPointer.decode("#/paths/nothing/to/decode");
// ["paths", "nothing", "to", "decode"]
```

I understand that I could preprocess the spec (and I appreciate the detailed suggestion), but in my opinion it should probably be handled by openapi-typescript.

**Comment by drwpow** [comment]
Ah thanks for explaining. I didn’t realize the encoding was necessary like you said. In that case I would be on board for seeing what it would take to decode `$refs`s and nothing else, so long as nothing else is transformed.

We’ll also have to see if this would disrupt anyone, and make sure this would still allow the same characters in schema names as before. If so, I’m on board.

Would you be interested in submitting a PR for this with a test?

**Comment by glen-84** [comment]
The tests don't run on Windows, which makes it quite difficult to work on this.

**Comment by glen-84** [comment]
This appears to work, but since I'm unable to run the tests, I cannot confirm:

Run: `npm i json-ptr`.

In `src/utils.ts`:

```diff
+import { JsonPointer } from "json-ptr";

// ...

/** Convert $ref to TS ref */
-export function transformRef(ref: string, root = ""): string {
+export function transformRef(ref: string): string {
  // TODO: load external file
  const isExternalRef = !ref.startsWith("#"); // if # isn’t first character, we can assume this is a remote schema
  if (isExternalRef) return "any";

-  const parts = ref.replace(/^#\//, root).split("/");
+  const parts = JsonPointer.decode(ref);
  return `${parts[0]}["${parts.slice(1).join('"]["')}"]`;
}
```

Let me know if you'd like me to open a PR with these changes.

**Comment by drwpow** [comment]
I believe this should be handled in [#602](https://github.com/drwpow/openapi-typescript/pull/602/files#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R101) with the addition of remote schemas (I had to touch a lot of $ref-related code for this). After that lands, I can add a test to make sure we’re decoding the $refs properly.

**Comment by drwpow** [comment]
This should be fixed as of `v4` of this library. Going to close pre-emptively, but reopen if you encounter any issues.

**Comment by glen-84** [comment]
With v4 the output looks like this:

```json
  "/tournaments/{id}/player-registrations": paths["/tournaments/%7Bid%7D/register/player"];
```

So the slashes are decoded, but nothing else.

I've switched to using [dtsgenerator](https://github.com/horiuchi/dtsgenerator), so a fix for this issue is not a high priority from my side.
