### ISSUE TITLE
Issue with property referencing sibling property

### ISSUE THREAD

**Issue by glen-84** [drwpow/openapi-typescript#588]
Given the following input (from a spec bundled with swagger-parser):

```jsonc
"Achievements": {
    "title": "Achievements",
    "type": "object",
    "properties": {
        "online": {
            "type": "array",
            "items": {
                "title": "Achievement",
                "type": "object",
                "properties": {
                    // ...
                }
            }
        },
        "offline": {
            "type": "array",
            "items": {
                "$ref": "#/components/schemas/Achievements/properties/online/items"
            }
        }
    }
}
```

The resulting TS looks like this:

```ts
Achievements: {
  online?: {
    // ...
  }[];
  offline?: components["schemas"]["Achievements"]["properties"]["online"]["items"][];
};
```

With the error: `Property 'properties' does not exist on type '{ online?: { /* ... */ }[]; offline?: any; }'.`

**Comment by drwpow** [comment]
No not at all! I am working on improvements to `$ref`s including remote schemas soon, so I will keep this in mind. I’m sure that there’s some `$ref` support we could improve overall.

I think I will close the issue just for focus, but again, will keep thinking about this and see if there are some more advanced `$ref` cases we need to support. Thank you for opening the issue!
