### ISSUE TITLE
Extending generated schema types

### ISSUE THREAD

**Issue by tweakster** [drwpow/openapi-typescript#592]
Hi,

Is it possible to use the type for specific schemas and extend them?

For example...

Part of a generated file
```
interface components {
  schemas: {
    Country: {
      id: number;
      name: string;
    };
  }
}
```

Then in my code I want to do something like
```
import { components } from './openapi'

interface CountryButton extends components['schemas']['Country'] {
  selected: boolean;
}
```
But this is generating an error:
```
error TS2499: An interface can only extend an identifier/qualified-name with optional type arguments.
```
My understanding is you cannot extend these as they are expressions (https://github.com/microsoft/TypeScript/issues/31843)

Is there any way around this issue?

**Comment by glen-84** [comment]
There is [a solution](https://github.com/microsoft/TypeScript/issues/31843#issuecomment-509686998) in the issue that you linked to: create a simple type alias. [Example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgQewLYAc0guAZ2QG8AoZZAhACwgzgIC4TyLkBhNAV3CgE9mZNm2AATZiC4YARtADcrYSDgYIzAmCigA5guEBfPcn2kTpMHywpOPTX2QBeVJhx5CAbQDkVWvQKeAXS8bXj5AhVJQSFhEa25QgCEuMDBcZAgAD0gQUSIQuxYKAggAGwgESHFkaTQ0MrgQBTN0EA1nW34klNxmfM7k1JBHQuQxZgBGABpWZVVmTwBRDJUsMs9potLyyuZNLghTUiA).
