### ISSUE TITLE
`required` properties are not respected when they are missing from `properties`

### ISSUE THREAD

**Issue by shuluster** [drwpow/openapi-typescript#619]
Example schema
```
type: object
properties: 
  email: 
    type: string
required: ["user"]
```
should generate a type that requires `user` to be present. Today it generates a type with only `email` being the optional argument.

This is part of spec and commonly used for when reusing an object and making optional fields required, for example

```
LogInReq:
  type: object
  allOf: 
    - $ref: '#/someCommonObject' 
    - type: object
       required: ["user", "password"]
```

`LogInReq` now requires `user` and `password` to be present while all other fields in `someCommonObject` to be their default setting.

Working on a PR.

This will change a lot of behavior for the library and curious about people's thoughts.

**Comment by drwpow** [comment]
This is interesting. I can’t say I’ve used this before, but I don’t see a problem with adding this. Will check out the PR, thanks!
