### ISSUE TITLE
Bug: Headers that use refs aren't included in output

### ISSUE THREAD

**Issue by rustyconover** [drwpow/openapi-typescript#624]
Hi there,

If a header is specified as a reference (i.e. as part of a response) the header isn't included in the produced objects.

An example response schema is:
```json
"responses": {
    "200": {
    "content": {
        "application/json": {
        "schema": {
            "$ref": "#/components/schemas/Result_Ok_GetGroups"
        }
        }
    },
    "description": "OK",
    "headers": {
        "ETag": {
        "$ref": "#/components/headers/ETag"
        }
    }
}
```

That would produce a type with:

```typescript
200: {
    headers: {};
    content: {
        "application/json": components["schemas"]["Result_Ok_GetGroups"];
    };
}
```

The reason is because of the check:

https://github.com/drwpow/openapi-typescript/blob/e2fb371f053c90af4d958c48b7b6b04271b257ca/src/transform/headers.ts#L17

`v.schema` won't be defined because the header is included by reference.

Properly handling the headers relies on resolving the reference (even if it is external).

Since the majority of my PR has not been merged that deals with resolving references, I'm going to just link to the commit that fixes this problem:

https://github.com/rustyconover/openapi-typescript/commit/9c2186448ce3c3c1c521da6d2d8ac15cf8bc1fc1

Please feel free to cherry pick.

Rusty

**Comment by njanor** [comment]
Hi,

This is an exact issue we're running into in our project currently. Will this be resolved at any time?

I've tried to have a look at the related issue (#586), but this seems to be something that can be included without the challenges presented and discussed in that issue.

**Comment by nsb** [comment]
Just hit the same issue.
