### ISSUE TITLE
Schema properties with default considered required

### ISSUE THREAD

**Issue by agualis** [drwpow/openapi-typescript#664]
This [line](
https://github.com/drwpow/openapi-typescript/blob/c681d24247615bf6def82957af2f6f00a0dcf167/src/transform/schema.ts#L27) assumes that a property is `required` when it has a `default` value. 

According to the [specification](https://swagger.io/specification/):

> default - The default value represents what would be assumed by the consumer of the input as the value of the schema if one is not provided. Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object defined at the same level. For example, if type is string, then default can be "foo" but cannot be 1.

So, my understanding is that: 

- When the consumer is reading the value will always have a value (`required`)
- But, when the consumer is writing  the value can be provided or not so that **the generated type should also be optional instead of required**

Am I missing something?

Thanks for your great library!

**Comment by drwpow** [comment]
This is no longer true! Now we give you the option. The default command will **only treat `required` as non-nullable**. But if you specify the `--default-non-nullable` flag as well, then it will respect **either `required` or `default` as non-nullable**. That’s the `options.defaultNonNullable &&` part). Hopefully this clarifies things!
