### ISSUE TITLE
Bug: Including additionalProperties map when the schema is just oneOf/anyOf/allOff

### ISSUE THREAD

**Issue by rustyconover** [drwpow/openapi-typescript#665]
It seems that emitting the additionalProperties `{ [name: string]: any}` when the schema node just has oneOf/anyOf/allOf is a bit too lax.

Please see the fix at:

https://github.com/rustyconover/openapi-typescript/commit/dd38fbcd5c395933f37d6177b94ea58472a9440c

**Comment by drwpow** [comment]
I’m not sure if this is no longer the case. Since this issue was opened we’ve added tests that reduce the appearance of `{ [name: string]: any }` types with `additionalProperties`. If I’m missing an example, please open a PR or produce a failing test!
