### ISSUE TITLE
Generated schema shows type of input file as string and not as File

### ISSUE THREAD

**Issue by jd-0001** [drwpow/openapi-typescript#733]
Hi,

I have the following schema:

![Screenshot from 2021-08-30 18-42-49](https://user-images.githubusercontent.com/47495003/131344621-b3e78e4a-9a4a-42ab-827f-b8d2e0b1b891.png)

This generates below:

```ts
uploaded_file?: string;
```

Isn't it should create below?

```ts
uploaded_file?: File;
```

Regards.

**Comment by drwpow** [comment]
According to your schema, the `type` is `string`, so I think this is correct. There’s no such thing as a `File` type that either Node.js or the browser would understand.

If you’d like to set your own custom type, you can always use the [custom formatter](https://github.com/drwpow/openapi-typescript#custom-formatter) as indicated in the README.

**Comment by jd-0001** [comment]
Thanks for response.
What should be API schema to generate `uploaded_file` as File. This is because I want to define type for HTML file input.

Regards.
