### ISSUE TITLE
Is there a way to only get the `definitions` output?

### ISSUE THREAD

**Issue by baptisteArno** [drwpow/openapi-typescript#741]
I'd like to ignore `paths`, `parameters`, `operation`, `external` interfaces. Is it possible?

Here is my current script:

```ts
import fs from "fs";
import openapiTS from "openapi-typescript";
import path from "path";

const updateTypes = async () => {
  const openapiUrl = `...`;
  const output = await openapiTS(openapiUrl, {
    formatter: (node) => {
      console.log(node);
      if (node.format === "jsonb") {
        return "unknown";
      }
      if (node.format === "ARRAY") {
        return `${node.type}[]`;
      }
      if (node.format === "timestamp with time zone") {
        return `string | Date`;
      }
    },
  });

  fs.writeFileSync(path.join("src", "models", "dto.ts"), output);
};

updateTypes();
```

**Comment by drwpow** [comment]
No, and I’d rather not support this. It’s my personal opinion that `import { paths } from '[myschema].ts'` should never throw a type error, no matter what schema you’re using and no matter how the schema contents change. I like to think of the interface namespaces almost as an API—they should always be present. It’s their type keys that are subject to change across schemas and contents, but the wrapper should always be importable.
