### ISSUE TITLE
Required values

### ISSUE THREAD

**Issue by andreyvital** [drwpow/openapi-typescript#758]
Hey folks, how's it going?

I'm using this project to generate types from https://github.com/apache/airflow/blob/main/airflow/api_connexion/openapi/v1.yaml. But I couldn't figure out how to make the properties required as per in their schema.

Currently, it outputs:

```TS
/**
 * DAG details.
 *
 * For details see:
 * (airflow.models.DAG)[https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/index.html#airflow.models.DAG]
 */
DAGDetail: components["schemas"]["DAG"] & {
  timezone?: components["schemas"]["Timezone"];
  catchup?: boolean;
  orientation?: string;
  concurrency?: number;
  start_date?: string | null;
  dag_run_timeout?: components["schemas"]["TimeDelta"] | null;
  doc_md?: string | null;
  default_view?: string;
  params?: { [key: string]: unknown };
};
```

Notice all properties being optional—which makes very annoying to use those types. I am not 100% sure if it's a problem on the schema or if there's a flag that has to be passed when generating the types.

Thoughts? _(Sorry if duplicate, btw)_

**Comment by drwpow** [comment]
This follows the OpenAPI spec in that all properties are considered optional unless a `required: []` array is given.

```yaml
type: object
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
required:
- name
```

https://swagger.io/specification/#schema-object

Hope this answers your question!

**Comment by simondotm** [comment]
Thanks for asking this question, I had a similar issue with all properties output as optional - in my case the problem was that I had the `required` field in my YAML file at the wrong indentation level! 🤦 Just leaving a note here for any future devs.
