### ISSUE TITLE
Emit operationId for operations

### ISSUE THREAD

**Issue by ajaishankar** [drwpow/openapi-typescript#776]
It will be helpful if **operationId** is emitted for an operation object.

When navigating via paths it will give a quick hint to the user on what a variable should be named.

![operationId](https://user-images.githubusercontent.com/328008/136802347-22e7afb0-e044-4886-9a0e-9cf363313a7d.png) 

Looks like an one line code change, but not sure the process to fix the tests
```diff
 export function transformOperationObj(operation: OperationObject, options: TransformOperationOptions): string {
   const { pathItem = {}, globalParameters, ...ctx } = options;
   const readonly = tsReadonly(ctx.immutableTypes);
 
-  let output = "";
+  let output = operation.operationId != null ? `  operationId: "${operation.operationId}";\n` : "";
```

**Comment by ajaishankar** [comment]
Closing since VSCode already shows the operation name once you CMD+Click on the operation.

![starRepo](https://user-images.githubusercontent.com/328008/136805039-621a6f78-0713-4459-9559-c678ad05364b.png)

**Comment by shinzui** [comment]
Is it possible to reopen? The `operationId` would help me when generating a client.
