### ISSUE TITLE
import error with node12 modules

### ISSUE THREAD

**Issue by dcharbonnier** [drwpow/openapi-typescript#847]
```
node_modules/openapi-typescript/dist/esm/index.d.ts:2:75 - error TS2835: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node12' or 'nodenext'. Did you mean './types.js'?

2 import type { OpenAPI2, OpenAPI3, SchemaObject, SwaggerToTSOptions } from "./types";
```

**Comment by drwpow** [comment]
Which version are you using? The most recent breaking version drops support for Node 12 in the interest of adopting the new standard of ESM support: https://github.com/drwpow/openapi-typescript/releases/tag/v5.0.0

**Comment by dcharbonnier** [comment]
nothing to do with the nodejs version, I'm using node 16 but the module resulution is called node12 or nodenext
https://www.typescriptlang.org/docs/handbook/esm-node.html

> relative import paths need full extensions (we have to write import "./foo.js" instead of import "./foo")

**Comment by drwpow** [comment]
Ah I see. OK this sounds like a bug with our generated types. ESM does require full extensions or `import type`.

**Comment by drwpow** [comment]
This should be fixed in the latest patch version. Please let me know if it’s not!
