### ISSUE TITLE
missing type definitions for cjs

### ISSUE THREAD

**Issue by alumni** [drwpow/openapi-typescript#855]
It looks fine for ESM, but TypeScript complains that the type definitions for commonjs are missing.

**Comment by drwpow** [comment]
@alumni which version are you using? I recently released a breaking change for this reason.

**Comment by alumni** [comment]
`4.5.0` is fine, `5.0.0` is not. In version v4.5 there are type definitions in `dist/cjs`, but in v5 there's only one file `index.cjs`:

- https://cdn.jsdelivr.net/npm/openapi-typescript@4.5.0/dist/cjs/
- https://cdn.jsdelivr.net/npm/openapi-typescript@5.0.0/dist/cjs/

If commonjs is not supported at all anymore, I would expect no cjs folder, but if it still is, I would expect to have the type definitions there as well.

**Comment by alumni** [comment]
The types are now fine but `index.cjs` is trying to import `node-fetch` which is an ESM-only package:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module <root>/node_modules/openapi-typescript/node_modules/node-fetch/src/index.js from <root>/node_modules/openapi-typescript/dist/cjs/index.cjs not supported.
Instead change the require of index.js in <root>/node_modules/openapi-typescript/dist/cjs/index.cjs to a dynamic import() which is available in all CommonJS modules. 
```

**Comment by drwpow** [comment]
I’m curious if it is possible to manually-install the previous version of `node-fetch` that’s CJS. But that experience/setup isn’t great IMO. I think at this point it is probably best to remove CJS. `5.0` was already a breaking change from CJS -> ESM; perhaps CJS should just be dropped a la [Sindre Sorhus](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77).
