### ISSUE TITLE
Expected Object but got Array

### ISSUE THREAD

**Issue by KevinGregull** [drwpow/openapi-typescript#860]
There seems to be an Issue here:
https://github.com/drwpow/openapi-typescript/blob/fec06c651fbea622e7837eda7067971f4f58d33c/src/utils.ts#L114
----

```json
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "items": {
                        "$ref": "#/components/schemas/ItemsCompanyGroup"
                      }
                    }
                  }
                }
              }

```

I have a Doc JSON that looks like this and is supposed to return a single JSON Object not an array, the content inside Data looks like this on the real API: `{"id":"f1d16572-75e4-4e77-ba26-585b9406b3cd","name":"Test"}`

And to me that seems to be correctly reflected in the JSON. But because it contains items, it is currently parsed as an Array and its actual generated type is:
```typescript
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["ItemsCompanyGroup"][];
          };
        };
      };
```

**Comment by drwpow** [comment]
Is your schema valid according to OpenAPI’s validator? I’m not aware of being able to use `items` in conjunction with `type: 'object'`
