### ISSUE TITLE
Feature request: output an enum of paths

### ISSUE THREAD

**Issue by berzi** [drwpow/openapi-typescript#873]
It would be very helpful to reduce duplication and have just a little bit more type safety if openapi-typescript would generate (perhaps optionally, behind a flag) an enum or object containing the API paths for each operation, so that one wouldn't have to write them down by hand or copy them manually from the spec when needing to use the paths in code.

This would help having the API spec as a single source of truth and would eliminate the need to keep paths in sync if the spec changes.

**Comment by drwpow** [comment]
I think this is a good idea. Do you have a simple example of what you think the output would look like?

Also, as much as I like TS enums, I do lean toward discriminated union types (`'GET' | 'POST'`) because when you’re receiving untyped data from an API I’ve found it much easier to coerce untyped strings to them. But regardless of implementation, +1 to the concept.

**Comment by berzi** [comment]
A discriminated union would allow one to type-safely input one of the API paths and get autocomplete for them, but you'd still have to tell TS that a certain string should really be one of the constants from that type. You can already do that (if a bit clumsily) by using `keyof paths`, but it would still mean having to go through the trouble of explicitly annotating something that is often used as a string literal.

The advantage of an Enum would be to have a direct connection between TS typing and JS content.

```typescript
// apiTypes.ts

export interface paths {
  "/api/v1/bananas": {
    // ...
  },
  "/api/v1/apples": {
    // ...
  },
}

export enum ApiPaths {
  GetBananas = "/api/v1/bananas",
  GetApples = "/api/v1/apples",
  PutApples = "/api/v1/apples",
}
```

```typescript
// myApp.ts

const bananas = await fetch(ApiPaths.GetBananas)

// compare that with:
const bananasPath: keyof paths = "/api/v1/bananas"
const bananas = await fetch(bananasPath)
```

I'm open to better options here, but I think enums are the right tool for the job in this case.

I believe it would be appropriate to have the keys of the enum equal those from `operations` (they will all be unique, right?) and the values those from `paths`.

I wonder if parameters, which in keys are shown like: `/api/url/{parameter}` should be converted in any way, like to `/api/url/:parameter` or anything of the sort.

**Comment by berzi** [comment]
I'm currently working on this feature myself. :)
