### ISSUE TITLE
Error:  expected to be of type CommonJS, which does not support named exports

### ISSUE THREAD

**Issue by marc-on-github** [drwpow/openapi-typescript#874]
Hello, I got an error if I run this command:
"npx openapi-typescript https://your-project.supabase.co/rest/v1/?apikey=your-anon-key --output types/database/index.ts"

That's the error:

npx: Installierte 10 in 3.556s
file:///Users/marc/.npm/_npx/64596/lib/node_modules/openapi-typescript/dist/load.js:1
import { request } from "undici";
         ^^^^^^^
SyntaxError: The requested module 'undici' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'undici';
const { request } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
error Command failed with exit code 1.

Can somebody help me, please?

**Comment by drwpow** [comment]
This is likely a bug. Will fix!

**Comment by drwpow** [comment]
This seems to be working on Node 16, but I’ll push a fix that will hopefully work for more versions. What version of Node are you on, by the way?

**Comment by RomainGuarinoni** [comment]
I have the same problem: 

I have a file in my project where I need to import the `openApiTS` function from `openapi-typescript` like this: 

```ts
import openApiTS from 'openapi-typescript';
```

And when i try to run my project, here is the error it gives me : 

```sh
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/rguarinoni/Documents/findAMusician/findAMusicianBackend/node_modules/openapi-typescript/dist/index.js
require() of ES modules is not supported.
require() of /home/rguarinoni/Documents/findAMusician/findAMusicianBackend/node_modules/openapi-typescript/dist/index.js from /home/rguarinoni/Documents/findAMusician/findAMusicianBackend/api/command/generateType.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/rguarinoni/Documents/findAMusician/findAMusicianBackend/node_modules/openapi-typescript/package.json.

```

I'm using node 16.2.0 btw

**Comment by drwpow** [comment]
This is likely an error with your TypeScript setup. You’ll need the following in tsconfig.json:

```json
{
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "Node"
  }
}
```

Also consider adding `{ "type": "module" }` to the top level of your `package.json` to switch Node to ESM by default.
