### ISSUE TITLE
Syntax error when enum in a Schema Object is a list of objects

### ISSUE THREAD

**Issue by denniskloyn** [drwpow/openapi-typescript#876]
If a Schema Object `enum` contains a list of objects (instead of—more commonly—a list strings) an error is thrown: `SyntaxError: '=>' expected.` This error message looks similar to the one in bug #561.

Note that an `enum` in a schema object may contain a list of anything. As per https://swagger.io/specification/#schema-object `enum` “[is] taken directly from the JSON Schema definition and follow[s] the same specifications”. The JSON Schema definition, https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-5.20, says that “Elements in the array MAY be of any type, including null.”

**Comment by rkulinski** [comment]
I think I'm experiencing the same issue but with different error:
```
 /** @enum {array} */
> 2448 | "_entity": [object Object];

````

It seems like this library has a bug when reading `enum`

**Comment by xiaoyu-tamu** [comment]
experencing the same issue when parsing  `mailchimp openapi spec`,

```
  {
            "in": "query",
            "name": "activity_filters",
            "x-title": "Activity Filters",
            "type": "array",
            "required": false,
            "items": {
              "type": "string"
            },
            "collectionFormat": "csv",
            "enum": [
              [
                "bounce"
              ],
			 // other options removed
            ],
            "description": "A comma-separated list of activity filters that correspond to a set of activity types, e.g \"?activity_filters=open,bounce,click\"."
          }
```

The generated enum value miss quotes.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/33362998/156386390-2f247e36-c293-4235-93fb-3d0c46d42d94.png">

**Comment by Gankarloo** [comment]
I'm facing the exact same issue as @Leafgard

**Comment by drwpow** [comment]
This definitely seems like a bug. If someone is able to create a PR to fix this (with tests) I’d be happy to merge & release

**Comment by MartinN3** [comment]
Same issue on docker api https://docs.docker.com/engine/api/v1.41/

**Comment by drwpow** [comment]
This has been added in the upcoming v6 version (#968). Closing in anticipation of that, but once that’s launched, if there are any issues please file additional bugs.
