### ISSUE TITLE
Support for .env files in CLI

### ISSUE THREAD

**Issue by Moortiii** [drwpow/openapi-typescript#884]
**Proposition:**

Add support for reading in environment variables from `.env` files when using the CLI tool.

**Use case:**

Allow users to read in auth tokens, schema URLs and more from environment variables without using `openapi-typescript` programatically.

**Example:**

```bash
// .env
ACCESS_TOKEN=very_secret_token
OPENAPI_SCHEMA_URL=http://localhost:5000/openapi.json
```

Command:

`npx openapi-typescript $OPENAPI_SCHEMA_URL --output src/schema.ts --header "Authorization: Bearer $AUTH_TOKEN"`

Command after preprocessing:

`npx openapi-typescript http://localhost:5000/openapi.json --output src/schema.ts --header "Authorization: Bearer very_secret_token"`

I could probably create a PR for this myself, if you would be willing to accept this feature.

**Comment by visormatt** [comment]
@Moortiii A good workaround for the time being so that we don't have commit these values and keep it in the `.env` is to throw a little bash script in between the two 🤷 Thanks for creating the issue though, I'd love to remove this step down the road.

**./scripts/types.sh**

```sh
#!/usr/bin/env sh
set -e

# So we can use the environment variables
source .env
./node_modules/.bin/openapi-typescript $OPENAPI_SCHEMA_URL/rest/v1/?apikey=$ACCESS_TOKEN --output app/types/supabase.ts
```

**package.json**

```json
  ...
  "build:types": "./scripts/types.sh",
  ...
```

**Comment by drwpow** [comment]
This is interesting. While I’m not necessarily opposed to this, I think there could be some unexpected behavior here.

I’ll consider adding this, but in the meantime I’d suggest either using [dotenv-cli](https://github.com/entropitor/dotenv-cli) to prefix the type generation, or using the Node.js API along with dotenv

**Comment by drwpow** [comment]
Update on this: if you’d like to consume env vars, then please use the `format()` option (v5) or the `transform()`/`postTransform()` options (v6) to handle when/how your env vars get loaded. This library won’t handle any environment variables for you as that’s somewhat of a security rabbit hole!
