### ISSUE TITLE
required attribute ignored when provided inline with properties

### ISSUE THREAD

**Issue by wereHamster** [drwpow/openapi-typescript#886]
I have a schema that includes `required` attributes with the individual properties (see below). The generated TypeScript type has these optional (ie. `id?: string; name?: string`).

If I change the schema to use one `"required": ["id", "name"]` on the same level as `properties` then the generated types are correct.

I'm not a OpenAPI spec expert so I don't know if the schema I'm working with is valid. 

```json
{
  "/foo/v3/bar": {
    "get": {
      "responses": {
        "200": {
          "content": {
            "application/json": {
              "schema": {
                "items": {
                  "properties": {
                    "id": { "format": "uuid", "required": true, "type": "string" },
                    "name": { "required": true, "type": "string" }
                  },
                  "type": "object"
                },
                "type": "array"
              }
            }
          },
          "description": "call successful"
        }
      }
    }
  }
}
```

**Comment by drwpow** [comment]
I’m going to close as I believe this to be a schema question. But if there’s something I missed or if types are being generated that disagree with your schema, please re-open or reply to this issue.
