### ISSUE TITLE
Replace params in paths with explicit types

### ISSUE THREAD

**Issue by Powell-v2** [drwpow/openapi-typescript#889]
Hi!

Would it be possible to substitute param names with real types within the `paths` export?

For example:

```ts
export interface paths {
  "/api/user/{id}": {
    get: ...
  }
}
```

=>

```ts
export interface paths {
  `/api/user/${number}`: {
    get: ...
  }
}
```

This change will allow plugging paths seamlessly into the fetching client. Currently paths with params require an explicit type assertion:

```ts
fetchJson<IUser>(`user/${id}` as 'user/{id}'))`
```

Happy to contribute if needed, given a tiny bit of guidance : )

Thank you!

**Comment by drwpow** [comment]
I don’t think TypeScript supports string literals / replacement in interfaces? I don’t think TypeScript can statically analyze runtime values. But if there is a way to do this I’d be in favor of adding.

**Comment by Powell-v2** [comment]
I wasn't entirely sure myself when creating this issue 😄 

Looks like it's doable, after all. I've put together an [example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4Chm+QbQGsIBPALmQAMB6OAB2GoFcBnaagEgxCYFsAjaAF9KAXQoswUUAHMceIqQo16jVuy48Bw6iAiSIAE07c+gqCPHJJ0kHKFYsCAPYhJyOBXQBeTPNwA5LQMzGxQ1ACsARQBMMAAbhABADT+yEGqoewRuvqQxgCc0elxiQD6IKBJWA5Oru7qUACShsi+BQAMHQDMdW5gyHRwYAAWFMQkzjBouL4qIY0mjS0iQA) for you to take a look at - let me know if that's gonna work.

**Comment by drwpow** [comment]
Whoa! TIL. If you wanted to add this via a flag I think it would be a good addition. I personally like adding unit tests first to figure out the end syntax, then work backwards to make it happen.

Would love help on someone making a PR on this (and can help if you run into any snags)

**Comment by Powell-v2** [comment]
I can certainly give it a shot. Will keep you posted about my progress!

**Comment by Powell-v2** [comment]
@drwpow the PR is ready - please take a look when you have an opportunity. Thank you!
