### ISSUE TITLE
Falsy example value do not generate comments in output

### ISSUE THREAD

**Issue by vietanhtran16** [drwpow/openapi-typescript#890]
When we do the below to generate interface from schema, when `example` value is false, it does not generate the comment for the example value but when `example` value is true, it does. Could we have an option to allow this or even make it default? Thanks

Schema
```
openapi: 3.0.3
components:
  schemas:
    Config:
      type: object
      properties:
        IsEnable:
          type: boolean
          example: false // this is the value I am talking about
```

Expected output
```
export interface components {
  readonly schemas: {
    readonly Config: {
        /** @example false */
        readonly IsEnable: boolean
    }
  }
}
```

Actual output
```
export interface components {
  readonly schemas: {
    readonly Config: {
        readonly IsEnable: boolean // comment is not generated
    }
  }
}
```

**Comment by drwpow** [comment]
Ah this seems like a classic falsy check gone wrong. Would be open to a PR & test to catch this if anyone has time.
