### ISSUE TITLE
The requested module 'undici' does not provide an export named 'request'

### ISSUE THREAD

**Issue by alexander-esser** [drwpow/openapi-typescript#920]
When I run `npx openapi-typescript foo.json --output foo.ts`, using the version from the _main_ branch, I receive the following error:

```
node_modules/openapi-typescript/dist/load.js:6
import { request } from "undici";
         ^^^^^^^
SyntaxError: The requested module 'undici' does not provide an export named 'request'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

Removing the curly brackets around `request` in _node_modules/openapi-typescript/dist/load.js:6_ resolves the problem.

**Comment by alexander-esser** [comment]
See also https://bobbyhadz.com/blog/javascript-requested-module-not-provide-export-named

**Comment by Mayank-jain34** [comment]
+1

**Comment by drwpow** [comment]
This should be fixed in the upcoming version!
