### ISSUE TITLE
Missing response headers when body type is empty (3XX or 204 response)

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [drwpow/openapi-typescript#921]
Type definitions for headers are missing in 3XX and 204 responses, or any response without a content type.

This problem happens with any header (`Location`, `Set-Cookie`, etc.)

**Actual result**

For instance the generated type definition for a 303 response is:

```ts
{
  303: never;
}
```

**Expected result**

But if headers are defined in the schema, it should generate this instead:

```ts
{
  303: {
    headers: {
      Location: string;
    };
    content: never;
  };
}
```

**Comment by javier-garcia-meteologica** [comment]
This error seems to be caused by an early return/continue. If there is no response content, the `continue` statement prevents advancing to the headers.

https://github.com/drwpow/openapi-typescript/blob/f9229a2e7da9e6b8ac5375577c6194598a7cab91/src/transform/responses.ts#L28-L45

**Comment by drwpow** [comment]
This should now be fixed! But please let me know if the issue persists.
