### ISSUE TITLE
x-nullable does not work (anymore) ?

### ISSUE THREAD

**Issue by raskyer** [drwpow/openapi-typescript#923]
Hi there,

I have an API Swagger 2.0 schema auto generated from Azure API. To have a nullable property, Azure only supports "x-nullable" so the definition of one property in model migth look like :
```json
"description": {
  "type": "string",
  "x-nullable": true
},
```

But when I do : `npx openapi-typescript ..\schema.json --output .\services\api.ts --version 2`

The typescript definition look like :
```ts
Model: {
  description: string;
};
```

**Comment by drwpow** [comment]
In v6 and beyond we’re dropping Swagger 2.0 support (#961). And in newer versions, `x-*` properties are ignored and should be handled by the consumer.

You can provide an override either with the `format()` option (v5) or the `transform()`/`postTransform()` options (v6) so you can control exactly what gets generated.
