### ISSUE TITLE
Folder as output doesn't work

### ISSUE THREAD

**Issue by AzazelloB** [drwpow/openapi-typescript#925]
This command `npx openapi-typescript src/api/v1.0/schemas/**/*.json --output src/api/v1.0/types/` throws an error "src/api/v1.0/types/src/api/v1.0/schemas/schema.ts". Because in openapi-typescript/bin/cli.js:120 filename is not actually a filename.

Possible fix:
replace: ``const filename = pathToSpec.replace(new RegExp(`${path.extname(pathToSpec)}$`), ".ts");``
to: ``const filename = path.basename(pathToSpec.replace(new RegExp(`${path.extname(pathToSpec)}$`), ".ts"));``

**Comment by drwpow** [comment]
I think there is a bug here, but I’m having a little trouble understanding how to reproduce it. Could you list out the contents of all your `.json` files so I could recreate?

**Comment by AzazelloB** [comment]
Cannot reproduce this issue myself anymore. Don't know what was it. The only inconvenience now that in a folder structure like that
```
├── src
│   ├── api
│   │   ├── v1.0
│   │   │   ├── schemas
│   │   │   │   ├── file1.json
│   │   │   │   ├── file2.json
│   │   │   ├── types
```
it creates .ts file with full folder path in the name
```
├── src
│   ├── api
│   │   ├── v1.0
│   │   │   ├── schemas
│   │   │   │   ├── file1.json
│   │   │   │   ├── file2.json
│   │   │   ├── types
│   │   │    │  ├── src
│   │   │    │  │   ├── api
│   │   │    │  │   │   ├── v1.0
│   │   │    │  │   │   │   ├── schemas
│   │   │    │  │   │   │   │   ├── file1.ts
│   │   │    │  │   │   │   │   ├── file2.ts
```

Which is inconvenience but expected

**Comment by BTMPL** [comment]
Was anyone able to sidestep this issue? Downgrading to 5.x solves the problem, but I'd like to use the native `fetch` helper, which was added in 6.x
