### ISSUE TITLE
Anyway to short circuit bodies

### ISSUE THREAD

**Issue by shuat** [drwpow/openapi-typescript#927]
Am I getting this correct that I need to do all this drilling to get body type?
type ForgotPassBody = operations["forgotPassword"]["requestBody"]["content"]["application/json"]

Is there any shorter way?

**Comment by drwpow** [comment]
That’s correct. It is annoying, but the reality is that the OpenAPI schema supports many characters that are invalid TypeScript names (e.g. the `.` character is valid in a name), and some public schemas actually do use those characters. In the service of accepting any valid OpenAPI schema, this syntax had to be adopted.

It’s a good pattern to follow your example and manage friendly names for your schema objects yourselves. But also, your schema could be improved by better use of the `components` path—that could be `components['schemas']['ForgotPassBody']` if your schema organized it that way.

When OpenAPI schemas make good use of `components`, it’s not so bad to only go a few levels deep.

**Comment by drwpow** [comment]
As this was a question, and is something that won’t be changed with this library, I’m going to close this issue. But please reply with any add’l questions or if you have a good suggestion on something that can be added to the docs to make this clearer!
