### ISSUE TITLE
Running openapi-typescript [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by aquaductape** [drwpow/openapi-typescript#928]
Since v5.0.0, openapi-typescript switched to full ESM support. If I install version before 5.0.0, my setup works, but I want need to use the latest version.

I have a simple minimal project https://github.com/aquaductape/test-openapi-ts, where there's 3 files: a typescript file, tsconfig.json, and package.json.

`createTypes.ts`
```ts
import * as fs from "fs";
import * as path from "path";
import openapiTS from "openapi-typescript";

const updateTypes = async () => {
  const openapiUrl = `/rest/v1/?apikey=`;
  const output = await openapiTS(openapiUrl, {
    formatter: (node) => {
      if (node.format === "jsonb") {
        return "any";
      }
    },
  });

  fs.writeFileSync(path.join("types", "supabase.ts"), output);
};

updateTypes();

```
`tsconfig.json`
```json
// tsconfig is from a NextJS project where I'm having this issue
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "target": "ES2016",
    "module": "ESNext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "baseUrl": "./[root]",
    "checkJs": true,
    "jsx": "preserve",
    "downlevelIteration": true,
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```
`package.json`
```json
{
  "scripts": {
    "build": "tsc createTypes.ts && node createTypes.js"
  },
  "dependencies": {
    "@types/node": "^18.6.3",
    "openapi-typescript": "^5.4.1",
    "typescript": "^4.7.4"
  }
}

```

So I encounter the error when I run a script from package.json, `npm run build` which is `"build": "tsc createTypes.ts && node createTypes.js"`. tsc successfully compiles the ts file to js, but when I run the js file with node, I get ESM error.

```
> build
> tsc createTypes.ts && node createTypes.js

/Users/caleb/Documents/just-programming/test-openapi-ts/createTypes.js:41
var openapi_typescript_1 = require("openapi-typescript");
                           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/caleb/Documents/just-programming/test-openapi-ts/node_modules/openapi-typescript/dist/index.js from /Users/caleb/Documents/just-programming/test-openapi-ts/createTypes.js not supported.
Instead change the require of index.js in /Users/caleb/Documents/just-programming/test-openapi-ts/createTypes.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/caleb/Documents/just-programming/test-openapi-ts/createTypes.js:41:28) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by drwpow** [comment]
Ah in your `tsconfig.json` you have `"noEmit": true`, so when you run `tsc` (which automatically locates `tsconfig.json`) nothing will happen. It should be noted that when running `tsc [fileName]`, it will ignore any config and just compile TS using default settings (CommonJS Node). That’s why the output `.js` file has require statements even though it shouldn’t (`"target": "ES2016"` shouldn’t have any `require()` statements).

Once you fix this, and your `createTypes.js` is in ESM, you’ll encounter your next issue:

```
SyntaxError: Cannot use import statement outside a module
```

The easiest way to fix this is to add `"type": "module"` to your `package.json` ([docs](https://nodejs.org/api/packages.html#packagejson-and-file-extensions)). Or, you can rename all ESM files to `.mjs`, but this is a bit annoying to do as TypeScript doesn’t have an option for this (unless I’m mistaken!)

**Comment by drwpow** [comment]
I don’t think this is an issue with this library, so I’m going to close this issue, but please let me know if you encounter any other problems!

**Comment by mkosir** [comment]
Hey @aquaductape, having the same issue and interested if you came to the bottom of this?
Can't make it work with v5.x or find any working example in the docs/issues 🤔

**Comment by mkosir** [comment]
This ESM was a roller coaster, finally was able to do it, leaving bellow for anyone coming after me:

Create `tsconfig.openapi-typescript.json` for ESM transpile
```ts
{
  "compilerOptions": {
    "moduleResolution": "node"
  },
  "ts-node": {
    "compilerOptions": {
      "module": "esnext",
      "target": "ESNext" // to allow  top-level await expressions set it to 'ES2017' or higher
  }
}

```
In `package.json` you can add `"type": "module"`, but I prefer to avoid it since it can mess other "non-ESM" scripts.
Instead add a script to it, notice `ts-node-esm` and `generate.mts` file extension:
```ts
 "api-generate-petstore": "ts-node-esm -P tsconfig.openapi-typescript.json generate.mts"
```

Create `generate.ts`:
```ts
import openapiTS, { SwaggerToTSOptions } from 'openapi-typescript';

const URL_SCHEMA_PET_STORE =
  'https://raw.githubusercontent.com/swagger-api/swagger-petstore/master/src/main/resources/openapi.yaml';

const OPENAPI_TS_OPTIONS: SwaggerToTSOptions = {
  immutableTypes: true,
  exportType: true,
};

const output = await openapiTS(URL_SCHEMA_PET_STORE, OPENAPI_TS_OPTIONS);
console.log('Output: ', output);
```

@drwpow I think some similar "instrucitons" how to run it in Node, could be added to docs/readme, since other developers might find it useful.

**Comment by aquaductape** [comment]
@mkosir sorry for late response, could have saved you time. 

I ended up using esbuild script within my nextjs project, so I can use the latest version of this library, I didn't have to change any of the nextjs settings.

nextjs structure
```
build-scripts
├── build.js
└── cleanup.js
scripts
└── createSupabaseTypes.ts
package.json
```

`build-scripts/build.js`
```js
const { build } = require('esbuild');
const glob = require('glob');
const entryPoints = glob.sync('./scripts/createSupabaseTypes.ts');

build({
  entryPoints,
  outbase: './scripts',
  outfile: './temp-dir/index.js',
  platform: 'node',
  bundle: true,
  external: [],
  watch: false,
});

```

`build-scripts/cleanup`
```js
const rimraf = require('rimraf');

const tempDir = './temp-dir';

rimraf.sync(tempDir);

```
`package.json`
```json
{
  "scripts": {
    "build:types": "node ./build-scripts/build.js && node ./temp-dir/index.js && node ./build-scripts/cleanup.js",
  },
  "devDependencies": {
    "esbuild": "0.11.14",
    "glob": "7.1.6",
    "openapi-typescript": "^5.4.1",
    "rimraf": "^3.0.2",
  }
}

```

**Comment by mkosir** [comment]
@aquaductape thx for sharing you solution variant with esbuild. I guess we are still some time away from working with ESM modules seamlessly 🙂
