### ISSUE TITLE
Sponsors/donate

### ISSUE THREAD

**Issue by nmhub** [drwpow/openapi-typescript#930]
Have you considered adding a sponsor / buymeacoffee button to this project? I love using openapi-typescript and would like to thank all the contributors.

**Comment by drwpow** [comment]
Really appreciate it! Though there have been many, many [contributors](https://github.com/drwpow/openapi-typescript#-contributing), I’m currently the only maintainer.

Last year I was working as a full-time employee at an OSS company, so accepting GitHub sponsorship would have been a bit eyebrow-raising. But now that I’m working at a private company again and work on this unpaid in my free time, I’ll consider adding a sponsorship link in the future 🙂
