### ISSUE TITLE
Add support for OpenAPI 3.1

### ISSUE THREAD

**Issue by jamietanna** [drwpow/openapi-typescript#933]
I'm not sure it's explicitly called out as whether it's supported or not, so just thought I'd flag this to check what we support, and if it's only 3.0, I'll get a README update accordingly

**Comment by drwpow** [comment]
Handled as part of #968. Going to close because the large features have been added such as polymorphism and discriminators as well as some other minor tweaks. But beyond that if there are any individual missing features from 3.1, please open another issue.
