### ISSUE TITLE
`--make-paths-enum` throws error if path has hyphen (`-`)

### ISSUE THREAD

**Issue by dheeraj-jn** [drwpow/openapi-typescript#934]
Given a path with an embedded hyphen (in general, characters invalid in a JavaScript identifier) such as `/api/v1/pet-cats`, using `--make-paths-enum` throws the following error by `prettier`:

```
SyntaxError: An enum member name must be followed by a ',', '=', or '}'.
>  pet-cats = "/api/v1/pet-cats",
      ^
```
@berzi

**Comment by berzi** [comment]
This can be solved by giving a unique `operationId` to the path: the script will then use it as name for the enum member.

What I could do at best would be to add documentation on this and throw a more explicit error at types generation time if the name is not valid, but I don't think the script should try to convert hyphenated names automatically, or you run the risk of having duplicated enum keys, which is harder to prevent from opneapi-typescript's side.

@drwpow Opinions?

**Comment by dheeraj-jn** [comment]
I already had specified `operationId` but even the `operationId` had a hyphen  🤦‍♂️.
Removing the hyphen from `operationId` fixes the issue.

Thanks @berzi
