### ISSUE TITLE
--make-paths-enum fails when path contains -

### ISSUE THREAD

**Issue by jacob-rede** [drwpow/openapi-typescript#935]
If the api.json file contains a path with a `-` it will fail to convert when `--make-paths-enum` parameter is added. ex:

`{
  "openapi": "3.0.0",
  "paths": {
    "/service-information": {        
      }
    }
}`

```
Error:
(node:80694) UnhandledPromiseRejectionWarning: SyntaxError: An enum member name must be followed by a ',', '=', or '}'. (299:10)
  297 | export enum ApiPaths {
  298 |   health = "/health",
> 299 |   service-information = "/service-information",
```

**Comment by tonyxiao** [comment]
Just got this too. For repo, e.g. `openapi-typescript https://dash.readme.com/api/v1/api-registry/rwkfe1gl7puob14 --make-paths-enum --output onebrick.gen.ts`

**Comment by drwpow** [comment]
v6 just released, and it’s dropped the `--make-paths-enum` option because it conflicted with `--path-params-as-types` and because of outstanding bugs like this.
