### ISSUE TITLE
Support for x-alternatives

### ISSUE THREAD

**Issue by pedromcunha** [drwpow/openapi-typescript#937]
Hi! Thanks for creating such a handy tool to generate typescript types from openapi/swagger2 schemas.

We're running into an issue where some parameters with `x-alternatives` types are not being properly generated in typescript. Here's an excerpt from our schema:

```
   "fee":{
      "type":"string",
      "pattern":"^[0-9]+$",
      "x-alternatives":[
         {
            "type":"string",
            "pattern":"^[0-9]+$"
         },
         {
            "type":"number"
         },
         {
            "$ref":"#/x-alt-definitions/fee"
         },
         {
            "$ref":"#/x-alt-definitions/Model6"
         }
      ]
   }
```

It could also be that we're doing something wrong here, is there any way to allow for multiple types to be valid?
Here's a link to the full schema:
https://api.reservoir.tools/swagger.json

**Comment by drwpow** [comment]
I think that anything prefixed by `x-*` should be handled by the consumer. Going forward, the best way to handle this would be using the `format()` option (v5) or `transform()` option (v6) to handle the type generation as you wish.

I’m going to mark this as closed as that API will give you full control over what gets generated, but let me know if I’m missing anything.
