### ISSUE TITLE
[Feature Request|Question] Make all types up to date with actual OpenAPI schema

### ISSUE THREAD

**Issue by ThaDaVos** [drwpow/openapi-typescript#939]
It seems that different parts of the types are not up to date with the full OpenAPI schema,

for example, `securitySchemes` is missing in the `components`, in `schemaObject` it's missing `maxLength` if type is `string` and so fort...

Is this intentional? Or is it simply a oversight?

**Comment by drwpow** [comment]
Thanks for filing! If you have a request for a specific addition, it would be really helpful for each addition to outline:

1. The source OpenAPI schema code (ideally simplified, but providing a full spec is fine, too)
2. The proposed TypeScript types it should generate.

Given that TypeScript is not a 1:1 translation from OpenAPI, there are parts of the schema that aren’t obvious how or even if they should be typed. But for the additions mentioned, any proposals/PRs would be welcome.

**Comment by drwpow** [comment]
Thanks again for filing. There’s a new **Missing syntax** issue template that would be extremely helpful for filling out specifics on what’s missing.

Security schemas has an open issue at #922.

I’m not sure how one would support `maxLength` for strings as this can’t validate runtime values; only provide static typings.

But again, opening up specific issues would be really helpful, thank you!
