### ISSUE TITLE
--make-paths-enum generate enum with another paths

### ISSUE THREAD

**Issue by Semigradsky** [drwpow/openapi-typescript#950]
For example, it generates
```ts
export interface paths {
  '/download/{p1}': {
    // ...
  },
}

export enum ApiPaths {
  getDownload: '/download/:p1',
}
```

So I can't choose type:
```ts
type X = paths[ApiPaths.getDownload] // error
```

---

As I see, that is why paths in `export interface paths {` and `export enum ApiPaths {` are different:
https://github.com/drwpow/openapi-typescript/blob/a4e05fa005277ea1e42eb191921aae5d9f51293a/src/transform/paths.ts#L127-L128

@berzi hi! Could you answer if this change is needed?

**Comment by Semigradsky** [comment]
@drwpow or it can be customized by option...

**Comment by drwpow** [comment]
This makes sense to me! Thanks for making this change.

**Comment by Semigradsky** [comment]
@drwpow is it possible to release this in 5.x version? As I see this feature was totally removed in 6.x

**Comment by insertmike** [comment]
This was somewhat broken again?? @drwpow
