### ISSUE TITLE
Error when `$ref` uses escape characters

### ISSUE THREAD

**Issue by ganlhi** [drwpow/openapi-typescript#956]
In a file these paths are defined: 

```yaml
paths:
  /public/v1/foos:
    get:
      operationId: getFoos
      tags:
        - Foo
      description: Foo foo foo foo.
      responses:
        "200":
          description: The foos
          content:
            application/json:
              schema:
                $ref: './otherfile.yaml#/components/schemas/Foos'
        "422":
          description: A validation error, invalid or missing supplier ID.
  /public/v1/{id}/foos:
    get:
      operationId: getFoosWithID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      description:
        $ref: "#/paths/~1public~1v1~1foos/get/description"
      tags:
        $ref: "#/paths/~1public~1v1~1foos/get/tags"
      responses:
        $ref: "#/paths/~1public~1v1~1foos/get/responses"
```

It looks like `openapi-typescript` doesn't like the escape characters `~1`. I get the following error: 
```
file://.../node_modules/openapi-typescript/dist/utils.js:41
    const commentText = text.trim().replace(COMMENT_RE, "*\\/");
                             ^
                             
TypeError: text.trim is not a function
    at comment (file://.../node_modules/openapi-typescript/dist/utils.js:41:30)
    at transformPathsObj (file://.../node_modules/openapi-typescript/dist/transform/paths.js:53:27)
    at transformAll (file://.../node_modules/openapi-typescript/dist/transform/index.js:27:25)
    at openapiTS (file://.../node_modules/openapi-typescript/dist/index.js:57:23)
    at async generateSchema (file://.../node_modules/openapi-typescript/bin/cli.js:97:18)
    at async file://.../node_modules/openapi-typescript/bin/cli.js:196:7
    at async Promise.all (index 63)
    at async main (file://.../node_modules/openapi-typescript/bin/cli.js:185:3)
```

**Comment by liangskyli** [comment]
Same as this bug： #915

**Comment by liangskyli** [comment]
why use ~ characters in $ref?

**Comment by ganlhi** [comment]
These are [escape characters](https://swagger.io/docs/specification/using-ref/) for `/`. You cannot write `$ref: "#/paths//public/v1/foos/get/responses"`.

**Comment by mitchell-merry** [comment]
Hm, I don't think we support `$ref` in those places. From what I can tell, the breaking prop here is `responses`, and I don't think you can have the top-level `responses` object be a ReferenceObject: https://swagger.io/specification/#responses-object.

**Comment by drwpow** [comment]
The new `6.5.2` allows you to define [JSONSchema $defs](https://json-schema.org/understanding-json-schema/structuring.html#defs) on object types and the root schemas as `3.1` is an extension of JSONSchema (but technically we won’t stop you from using this on `3.0` schemas—this isn’t a validator, after all).

This will be the preferred way of referencing sub-schemas like this, because in the transformation to TypeScript we can’t guarantee an arbitrary property will or won’t be there.

I believe this solves the original issue! But please open up another issue if `$defs` isn’t behaving as expected.
