### ISSUE TITLE
📣 v6.0 RFC and call for contributors

### ISSUE THREAD

**Issue by drwpow** [drwpow/openapi-typescript#961]
### 👯‍♂️ v6.0

openapi-typescript has an upcoming 6.0 version, which started as [a breaking change](https://github.com/drwpow/openapi-typescript/pull/895) but has now expanded to include the following as well:

- [x] OpenAPI 3.1 support
   - [x] polymorphism (#969)
   - [x] `discriminator` (#953)
- [x] Closer adherence to the spec
- [x] Better JSDoc comment generation
- [x] Library cleanup to make contributions easier
- [x] Improvements to the formatter (now called `transform()`)

### 🤝 Call for contributors

This library would love to have more contributors and maintainers help keep this project going! In service of this, I’ve recently added:

- Issue templates for better bug filing
- Improved [contributor docs](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md) to make contributions friendlier
- Codebase cleanup that makes onboarding simpler.

If you’ve been interested in contributing to opensource, or if you’ve found this tool useful at your workplace or personal projects and would love to contribute, please raise a hand ✋! Anyone of any skill level and experience with the project is welcome 🙂

_Note that at this time, contributing monetarily isn’t necessary. Perhaps in the future, but for now this library is held back by time constraints and number of maintainers._

### ❓ v6.0 RFC

Would love some 👍 or 👎 (comments welcome) on the following changes for 6.0 and beyond:

#### ❓ 1. Dropping Swagger 2.x support

Swagger 3.0 has been out for 5 years now and already many (most?) APIs have fully made the leap to 3.x. Anecdotally I haven’t seen an active 2.0 schema in the wild for quite some time. Dropping support for 2.x would shed quite a bit of dead weight in the codebase and allow for faster releases. Of course, users of Swagger 2.x could always use `openapi-typescript@5` indefinitely to generate types for their 2.x schemas, but won’t receive any future updates.

#### ❓ 2. Dropping Prettier

Prettier was originally added as a lazy way to clean up the generated output. But with the in-progress code improvements, the output is much better formatted to the point Prettier isn’t needed (to be clear, the output doesn’t and never will match Prettier 100%, but it’s still formatted neatly to the point Prettier isn’t needed). Dropping Prettier would mean **much faster generation** (initial testing shows a 3× speedup on large schemas) and it would also shed this library’s weight by quite a bit. And users could use their formatting method of choice (#959).

#### ❓ 3. Keeping string manipulation (over AST transformation)

There are 2 types of codegen libraries: those that use **string manipulation**, and those that use **AST transformation.** This library uses the former initially out of expediency, but over the years has stuck with this pattern for ease of maintenance and performance. Even though there’s no change here, the idea of switching to TypeScript’s AST has been raised before, and I wanted to raise it again. I won’t explain the pros/cons of each here, because if no one reading is familiar with how ASTs work I think I’ve made my point and ASTs would be harder to maintain 😉. But regardless, thoughts are welcome for those that have them here.

#### ❓ 4. [Insert your idea here]

If you’d like to propose something not mentioned here, either **as a breaking change** or as **a feature request,** please speak now! For ideas, you can look back at suggested [enhancements](https://github.com/drwpow/openapi-typescript/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) that haven’t been implemented yet.

---

🙏 Thanks so much for all the support you’ve given this library. I can’t believe a simple little tool we made at a past company has resulted in millions of downloads and is used in thousands of projects. Thanks for all the PRs, bugfixes, and passionate contributions made by this community! 

Here’s to an even better, and faster v6 (and beyond) 😎

**Comment by drwpow** [comment]
Update: this is largely done in #968. Once that merges, it’ll just be adding back missing tests.

**Comment by drwpow** [comment]
v6.0.0 shipped! 🎉

The call for contributors is still open. Any bug testing and PRs fixing bugs are welcome!

**Comment by yacinehmito** [comment]
Raising a hand 🤚 
(that doesn't exist as a reaction, sorry)

I plan to use openapi-typescript extensively at our company. I have a keen interest in making the library portable to other runtimes (browser, Deno, Cloudflare Workers), without compatibility layers.

**Comment by benevbright** [comment]
Is it currently possible to get `paths` as an object for runtime?

**Comment by drwpow** [comment]
@npbenjohnson @rxliuli you both make some compelling arguments for using AST! While it probably wouldn’t change the overarching logic of this codebase a whole lot, if you feel it would lower the barrier to entry I’d be all for it. Having written quite a few Babel transformers myself, and talking to the maintainers, I just think about how hard it was for that project to write docs or get contributors because of the complexity.

But on the other hand, transformation is transformation, and expressing the problem in a syntax meant for transformation isn’t a complexity add; quite the opposite.

I do like ast-types/recast’s syntax, as you mentioned, @rxliuli. Agreed it looks simpler than TypeScript’s native syntax. Perhaps there’s some interesting approach we could take that doesn’t inherit TS’ weirdness or slowness when it comes to compile. Because love or hate this library’s current approach of string mashing, at least it’s fast! 😄

**Comment by mitchell-merry** [comment]
Officially raising my hand ✋🏻!

**Comment by sregg** [comment]
6.0 has been out for 6 months. Should this be still open?
