### ISSUE TITLE
[string, null] definition is converted to unknown

### ISSUE THREAD

**Issue by LarsOlt** [drwpow/openapi-typescript#969]
**Description**

Source:
![image](https://user-images.githubusercontent.com/32353679/199654166-967cffc7-f4e5-46cf-9e40-b9b4c895b7f9.png)

Output: 

![image](https://user-images.githubusercontent.com/32353679/199654237-1220f03b-c3dd-4117-98f6-7c21ef950365.png)

Expected:

`"image-path": string | null`

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `5.4.1`                      |
| Node.js              | `16.18.0`                      |
| OS + version         | `Win 11` |

**Reproduction**

_How can this be reproduced / when did the error occur?_

I am using the https://developers.themoviedb.org/ OAS API definition.

`npx openapi-typescript https://api.stoplight.io/v1/versions/9WaNJfGpnnQ76opqe/export/oas.json --output tmdb-oas.ts`

**Expected result**

_(in case it’s not obvious)_

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by LarsOlt** [comment]
Seems to be related to https://github.com/drwpow/openapi-typescript/issues/898 ?

**Comment by drwpow** [comment]
Thank you for raising! v6 will add OpenAPI 3.1 support so will make sure this makes it in.
