### ISSUE TITLE
`requestBody` missing `content` property

### ISSUE THREAD

**Issue by essential-randomness** [drwpow/openapi-typescript#972]
**Description**

After the refactoring, `requestBody` is missing `content` as a nested property. To doublecheck that it is supposed to be there, I tried generating it with the npm version vs the one in github.

NPM version (what I expected):
```
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email?: string;
          label?: string;
        };
      };
    };
```

Current version (what I believe is wrong):
```
    requestBody: {
      "application/json": {
        /** Format: email */
        email?: string;
        label?: string;
      };
    };
```

**Reproduction**

Sync with the current codebase and run the generator. Note that [the test](https://github.com/drwpow/openapi-typescript/blob/main/test/request-body-object.test.ts) is also missing this property.

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Thanks so much for taking the time to test the in-progress work! And thanks for being willing to open a PR. But there are some other things changing in the codebase and I wouldn’t want you to deal with that right now so I can make that change. But next time a PR would be very much appreciated! 🙂

**Comment by essential-randomness** [comment]
Thank you so much for working on this library :) I was stoked to finally find something that can handle my OpenAPI 3.1 declaration files, and the types have already helped me find a bunch of bugs! Very grateful for the work.
