### ISSUE TITLE
type integer oneOf minimum now a record

### ISSUE THREAD

**Issue by leppaott** [drwpow/openapi-typescript#980]
We have:

`"address": {
            "type": "integer",
            "oneOf": [
              {
                "minimum": 1,
                "maximum": 2
              },
              {
                "minimum": 5,
                "maximum": 6
              }
            ]`

This used to generate on 5.x:

`address?: number;`

Now we have:

`address?: Record<string, never> | Record<string, never>;`

Think the schema is valid.

**Comment by drwpow** [comment]
Thanks for filing. What would the desired TypeScript types look like for this, given that the `oneOf` objects are missing a `type`? This does pass a validator, you’re right, but I think `type` inheritance is not part of the schema?

**Comment by leppaott** [comment]
Right, you're saying that we could just add the `type` into each item inside `oneOf`. Not a schema expert, we're just validating this with Ajv and it's working. Then it's a good question is it inheriting the type - more generic or is it just guessing based on `minimum` as:

> [6.2.4. ](https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.2.4)[minimum](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-minimum)
The value of "minimum" MUST be a number, representing an inclusive lower limit for a numeric instance.

> If the instance is a number, then this keyword validates only if the instance is greater than or exactly equal to "minimum".

Yeah not an expert is this legal usage then, I guess if it works shouldn't the types be OK too. I was expecting `address?: number` and can't see where the `Record<>` comes from seeing there is no `type object` either.
