### ISSUE TITLE
$ref in parameters is not working

### ISSUE THREAD

**Issue by axelhzf** [drwpow/openapi-typescript#989]
**Description**

Using `$ref` in the parameters section does not generate the type correctly

**OpenAPI**

```json
{
  "openapi": "3.0.3",
  "info": {
    "title": "",
    "version": ""
  },
  "paths": {
    "/get": {
      "parameters": [
        {
          "$ref": "#/components/parameters/limit"
        }
      ]
    }
  },
  "components": {
    "parameters": {
      "limit": {
        "required": true,
        "in": "query",
        "name": "limit",
        "schema": {
          "type": "number"
        }
      }
    }
  }
}
```

**Generated TS**

```ts
export interface paths {
  "/get": {

  };
}

export interface components {
  schemas: never;
  responses: never;
  parameters: {
    limit: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
```

**Expected TS*

```ts
export interface paths {
  "/get": {
     parameters: {
        query: {
           limit: components['parameters']['limit']
        }
     }
  };
}
```

**Checklist**

- [x] My OpenAPI schema passes a validator
- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by axelhzf** [comment]
I think that the problem could be in this part of the code https://github.com/drwpow/openapi-typescript/blob/main/src/transform/operation-object.ts#L72-L74

This is expecting `paramIn` to be part of the ref like `components["parameters"]["query"]["limit"]` but it is actually `components["parameters"]["limit"]`

**Comment by wolfy1339** [comment]
I actually had opened #984 with this exact problem.

**Comment by axelhzf** [comment]
Ops, I didn't realize your issue is the same
